### ISSUE TITLE
Workspace produced by ConvertToYSpace has X axis with decreasing values from left.

### ISSUE THREAD

**Issue by abuts** [mantidproject/mantid#10489]
This issue was originally [TRAC 9646](http://trac.mantidproject.org/mantid/ticket/9646)

This ticket is blocks :  [TRAC11618](http://trac.mantidproject.org/mantid/ticket/11618)

Run script below and try to view the resulting workspace in sliceviewer. 

Mantid is throwing unexpected exception while creating Histo dimension.

```

 tof_ws = CreateSimulationWorkspace(Instrument='MAR',BinParams=[-50,2,50],UnitX='TOF')
SetInstrumentParameter(tof_ws,ParameterName='t0',ParameterType='Number',Value='0.5')
SetInstrumentParameter(tof_ws,ParameterName='efixed',ParameterType='Number',Value='30.')    
###### Convert data to format acceptable by ConvertToYSpace
tof_ws = ConvertToPointData(tof_ws)
###### Convert to Y Space
wsY=ConvertToYSpace(InputWorkspace='tof_ws',Mass='30')

```

**Comment by martyngigg** [comment]
This workspace won't plot as a colorfill in workbench or in the new sliceviewer. I assume it's the same reason.
The colorfill plot gives an error:
```
Traceback (most recent call last):
  File "/home/mgigg/Code/mantidproject/mantid/qt/applications/workbench/workbench/plugins/workspacewidget.py", line 137, in _do_plot_colorfill
    pcolormesh(names)
  File "/home/mgigg/Code/mantidproject/mantid/Framework/PythonInterface/mantid/plots/plotfunctions.py", line 56, in inner_func
    return func(workspaces, *args, **kwargs)
  File "/home/mgigg/Code/mantidproject/mantid/qt/python/mantidqt/plotting/functions.py", line 199, in pcolormesh
    pcm = pcolormesh_on_axis(ax, ws)
  File "/home/mgigg/Code/mantidproject/mantid/qt/python/mantidqt/plotting/functions.py", line 249, in pcolormesh_on_axis
    pcm = ax.imshow(ws, cmap=ConfigService.getString("plots.images.Colormap"), aspect='auto', origin='lower')
  File "/home/mgigg/Code/mantidproject/mantid/Framework/PythonInterface/mantid/plots/mantidaxes.py", line 45, in wrapper
    func_value = func(self, *args, **kwargs)
  File "/home/mgigg/Code/mantidproject/mantid/Framework/PythonInterface/mantid/plots/mantidaxes.py", line 848, in imshow
    return self._plot_2d_func('imshow', *args, **kwargs)
  File "/home/mgigg/Code/mantidproject/mantid/Framework/PythonInterface/mantid/plots/mantidaxes.py", line 874, in _plot_2d_func
    plotfunctions_func(self, *args, **kwargs),
  File "/home/mgigg/Code/mantidproject/mantid/Framework/PythonInterface/mantid/plots/axesfunctions.py", line 637, in imshow
    transpose=transpose)
  File "/home/mgigg/Code/mantidproject/mantid/Framework/PythonInterface/mantid/plots/datafunctions.py", line 484, in get_matrix_2d_ragged
    x_centers = np.linspace(min_value, max_value, num=num_edges)
  File "/usr/lib/python3/dist-packages/numpy/core/function_base.py", line 103, in linspace
    raise ValueError("Number of samples, %s, must be non-negative." % num)
ValueError: Number of samples, -492, must be non-negative.
```
It looks like this produces an X axes that is in decreasing order.
`ConvertToYSpace` should probably reorder the axis like `ConvertUnits` does when it converts to momentum transfer.

**Comment by martyngigg** [comment]
Note that we must first understand how this will affect the Vesuvio reduction/fitting.
