### ISSUE TITLE
Create GUI-based script in Mantid to process HB3A data

### ISSUE THREAD

**Issue by wdzhou** [mantidproject/mantid#12122]
This issue was originally [TRAC 11283](http://trac.mantidproject.org/mantid/ticket/11283)

Create a graphic user interface in Mantid for HB3A of HFIR.  The feature should include (1) downloading the data files (SPICE text file and XML file) from a server via http link, (2) Load the data into a TableWorkspace, a MatrixWorkspace for log information and a workspace group containing MatrixWorkspaces, each of which corresponds to one measurement (Pt) of a scan. (3) Provide some convenience for user to visualize the data on 2D anger camera. (4) Calculate UB matrix; (5) Refine UB matrix; (6) Calculate lattice parameters from refined UB matrix; (7) Integrate peaks;

**Comment by wdzhou** [comment]
Error message 1:
Traceback (most recent call last):
  File "/home/wzz/Mantid/Code/Mantid/scripts/HFIR_4Circle_Reduction/reduce4circleGUI.py", line 292, in do_download_spice_data
    self._myControl.download_data_set(scan_list)
  File "/home/wzz/Mantid/Code/Mantid/scripts/HFIR_4Circle_Reduction/reduce4circleControl.py", line 213, in download_data_set
    status, spice_table = self.load_spice_scan_file(scan_no, spice_file_name)
  File "/home/wzz/Mantid/Code/Mantid/scripts/HFIR_4Circle_Reduction/reduce4circleControl.py", line 385, in load_spice_scan_file
    out_ws_name = 'Table_Exp%d_Scan%04d' % (exp_no, scan_no)
TypeError: %d format: a number is required, not str

**Comment by wdzhou** [comment]
Error message 2:
Traceback (most recent call last):
  File "/home/wzz/Mantid/Code/Mantid/scripts/HFIR_4Circle_Reduction/reduce4circleGUI.py", line 354, in do_plot_pt_raw
    self._plot_raw_xml_2d(exp_no, scan_no, pt_no)
  File "/home/wzz/Mantid/Code/Mantid/scripts/HFIR_4Circle_Reduction/reduce4circleGUI.py", line 536, in _plot_raw_xml_2d
    does_exist = self._myControl.does_spice_loaded(exp_no, scan_no)
AttributeError: 'CWSCDReductionControl' object has no attribute 'does_spice_loaded'
