### ISSUE TITLE
DSFinterp1DTest fails on OS-X

### ISSUE THREAD

**Issue by jmborr** [mantidproject/mantid#14967]
DSFinterp1DTest fails when package dsfinterp is installed and the test is run.

Excerpt from error message ( console-output at http://builds.mantidproject.org/job/pull_requests-osx/4514/console )

15:57:59 ERROR: test_LorentzianFit (__main__.DSFinterp1DTestTest)
15:57:59 Fit a set or Lorentzians with "noisy" HWHM against a reference lorentzian
15:57:59 ----------------------------------------------------------------------
15:57:59 Traceback (most recent call last):
15:57:59   File "/Users/builder/jenkins-linode/workspace/pull_requests-osx/Framework/PythonInterface/test/python/plugins/functions/DSFinterp1DFitTest.py", line 146, in test_LorentzianFit
15:57:59     Fit( Function=func_string, InputWorkspace= 'targetW', WorkspaceIndex=0, StartX=xvalues[0], EndX=xvalues[-1], CreateOutput=1, MaxIterations=20 )
15:57:59   File "/Users/builder/jenkins-linode/workspace/pull_requests-osx/build/bin/mantid/simpleapi.py", line 197, in wrapper
15:57:59     algm.setProperty('Function', Function) # Must be set first
15:57:59 ValueError: Invalid value for property Function (Function) "name=DSFinterp1DFit,InputWorkspaces=" sim0 sim1 sim2 sim3 sim4 sim5 sim6 sim7 sim8 sim9 sim10 sim11 sim12 sim13 sim14 sim15 sim16 sim17 sim18 sim19",ParameterValues=" 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2",LoadErrors=0,LocalRegression=1,RegressionType=quadratic,RegressionWindow=6,WorkspaceIndex=0,Intensity=1.0,TargetParameter=0.01;": min() arg is an empty sequence
15:57:59   at line 93 in '/Users/builder/jenkins-linode/workspace/pull_requests-osx/Framework/PythonInterface/plugins/functions/DSFinterp1DFit.py'
15:57:59   at line 62 in '/Users/builder/jenkins-linode/workspace/pull_requests-osx/Framework/PythonInterface/plugins/functions/DSFinterp1DFit.py'
15:57:59 
15:57:59 ======================================================================
15:57:59 FAIL: test_input_exceptions (__main__.DSFinterp1DTestTest)
15:57:59 Test exceptions thrown upon wrong input
15:57:59 ----------------------------------------------------------------------
15:57:59 Traceback (most recent call last):
15:57:59   File "/Users/builder/jenkins-linode/workspace/pull_requests-osx/Framework/PythonInterface/test/python/plugins/functions/DSFinterp1DFitTest.py", line 96, in test_input_exceptions
15:57:59     self.assertTrue('Number of InputWorkspaces and ParameterValues should be the same' in str(e))
15:57:59 AssertionError: False is not true
15:57:59 
15:57:59 ----------------------------------------------------------------------
15:57:59 Ran 2 tests in 0.101s
15:57:59 
15:57:59 FAILED (failures=1, errors=1)

**Comment by jmborr** [comment]
@quantumsteve issue opened

**Comment by jmborr** [comment]
This issues has been resolved in #14984
