### ISSUE TITLE
EQSANS GUI BUG

### ISSUE THREAD

**Issue by ricleal** [mantidproject/mantid#16291]
After adding BIOSANS / GPSANS new distances, the XML is not well exported.

1. When Loading 
`Detector distance offset``` loads a property, not a value: `<property object at 0x7fc3b27a91b0>`

2. When reducing the data, I have the error
```
Reduction could not be executed:

Traceback (most recent call last):
  File "/home/rhf/git/mantid/scripts/Interface/reduction_gui/instruments/interface.py", line 207, in reduce
    self.scripter.apply()
  File "/home/rhf/git/mantid/scripts/Interface/reduction_gui/reduction/scripter.py", line 494, in apply
    raise RuntimeError, sys.exc_value
RuntimeError: cannot import name PropertyManagerDataService
```
3. SaveCanSAS1D incorrectly saves SASprocess as SASProcess (typo).

4. The SANS reduction info in the cansas xml file should be in
```
<SASprocess><SASprocessnote> ... </SASprocessnote></SASprocess>
```

Point 2 can be solved by correcting: `from mantid import PropertyManagerDataService`

Test opening the file in the EQSANS GUI (Debug Mode On): `/SNS/EQSANS/IPTS-15454/shared/67315_Iq.xml`.

**Comment by ricleal** [comment]
@mdoucet Can you test this?
