### ISSUE TITLE
DataHandling::LoadEventNexus: AddressSanitizer: heap-buffer-overflow

### ISSUE THREAD

**Issue by SimonHeybrock** [mantidproject/mantid#17440]
From a run of units tests with Address Sanitizer (compiled with `-DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=-fsanitize=address`):

```
745/1683 Test #745: DataHandlingTest_LoadEventNexusTestPerformance ...............***Failed    5.41 sec
FrameworkManager-[Notice] Welcome to Mantid 3.7.20160907.1229
FrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid
Running 4 testsLoadEventNexus-[Notice] LoadEventNexus started
LoadEventNexus-[Notice] LoadEventNexus successful, Duration 2.33 seconds
.LoadEventNexus-[Notice] LoadEventNexus started
=================================================================
==98890==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6230000ee0e0 at pc 0x7f030f1602d2 bp 0x7f02d6c40970 sp 0x7f02d6c40960
READ of size 8 at 0x6230000ee0e0 thread T25
    #0 0x7f030f1602d1 in Mantid::DataHandling::ProcessBankData::run() /home/simon/code/mantid/Framework/DataHandling/src/ProcessBankData.cpp:61
    #1 0x7f030c8a1978 in Mantid::Kernel::ThreadPoolRunnable::run() /home/simon/code/mantid/Framework/Kernel/src/ThreadPoolRunnable.cpp:57
    #2 0x7f030bb1c2f9 in Poco::ThreadImpl::runnableEntry(void*) (/usr/lib/libPocoFoundationd.so.11+0x1732f9)
    #3 0x7f0309d806a9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76a9)
    #4 0x7f030a09deec in clone (/lib/x86_64-linux-gnu/libc.so.6+0x106eec)

0x6230000ee0e0 is located 32 bytes to the left of 6152-byte region [0x6230000ee100,0x6230000ef908)
allocated by thread T0 here:
    #0 0x7f03109021af in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x581af)
    #1 0x6237ca in __gnu_cxx::new_allocator<unsigned long>::allocate(unsigned long, void const*) /usr/include/c++/4.9/ext/new_allocator.h:104
    #2 0x622cfb in std::allocator_traits<std::allocator<unsigned long> >::allocate(std::allocator<unsigned long>&, unsigned long) /usr/include/c++/4.9/bits/alloc_traits.h:357
    #3 0x621d2b in std::_Vector_base<unsigned long, std::allocator<unsigned long> >::_M_allocate(unsigned long) /usr/include/c++/4.9/bits/stl_vector.h:170
    #4 0x6216be in std::_Vector_base<unsigned long, std::allocator<unsigned long> >::_M_create_storage(unsigned long) /usr/include/c++/4.9/bits/stl_vector.h:185
    #5 0x620b24 in std::_Vector_base<unsigned long, std::allocator<unsigned long> >::_Vector_base(unsigned long, std::allocator<unsigned long> const&) /usr/include/c++/4.9/bits/stl_vector.h:136
    #6 0xc06e13 in std::vector<unsigned long, std::allocator<unsigned long> >::vector(unsigned long, unsigned long const&, std::allocator<unsigned long> const&) /usr/include/c++/4.9/bits/stl_vector.h:291
    #7 0x7f031037b870 in Mantid::API::MatrixWorkspace::getSpectrumToWorkspaceIndexVector(int&) const /home/simon/code/mantid/Framework/API/src/MatrixWorkspace.cpp:408
    #8 0x7f030ef237b7 in Mantid::DataHandling::EventWorkspaceCollection::getSpectrumToWorkspaceIndexVector(int&) const /home/simon/code/mantid/Framework/DataHandling/src/EventWorkspaceCollection.cpp:205
    #9 0x7f030f11e8ea in Mantid::DataHandling::LoadEventNexus::createWorkspaceIndexMaps(bool, std::vector<std::string, std::allocator<std::string> > const&) /home/simon/code/mantid/Framework/DataHandling/src/LoadEventNexus.cpp:1116
    #10 0x7f030f121112 in Mantid::DataHandling::LoadEventNexus::loadEvents(Mantid::API::Progress*, bool) /home/simon/code/mantid/Framework/DataHandling/src/LoadEventNexus.cpp:1476
    #11 0x7f030f11d9ac in Mantid::DataHandling::LoadEventNexus::exec() /home/simon/code/mantid/Framework/DataHandling/src/LoadEventNexus.cpp:958
    #12 0x7f03101a6f56 in Mantid::API::Algorithm::execute() /home/simon/code/mantid/Framework/API/src/Algorithm.cpp:563
    #13 0xa3fd85 in LoadEventNexusTestPerformance::testDefaultLoadBankSplitting() /home/simon/code/mantid/Framework/DataHandling/test/LoadEventNexusTest.h:763
    #14 0xa419d3 in TestDescription_suite_LoadEventNexusTestPerformance_testDefaultLoadBankSplitting::runTest() /home/simon/build/mantid-debug/Framework/DataHandling/test/LoadEventNexusTest.cpp:152
    #15 0xbbf5b9 in CxxTest::RealTestDescription::run() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/RealDescriptions.cpp:96
    #16 0xbc558e in CxxTest::TestRunner::runTest(CxxTest::TestDescription&) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:94
    #17 0xbc51af in CxxTest::TestRunner::runSuite(CxxTest::SuiteDescription&) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:79
    #18 0xbc4d7f in CxxTest::TestRunner::runWorld() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:63
    #19 0xbc49ca in CxxTest::TestRunner::runAllTests(CxxTest::TestListener&) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:24
    #20 0xbd2703 in CxxTest::XUnitPrinter::run() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/XUnitPrinter.h:30
    #21 0xbd41f7 in int CxxTest::Main<CxxTest::XUnitPrinter>(CxxTest::XUnitPrinter&, int, char**) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestMain.h:106
    #22 0xbbd8d1 in main /home/simon/build/mantid-debug/Framework/DataHandling/test/DataHandlingTest_runner.cpp:27
    #23 0x7f0309fb7a3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20a3f)

Thread T25 created by T0 here:
    #0 0x7f03108cde0a in __interceptor_pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x23e0a)
    #1 0x7f030bb1b4f7 in Poco::ThreadImpl::startImpl(Poco::Runnable&) (/usr/lib/libPocoFoundationd.so.11+0x1724f7)
    #2 0x7f030bb1c9e6 in Poco::Thread::start(Poco::Runnable&) (/usr/lib/libPocoFoundationd.so.11+0x1739e6)
    #3 0x7f030c89e19b in Mantid::Kernel::ThreadPool::start(double) /home/simon/code/mantid/Framework/Kernel/src/ThreadPool.cpp:101
    #4 0x7f030c89e7ac in Mantid::Kernel::ThreadPool::joinAll() /home/simon/code/mantid/Framework/Kernel/src/ThreadPool.cpp:152
    #5 0x7f030f12233a in Mantid::DataHandling::LoadEventNexus::loadEvents(Mantid::API::Progress*, bool) /home/simon/code/mantid/Framework/DataHandling/src/LoadEventNexus.cpp:1587
    #6 0x7f030f11d9ac in Mantid::DataHandling::LoadEventNexus::exec() /home/simon/code/mantid/Framework/DataHandling/src/LoadEventNexus.cpp:958
    #7 0x7f03101a6f56 in Mantid::API::Algorithm::execute() /home/simon/code/mantid/Framework/API/src/Algorithm.cpp:563
    #8 0xa3fd85 in LoadEventNexusTestPerformance::testDefaultLoadBankSplitting() /home/simon/code/mantid/Framework/DataHandling/test/LoadEventNexusTest.h:763
    #9 0xa419d3 in TestDescription_suite_LoadEventNexusTestPerformance_testDefaultLoadBankSplitting::runTest() /home/simon/build/mantid-debug/Framework/DataHandling/test/LoadEventNexusTest.cpp:152
    #10 0xbbf5b9 in CxxTest::RealTestDescription::run() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/RealDescriptions.cpp:96
    #11 0xbc558e in CxxTest::TestRunner::runTest(CxxTest::TestDescription&) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:94
    #12 0xbc51af in CxxTest::TestRunner::runSuite(CxxTest::SuiteDescription&) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:79
    #13 0xbc4d7f in CxxTest::TestRunner::runWorld() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:63
    #14 0xbc49ca in CxxTest::TestRunner::runAllTests(CxxTest::TestListener&) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:24
    #15 0xbd2703 in CxxTest::XUnitPrinter::run() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/XUnitPrinter.h:30
    #16 0xbd41f7 in int CxxTest::Main<CxxTest::XUnitPrinter>(CxxTest::XUnitPrinter&, int, char**) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestMain.h:106
    #17 0xbbd8d1 in main /home/simon/build/mantid-debug/Framework/DataHandling/test/DataHandlingTest_runner.cpp:27
    #18 0x7f0309fb7a3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20a3f)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/simon/code/mantid/Framework/DataHandling/src/ProcessBankData.cpp:61 Mantid::DataHandling::ProcessBankData::run()
Shadow bytes around the buggy address:
  0x0c4680015bc0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4680015bd0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4680015be0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4680015bf0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4680015c00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c4680015c10: fa fa fa fa fa fa fa fa fa fa fa fa[fa]fa fa fa
  0x0c4680015c20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4680015c30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4680015c40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4680015c50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4680015c60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Contiguous container OOB:fc
  ASan internal:           fe
```

**Comment by martyngigg** [comment]
The address sanitizer no longer reports this as an issue with the latest version of the code.
