### ISSUE TITLE
Algorithms::NormaliseByDetector: AddressSanitizer: heap-buffer-overflow

### ISSUE THREAD

**Issue by SimonHeybrock** [mantidproject/mantid#17443]
From a run of units tests with Address Sanitizer (compiled with `-DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=-fsanitize=address`):

```
1069/1683 Test #1069: AlgorithmsTest_NormaliseByDetectorTestPerformance ............***Failed    2.98 sec
Running 2 testsFrameworkManager-[Notice] Welcome to Mantid 3.7.20160907.1229
FrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid
Load-[Notice] Load started
Load-[Notice] Load successful, Duration 1.03 seconds
ConvertUnits-[Notice] ConvertUnits started
ConvertUnits-[Notice] ConvertUnits started
ConvertUnits-[Notice] ConvertUnits successful, Duration 0.02 seconds
ConvertUnits-[Notice] ConvertUnits started
ConvertUnits-[Notice] ConvertUnits successful, Duration 0.02 seconds
ConvertUnits-[Notice] ConvertUnits successful, Duration 0.04 seconds. Processed as a workspace group
ConvertSpectrumAxis-[Notice] ConvertSpectrumAxis started
ConvertSpectrumAxis-[Notice] ConvertSpectrumAxis started
ConvertSpectrumAxis-[Warning] The instrument definition is incomplete - spectra dropped from output
ConvertSpectrumAxis-[Notice] ConvertSpectrumAxis successful, Duration 0.01 seconds
ConvertSpectrumAxis-[Notice] ConvertSpectrumAxis started
ConvertSpectrumAxis-[Warning] The instrument definition is incomplete - spectra dropped from output
ConvertSpectrumAxis-[Notice] ConvertSpectrumAxis successful, Duration 0.01 seconds
ConvertSpectrumAxis-[Notice] ConvertSpectrumAxis successful, Duration 0.02 seconds. Processed as a workspace group
LoadParameterFile-[Notice] LoadParameterFile started
=================================================================
==133619==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60e00011d5d8 at pc 0x7f24e2f08a65 bp 0x7ffe20be82a0 sp 0x7ffe20be8290
READ of size 8 at 0x60e00011d5d8 thread T0
    #0 0x7f24e2f08a64 in Mantid::Kernel::TimeValueUnit<double>::value() const /home/simon/code/mantid/Framework/Kernel/inc/MantidKernel/TimeSeriesProperty.h:79
    #1 0x7f24e2eda307 in Mantid::Kernel::TimeSeriesProperty<double>::nthValue(int) const /home/simon/code/mantid/Framework/Kernel/src/TimeSeriesProperty.cpp:1530
    #2 0x7f24e2e8b007 in Mantid::Kernel::filterByStatistic(Mantid::Kernel::TimeSeriesProperty<double> const*, Mantid::Kernel::Math::StatisticType) /home/simon/code/mantid/Framework/Kernel/src/TimeSeriesProperty.cpp:2183
    #3 0x7f24e3c1f0ab in Mantid::Geometry::XMLInstrumentParameter::createParamValue(Mantid::Kernel::TimeSeriesProperty<double>*) const /home/simon/code/mantid/Framework/Geometry/src/Instrument/XMLInstrumentParameter.cpp:139
    #4 0x7f24e6851c0a in operator double /home/simon/code/mantid/Framework/API/src/ExperimentInfo.cpp:224
    #5 0x7f24e685ac55 in Mantid::API::ExperimentInfo::populateWithParameter(Mantid::Geometry::ParameterMap&, std::string const&, Mantid::Geometry::XMLInstrumentParameter const&, Mantid::API::Run const&) /home/simon/code/mantid/Framework/API/src/ExperimentInfo.cpp:1219
    #6 0x7f24e68527f3 in Mantid::API::ExperimentInfo::populateInstrumentParameters() /home/simon/code/mantid/Framework/API/src/ExperimentInfo.cpp:303
    #7 0x7f24e69633e3 in Mantid::API::MatrixWorkspace::populateInstrumentParameters() /home/simon/code/mantid/Framework/API/src/MatrixWorkspace.cpp:842
    #8 0x7f24e592f814 in Mantid::DataHandling::LoadParameterFile::exec() /home/simon/code/mantid/Framework/DataHandling/src/LoadParameterFile.cpp:149
    #9 0x7f24e678af56 in Mantid::API::Algorithm::execute() /home/simon/code/mantid/Framework/API/src/Algorithm.cpp:563
    #10 0x8a25dd in apply_instrument_parameter_file_to_workspace(boost::shared_ptr<Mantid::API::MatrixWorkspace>, ScopedFileHelper::ScopedFile const&) /home/simon/code/mantid/Framework/Algorithms/test/NormaliseByDetectorTest.h:39
    #11 0x8b1dd5 in NormaliseByDetectorTestPerformance::setUp() /home/simon/code/mantid/Framework/Algorithms/test/NormaliseByDetectorTest.h:644
    #12 0xfa1d37 in CxxTest::RealTestDescription::setUp() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/RealDescriptions.cpp:53
    #13 0xfa811a in CxxTest::TestRunner::runTest(CxxTest::TestDescription&) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:91
    #14 0xfa7e03 in CxxTest::TestRunner::runSuite(CxxTest::SuiteDescription&) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:79
    #15 0xfa79d3 in CxxTest::TestRunner::runWorld() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:63
    #16 0xfa761e in CxxTest::TestRunner::runAllTests(CxxTest::TestListener&) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:24
    #17 0xfb5357 in CxxTest::XUnitPrinter::run() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/XUnitPrinter.h:30
    #18 0xfb6d8b in int CxxTest::Main<CxxTest::XUnitPrinter>(CxxTest::XUnitPrinter&, int, char**) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestMain.h:106
    #19 0xfa0525 in main /home/simon/build/mantid-debug/Framework/Algorithms/test/AlgorithmsTest_runner.cpp:27
    #20 0x7f24e119ba3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20a3f)
    #21 0x4bb488 in _start (/home/simon/build/mantid-debug/bin/AlgorithmsTest+0x4bb488)

0x60e00011d5d8 is located 24 bytes to the right of 160-byte region [0x60e00011d520,0x60e00011d5c0)
allocated by thread T0 here:
    #0 0x7f24e8bbe1af in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x581af)
    #1 0x7f24e2cad7ce in __gnu_cxx::new_allocator<Mantid::Kernel::TimeValueUnit<double> >::allocate(unsigned long, void const*) /usr/include/c++/4.9/ext/new_allocator.h:104
    #2 0x7f24e2cace3a in std::allocator_traits<std::allocator<Mantid::Kernel::TimeValueUnit<double> > >::allocate(std::allocator<Mantid::Kernel::TimeValueUnit<double> >&, unsigned long) /usr/include/c++/4.9/bits/alloc_traits.h:357
    #3 0x7f24e2caba25 in std::_Vector_base<Mantid::Kernel::TimeValueUnit<double>, std::allocator<Mantid::Kernel::TimeValueUnit<double> > >::_M_allocate(unsigned long) /usr/include/c++/4.9/bits/stl_vector.h:170
    #4 0x7f24e2caa7ca in std::_Vector_base<Mantid::Kernel::TimeValueUnit<double>, std::allocator<Mantid::Kernel::TimeValueUnit<double> > >::_M_create_storage(unsigned long) /usr/include/c++/4.9/bits/stl_vector.h:185
    #5 0x7f24e2ca8a8a in std::_Vector_base<Mantid::Kernel::TimeValueUnit<double>, std::allocator<Mantid::Kernel::TimeValueUnit<double> > >::_Vector_base(unsigned long, std::allocator<Mantid::Kernel::TimeValueUnit<double> > const&) /usr/include/c++/4.9/bits/stl_vector.h:136
    #6 0x7f24e2ca6dd5 in std::vector<Mantid::Kernel::TimeValueUnit<double>, std::allocator<Mantid::Kernel::TimeValueUnit<double> > >::vector(std::vector<Mantid::Kernel::TimeValueUnit<double>, std::allocator<Mantid::Kernel::TimeValueUnit<double> > > const&) /usr/include/c++/4.9/bits/stl_vector.h:320
    #7 0x7f24e2ca58ad in Mantid::Kernel::TimeSeriesProperty<double>::TimeSeriesProperty(Mantid::Kernel::TimeSeriesProperty<double> const&) /home/simon/code/mantid/Framework/Kernel/inc/MantidKernel/TimeSeriesProperty.h:112
    #8 0x7f24e2ca3e8c in Mantid::Kernel::FilteredTimeSeriesProperty<double>::FilteredTimeSeriesProperty(Mantid::Kernel::TimeSeriesProperty<double>*, Mantid::Kernel::TimeSeriesProperty<bool> const&, bool) /home/simon/code/mantid/Framework/Kernel/src/FilteredTimeSeriesProperty.cpp:20
    #9 0x7f24e2dc01a8 in std::_MakeUniq<Mantid::Kernel::FilteredTimeSeriesProperty<double> >::__single_object std::make_unique<Mantid::Kernel::FilteredTimeSeriesProperty<double>, Mantid::Kernel::TimeSeriesProperty<double>*&, Mantid::Kernel::TimeSeriesProperty<bool> const&, bool const&>(Mantid::Kernel::TimeSeriesProperty<double>*&, Mantid::Kernel::TimeSeriesProperty<bool> const&, bool const&) /usr/include/c++/4.9/bits/unique_ptr.h:765
    #10 0x7f24e2dbaf44 in Mantid::Kernel::PropertyManager::filterByProperty(Mantid::Kernel::TimeSeriesProperty<bool> const&) /home/simon/code/mantid/Framework/Kernel/src/PropertyManager.cpp:167
    #11 0x7f24e6941c9a in Mantid::API::LogManager::filterByLog(Mantid::Kernel::TimeSeriesProperty<bool> const&) /home/simon/code/mantid/Framework/API/src/LogManager.cpp:230
    #12 0x7f24e55e5058 in Mantid::DataHandling::ISISRunLogs::addPeriodLogs(int, Mantid::API::Run&) /home/simon/code/mantid/Framework/DataHandling/src/ISISRunLogs.cpp:75
    #13 0x7f24e5811f7b in Mantid::DataHandling::LoadISISNexus2::createPeriodLogs(long, boost::shared_ptr<Mantid::DataObjects::Workspace2D>&) /home/simon/code/mantid/Framework/DataHandling/src/LoadISISNexus2.cpp:861
    #14 0x7f24e580ba71 in Mantid::DataHandling::LoadISISNexus2::exec() /home/simon/code/mantid/Framework/DataHandling/src/LoadISISNexus2.cpp:305
    #15 0x7f24e678af56 in Mantid::API::Algorithm::execute() /home/simon/code/mantid/Framework/API/src/Algorithm.cpp:563
    #16 0x7f24e5601f54 in Mantid::DataHandling::Load::loadSingleFile() /home/simon/code/mantid/Framework/DataHandling/src/Load.cpp:371
    #17 0x7f24e5601238 in Mantid::DataHandling::Load::exec() /home/simon/code/mantid/Framework/DataHandling/src/Load.cpp:337
    #18 0x7f24e678af56 in Mantid::API::Algorithm::execute() /home/simon/code/mantid/Framework/API/src/Algorithm.cpp:563
    #19 0x7f24e67de69c in Mantid::API::AlgorithmProxy::execute() /home/simon/code/mantid/Framework/API/src/AlgorithmProxy.cpp:71
    #20 0x8b0d42 in NormaliseByDetectorTestPerformance::setUp() /home/simon/code/mantid/Framework/Algorithms/test/NormaliseByDetectorTest.h:594
    #21 0xfa1d37 in CxxTest::RealTestDescription::setUp() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/RealDescriptions.cpp:53
    #22 0xfa811a in CxxTest::TestRunner::runTest(CxxTest::TestDescription&) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:91
    #23 0xfa7e03 in CxxTest::TestRunner::runSuite(CxxTest::SuiteDescription&) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:79
    #24 0xfa79d3 in CxxTest::TestRunner::runWorld() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:63
    #25 0xfa761e in CxxTest::TestRunner::runAllTests(CxxTest::TestListener&) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:24
    #26 0xfb5357 in CxxTest::XUnitPrinter::run() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/XUnitPrinter.h:30
    #27 0xfb6d8b in int CxxTest::Main<CxxTest::XUnitPrinter>(CxxTest::XUnitPrinter&, int, char**) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestMain.h:106
    #28 0xfa0525 in main /home/simon/build/mantid-debug/Framework/Algorithms/test/AlgorithmsTest_runner.cpp:27
    #29 0x7f24e119ba3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20a3f)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/simon/code/mantid/Framework/Kernel/inc/MantidKernel/TimeSeriesProperty.h:79 Mantid::Kernel::TimeValueUnit<double>::value() const
Shadow bytes around the buggy address:
  0x0c1c8001ba60: 00 00 00 00 fa fa fa fa fa fa fa fa 00 00 00 00
  0x0c1c8001ba70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c1c8001ba80: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c1c8001ba90: 00 00 00 00 00 00 00 00 00 00 00 00 fa fa fa fa
  0x0c1c8001baa0: fa fa fa fa 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c1c8001bab0: 00 00 00 00 00 00 00 00 fa fa fa[fa]fa fa fa fa
  0x0c1c8001bac0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c1c8001bad0: 00 00 00 00 fa fa fa fa fa fa fa fa 00 00 00 00
  0x0c1c8001bae0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c1c8001baf0: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c1c8001bb00: 00 00 00 00 00 00 00 00 00 00 00 00 fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Contiguous container OOB:fc
  ASan internal:           fe
```

**Comment by DavidFair** [comment]
Closing as obsolete, if this or any other memory issues still exist they will be picked up by the sanitizers
