### ISSUE TITLE
SCDCalibratePanelsTest segfaults sporadically on master.

### ISSUE THREAD

**Issue by SimonHeybrock** [mantidproject/mantid#18390]
On my system (Ubuntu 16.04, gcc) `SCDCalibratePanelsTest` sporadically segfaults for the current master branch. Backtraces indicates that this could be related to recent changes for Instrument-2.0, but I could not reproduce it systematically enough so far.

**Comment by SimonHeybrock** [comment]
Example backtrace (not that segfaults occur at different places, not always the same!):

```
Running 1 testLoadIsawPeaks-[Notice] LoadIsawPeaks started
LoadIsawPeaks-[Notice] LoadIsawPeaks successful, Duration 4.21 seconds
SCDCalibratePanels-[Notice] SCDCalibratePanels started
IndexPeaks-[Notice] ALL Runs: indexed 425 Peaks out of 434 with tolerance of 0.15
IndexPeaks-[Notice] Average error in h,k,l for indexed peaks =  0.0277364
IndexPeaks-[Notice] Lattice Parameters:    4.750000    4.750000   13.000000   90.000000   90.000000  120.000000   254.016076
SCDCalibratePanels-[Notice] Matrix(3,3)0.204131,0.18081,0.0302817,0.131664,-0.0446408,-0.0505176,-0.00949735,0.156237,-0.0494787
SCDCalibratePanels-[Notice] L1 = 17.9894  success Chi2overDoF 267.787
[New Thread 0x7fffe306f700 (LWP 133305)]
[New Thread 0x7fffe286e700 (LWP 133306)]
[New Thread 0x7fffe206d700 (LWP 133307)]
[New Thread 0x7fffdf46b700 (LWP 133308)]
[New Thread 0x7fffdec6a700 (LWP 133312)]
[New Thread 0x7fffde469700 (LWP 133313)]
[New Thread 0x7fffddc68700 (LWP 133316)]
[New Thread 0x7fffdd467700 (LWP 133317)]
[New Thread 0x7fffdcc66700 (LWP 133318)]
[New Thread 0x7fffdc465700 (LWP 133319)]
[New Thread 0x7fffdbc64700 (LWP 133320)]
[New Thread 0x7fffdb463700 (LWP 133322)]
[New Thread 0x7fffdac62700 (LWP 133323)]
[New Thread 0x7fffda461700 (LWP 133325)]
[New Thread 0x7fffd9c60700 (LWP 133326)]
[New Thread 0x7fffd945f700 (LWP 133327)]
[New Thread 0x7fffd8c5e700 (LWP 133328)]
[New Thread 0x7fffd845d700 (LWP 133329)]
[New Thread 0x7fffd7c5c700 (LWP 133330)]
[New Thread 0x7fffd745b700 (LWP 133331)]
[New Thread 0x7fffd6c5a700 (LWP 133332)]
[New Thread 0x7fffd6459700 (LWP 133333)]
[New Thread 0x7fffd5c58700 (LWP 133334)]

Thread 6 "CrystalTest" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffdec6a700 (LWP 133312)]
0x00007fffc0046670 in ?? ()
(gdb) bt
#0  0x00007fffc0046670 in ?? ()
#1  0x00007ffff536a658 in boost::detail::sp_counted_base::release (this=0x7fffc0001400) at /usr/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp:146
#2  0x00007ffff536a6d5 in boost::detail::shared_count::~shared_count (this=0x7fffc003be38, __in_chrg=<optimized out>) at /usr/include/boost/smart_ptr/detail/shared_count.hpp:443
#3  0x00007ffff5453a86 in boost::shared_ptr<Mantid::Beamline::DetectorInfo const>::~shared_ptr (this=0x7fffc003be30, __in_chrg=<optimized out>) at /usr/include/boost/smart_ptr/shared_ptr.hpp:323
#4  0x00007ffff544a49a in Mantid::Geometry::Instrument::~Instrument (this=0x7fffc003bc30, __in_chrg=<optimized out>, __vtt_parm=<optimized out>) at /home/simon/code/mantid/Framework/Geometry/src/Instrument.cpp:114
#5  0x00007ffff547a45a in boost::detail::sp_ms_deleter<Mantid::Geometry::Instrument>::destroy (this=0x7fffc003bc28) at /usr/include/boost/smart_ptr/make_shared_object.hpp:57
#6  0x00007ffff547a6c4 in boost::detail::sp_ms_deleter<Mantid::Geometry::Instrument>::operator() (this=0x7fffc003bc28) at /usr/include/boost/smart_ptr/make_shared_object.hpp:91
#7  0x00007ffff547a63b in boost::detail::sp_counted_impl_pd<Mantid::Geometry::Instrument*, boost::detail::sp_ms_deleter<Mantid::Geometry::Instrument> >::dispose (this=0x7fffc003bc10) at /usr/include/boost/smart_ptr/detail/sp_counted_impl.hpp:153
#8  0x00007ffff79279d8 in boost::detail::sp_counted_base::release (this=0x7fffc003bc10) at /usr/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp:146
#9  0x00007ffff7927a6b in boost::detail::shared_count::~shared_count (this=0x7fffdec678e8, __in_chrg=<optimized out>) at /usr/include/boost/smart_ptr/detail/shared_count.hpp:443
#10 0x00007ffff79394a6 in boost::shared_ptr<Mantid::Geometry::Instrument const>::~shared_ptr (this=0x7fffdec678e0, __in_chrg=<optimized out>) at /usr/include/boost/smart_ptr/shared_ptr.hpp:323
#11 0x00007ffff7a6c23d in Mantid::Crystal::SCDPanelErrors::eval (this=0x7fffc00377d0, xshift=0, yshift=0, zshift=0, xrotate=0, yrotate=0, zrotate=0, scalex=1, scaley=1, out=0x7fffc0048250, xValues=0x7fffc003a6b0, nData=186) at /home/simon/code/mantid/Framework/Crystal/src/SCDPanelErrors.cpp:168
#12 0x00007ffff7a6c781 in Mantid::Crystal::SCDPanelErrors::function1D (this=0x7fffc00377d0, out=0x7fffc0048250, xValues=0x7fffc003a6b0, nData=186) at /home/simon/code/mantid/Framework/Crystal/src/SCDPanelErrors.cpp:211
#13 0x00007ffff738908a in Mantid::API::IFunction1D::function (this=0x7fffc00378b8, domain=..., values=...) at /home/simon/code/mantid/Framework/API/src/IFunction1D.cpp:47
#14 0x00007ffff737a633 in Mantid::API::IFunction::calNumericalDeriv (this=0x7fffc00378f8, domain=..., jacobian=...) at /home/simon/code/mantid/Framework/API/src/IFunction.cpp:675
#15 0x00007ffff7a6c991 in Mantid::Crystal::SCDPanelErrors::functionDeriv1D (this=0x7fffc00377d0, out=0x7fffc00350b8, xValues=0x7fffc003a6b0, nData=186) at /home/simon/code/mantid/Framework/Crystal/src/SCDPanelErrors.cpp:224
#16 0x00007ffff7389227 in Mantid::API::IFunction1D::functionDeriv (this=0x7fffc00378b8, domain=..., jacobian=...) at /home/simon/code/mantid/Framework/API/src/IFunction1D.cpp:62
#17 0x00007fffe40ce02b in Mantid::CurveFitting::gsl_df (x=0x7fffc00377a0, params=0x7fffc0035080, J=0x7fffc0036270) at /home/simon/code/mantid/Framework/CurveFitting/src/GSLFunctions.cpp:100
#18 0x00007ffff2cfb514 in gsl_multifit_eval_wdf () from /usr/lib/x86_64-linux-gnu/libgsl.so.19
#19 0x00007ffff2cfa817 in ?? () from /usr/lib/x86_64-linux-gnu/libgsl.so.19
#20 0x00007ffff2cfaa2b in ?? () from /usr/lib/x86_64-linux-gnu/libgsl.so.19
#21 0x00007fffe3fd4679 in Mantid::CurveFitting::FuncMinimisers::LevenbergMarquardtMinimizer::initialize (this=0x7fffc0038560, costFunction=...) at /home/simon/code/mantid/Framework/CurveFitting/src/FuncMinimizers/LevenbergMarquardtMinimizer.cpp:74
#22 0x00007fffe3eac2d2 in Mantid::CurveFitting::Algorithms::Fit::execConcrete (this=0x7fffc0032830) at /home/simon/code/mantid/Framework/CurveFitting/src/Algorithms/Fit.cpp:141
#23 0x00007fffe40db97a in Mantid::CurveFitting::IFittingAlgorithm::exec (this=0x7fffc0032830) at /home/simon/code/mantid/Framework/CurveFitting/src/IFittingAlgorithm.cpp:346
#24 0x00007ffff729ac50 in Mantid::API::Algorithm::execute (this=0x7fffc0032830) at /home/simon/code/mantid/Framework/API/src/Algorithm.cpp:548
#25 0x00007ffff729bf93 in Mantid::API::Algorithm::executeAsChildAlg (this=0x7fffc0032830) at /home/simon/code/mantid/Framework/API/src/Algorithm.cpp:650
#26 0x00007ffff7a5d4f3 in Mantid::Crystal::SCDCalibratePanels::exec () at /home/simon/code/mantid/Framework/Crystal/src/SCDCalibratePanels.cpp:239
#27 0x00007ffff29fe43e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#28 0x00007ffff34206ba in start_thread (arg=0x7fffdec6a700) at pthread_create.c:333
#29 0x00007ffff315682d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```
