### ISSUE TITLE
Instrument view overlay command crashes Mantid with wrong TOF range

### ISSUE THREAD

**Issue by samueljackson92** [mantidproject/mantid#19084]
### Expected behavior
Using the `overlay` command on the instrument view with a peaks workspace that has TOF values outside that of the the data.

### Actual behavior
Using the command with values outside the TOF range causes Mantid to crash

### Steps to reproduce the behavior
Run this script:

```python
ws = CreateSimulationWorkspace(Instrument='WISH',
                               BinParams='0,10000,20000',
                               UnitX='TOF')

SetUB(ws, a=5.5, b=6.5, c=8.1, u='12,1,1', v='0,4,9')

cs = CrystalStructure('5.5 6.5 8.1', 'P b c a',
                      """Ni 0.232 0.114 0.543 1.0 0.00843;
                         Al 0.434 0.041 0.854 1.0 0.01120""")
ws.sample().setCrystalStructure(cs)

predicted = PredictPeaks(InputWorkspace=ws,
                         CalculateStructureFactors=True,
                         MinDSpacing=0.5,
                         WavelengthMin=2.0, WavelengthMax=2.2)
                         
iView = getInstrumentView('ws')
iView.overlay('predicted')
iView.show()
```

### Platforms affected
Ubuntu 14.04

### Stack trace

```
#0  0x00007ffff001ccc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff00200d8 in __GI_abort () at abort.c:89
#2  0x00007ffff0015b86 in __assert_fail_base (fmt=0x7ffff0166830 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7ffff682073c "px != 0", file=file@entry=0x7ffff6820710 "/usr/include/boost/smart_ptr/shared_ptr.hpp", line=line@entry=653, function=function@entry=0x7ffff6820f00 <boost::shared_ptr<MantidQt::MantidWidgets::UnwrappedSurface>::operator->() const::__PRETTY_FUNCTION__> "typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = MantidQt::MantidWidgets::UnwrappedSurface; typename boost::detail::sp_member_access<T>::type = Mant"...) at assert.c:92
#3  0x00007ffff0015c32 in __GI___assert_fail (assertion=0x7ffff682073c "px != 0", file=0x7ffff6820710 "/usr/include/boost/smart_ptr/shared_ptr.hpp", line=653, function=0x7ffff6820f00 <boost::shared_ptr<MantidQt::MantidWidgets::UnwrappedSurface>::operator->() const::__PRETTY_FUNCTION__> "typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = MantidQt::MantidWidgets::UnwrappedSurface; typename boost::detail::sp_member_access<T>::type = Mant"...) at assert.c:101
#4  0x00007ffff66b3a01 in boost::shared_ptr<MantidQt::MantidWidgets::UnwrappedSurface>::operator-> (this=0x7fffffffb5d0) at /usr/include/boost/smart_ptr/shared_ptr.hpp:653
#5  0x00007ffff66b14cf in MantidQt::MantidWidgets::InstrumentWidget::overlayPeaksWorkspace (this=0x376dc00, ws=...) at /home/cs/soininen/Sources/mantid/MantidQt/MantidWidgets/src/InstrumentView/InstrumentWidget.cpp:1305
#6  0x00007ffff66afe33 in MantidQt::MantidWidgets::InstrumentWidget::overlay (this=0x376dc00, wsName=...) at /home/cs/soininen/Sources/mantid/MantidQt/MantidWidgets/src/InstrumentView/InstrumentWidget.cpp:973
#7  0x00007ffff66af76c in MantidQt::MantidWidgets::InstrumentWidget::dropEvent (this=0x376dc00, e=0x7fffffffbba0) at /home/cs/soininen/Sources/mantid/MantidQt/MantidWidgets/src/InstrumentView/InstrumentWidget.cpp:900
#8  0x00007ffff3d8326a in QWidget::event (this=0x376dc00, event=0x7fffffffbba0) at kernel/qwidget.cpp:8577
#9  0x00007ffff3d33e2c in QApplicationPrivate::notify_helper (this=this@entry=0x123b240, receiver=receiver@entry=0x376dc00, e=e@entry=0x7fffffffbba0) at kernel/qapplication.cpp:4567
#10 0x00007ffff3d3b326 in QApplication::notify (this=<optimized out>, receiver=<optimized out>, e=0x7fffffffbba0) at kernel/qapplication.cpp:4353
#11 0x000000000080d666 in MantidApplication::notify (this=0x7fffffffdc40, receiver=0x376dc00, event=0x7fffffffbba0) at /home/cs/soininen/Sources/mantid/MantidPlot/src/Mantid/MantidApplication.cpp:37
#12 0x00007ffff35bd4dd in QCoreApplication::notifyInternal (this=0x7fffffffdc40, receiver=0x376dc00, event=event@entry=0x7fffffffbba0) at kernel/qcoreapplication.cpp:953
#13 0x00007ffff3dbc7b1 in sendEvent (event=0x7fffffffbba0, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:231
#14 QX11Data::xdndHandleDrop (this=<optimized out>, xe=xe@entry=0x7fffffffbcc0, passive=passive@entry=false) at kernel/qdnd_x11.cpp:1185
#15 0x00007ffff3dbcb45 in QDragManager::drop (this=this@entry=0x38629e0) at kernel/qdnd_x11.cpp:1765
#16 0x00007ffff3dbdd90 in QDragManager::eventFilter (this=0x38629e0, o=<optimized out>, e=<optimized out>) at kernel/qdnd_x11.cpp:1314
#17 0x00007ffff35bd5b2 in QCoreApplicationPrivate::sendThroughApplicationEventFilters (this=this@entry=0x123b240, receiver=receiver@entry=0xa200200, event=event@entry=0x7fffffffc230) at kernel/qcoreapplication.cpp:1044
#18 0x00007ffff3d33db8 in QApplicationPrivate::notify_helper (this=this@entry=0x123b240, receiver=receiver@entry=0xa200200, e=e@entry=0x7fffffffc230) at kernel/qapplication.cpp:4542
#19 0x00007ffff3d3a5dd in QApplication::notify (this=<optimized out>, receiver=0xa200200, e=0x7fffffffc230) at kernel/qapplication.cpp:4110
#20 0x000000000080d666 in MantidApplication::notify (this=0x7fffffffdc40, receiver=0xa200200, event=0x7fffffffc230) at /home/cs/soininen/Sources/mantid/MantidPlot/src/Mantid/MantidApplication.cpp:37
#21 0x00007ffff35bd4dd in QCoreApplication::notifyInternal (this=0x7fffffffdc40, receiver=receiver@entry=0xa200200, event=event@entry=0x7fffffffc230) at kernel/qcoreapplication.cpp:953
#22 0x00007ffff3d39d93 in sendEvent (event=<optimized out>, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:231
#23 QApplicationPrivate::sendMouseEvent (receiver=receiver@entry=0xa200200, event=event@entry=0x7fffffffc230, alienWidget=alienWidget@entry=0x0, nativeWidget=nativeWidget@entry=0xa200200, buttonDown=buttonDown@entry=0x7ffff4819318 <qt_button_down>, lastMouseReceiver=..., spontaneous=spontaneous@entry=true) at kernel/qapplication.cpp:3178
#24 0x00007ffff3dae9eb in QETWidget::translateMouseEvent (this=this@entry=0xa200200, event=event@entry=0x7fffffffc5b0) at kernel/qapplication_x11.cpp:4634
#25 0x00007ffff3dae289 in QApplication::x11ProcessEvent (this=0x7fffffffdc40, event=event@entry=0x7fffffffc5b0) at kernel/qapplication_x11.cpp:3627
#26 0x00007ffff3dd5b32 in x11EventSourceDispatch (s=0x123dda0, callback=0x0, user_data=0x0) at kernel/qguieventdispatcher_glib.cpp:146
#27 0x00007fffe7bd1e04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007fffe7bd2048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007fffe7bd20ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007ffff35ea7a1 in QEventDispatcherGlib::processEvents (this=0x123c740, flags=...) at kernel/qeventdispatcher_glib.cpp:434
#31 0x00007ffff3dd5be6 in QGuiEventDispatcherGlib::processEvents (this=<optimized out>, flags=...) at kernel/qguieventdispatcher_glib.cpp:204
#32 0x00007ffff35bc0af in QEventLoop::processEvents (this=this@entry=0x1814390, flags=...) at kernel/qeventloop.cpp:149
#33 0x00007ffff35bc3a5 in QEventLoop::exec (this=this@entry=0x1814390, flags=...) at kernel/qeventloop.cpp:204
#34 0x00007ffff3dbe0bd in QDragManager::drag (this=0x38629e0, o=o@entry=0x367d5d0) at kernel/qdnd_x11.cpp:2032
#35 0x00007ffff3d44e3a in QDrag::exec (this=0x367d5d0, supportedActions=..., defaultDropAction=defaultDropAction@entry=Qt::IgnoreAction) at kernel/qdrag.cpp:284
#36 0x00007ffff3d44ef3 in QDrag::exec (this=<optimized out>, supportedActions=...) at kernel/qdrag.cpp:239
#37 0x00007ffff673cf5a in MantidQt::MantidWidgets::MantidTreeWidget::mouseMoveEvent (this=0x16fead0, e=0x7fffffffd3c0) at /home/cs/soininen/Sources/mantid/MantidQt/MantidWidgets/src/MantidTreeWidget.cpp:139
#38 0x00007ffff3d83645 in QWidget::event (this=this@entry=0x16fead0, event=event@entry=0x7fffffffd3c0) at kernel/qwidget.cpp:8361
#39 0x00007ffff412504e in QFrame::event (this=0x16fead0, e=0x7fffffffd3c0) at widgets/qframe.cpp:557
#40 0x00007ffff4234633 in QAbstractItemView::viewportEvent (this=this@entry=0x16fead0, event=event@entry=0x7fffffffd3c0) at itemviews/qabstractitemview.cpp:1644
#41 0x00007ffff4273230 in QTreeView::viewportEvent (this=0x16fead0, event=0x7fffffffd3c0) at itemviews/qtreeview.cpp:1252
#42 0x00007ffff35bd646 in QCoreApplicationPrivate::sendThroughObjectEventFilters (this=this@entry=0x123b240, receiver=receiver@entry=0x1667520, event=event@entry=0x7fffffffd3c0) at kernel/qcoreapplication.cpp:1063
#43 0x00007ffff3d33e0c in QApplicationPrivate::notify_helper (this=this@entry=0x123b240, receiver=receiver@entry=0x1667520, e=e@entry=0x7fffffffd3c0) at kernel/qapplication.cpp:4563
#44 0x00007ffff3d3a5dd in QApplication::notify (this=<optimized out>, receiver=0x1667520, e=0x7fffffffd3c0) at kernel/qapplication.cpp:4110
#45 0x000000000080d666 in MantidApplication::notify (this=0x7fffffffdc40, receiver=0x1667520, event=0x7fffffffd3c0) at /home/cs/soininen/Sources/mantid/MantidPlot/src/Mantid/MantidApplication.cpp:37
#46 0x00007ffff35bd4dd in QCoreApplication::notifyInternal (this=0x7fffffffdc40, receiver=receiver@entry=0x1667520, event=event@entry=0x7fffffffd3c0) at kernel/qcoreapplication.cpp:953
#47 0x00007ffff3d39d93 in sendEvent (event=<optimized out>, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:231
#48 QApplicationPrivate::sendMouseEvent (receiver=receiver@entry=0x1667520, event=event@entry=0x7fffffffd3c0, alienWidget=alienWidget@entry=0x1667520, nativeWidget=nativeWidget@entry=0x16a9ea0, buttonDown=buttonDown@entry=0x7ffff4819318 <qt_button_down>, lastMouseReceiver=..., spontaneous=spontaneous@entry=true) at kernel/qapplication.cpp:3178
#49 0x00007ffff3dae9eb in QETWidget::translateMouseEvent (this=this@entry=0x16a9ea0, event=event@entry=0x7fffffffd740) at kernel/qapplication_x11.cpp:4634
#50 0x00007ffff3dae289 in QApplication::x11ProcessEvent (this=0x7fffffffdc40, event=event@entry=0x7fffffffd740) at kernel/qapplication_x11.cpp:3627
#51 0x00007ffff3dd5b32 in x11EventSourceDispatch (s=0x123dda0, callback=0x0, user_data=0x0) at kernel/qguieventdispatcher_glib.cpp:146
#52 0x00007fffe7bd1e04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#53 0x00007fffe7bd2048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#54 0x00007fffe7bd20ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#55 0x00007ffff35ea7a1 in QEventDispatcherGlib::processEvents (this=0x123c740, flags=...) at kernel/qeventdispatcher_glib.cpp:434
#56 0x00007ffff3dd5be6 in QGuiEventDispatcherGlib::processEvents (this=<optimized out>, flags=...) at kernel/qguieventdispatcher_glib.cpp:204
#57 0x00007ffff35bc0af in QEventLoop::processEvents (this=this@entry=0x7fffffffdb10, flags=...) at kernel/qeventloop.cpp:149
#58 0x00007ffff35bc3a5 in QEventLoop::exec (this=this@entry=0x7fffffffdb10, flags=...) at kernel/qeventloop.cpp:204
#59 0x00007ffff35c1b79 in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1225
#60 0x00000000008ca8d9 in main (argc=1, argv=0x7fffffffdde8) at /home/cs/soininen/Sources/mantid/MantidPlot/src/main.cpp:255
```

**Comment by samueljackson92** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hello](https://trello.com/c/FamFkOsI/96-hello)

**Comment by samueljackson92** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Testing](https://trello.com/c/HeQamhSG/97-testing)
