### ISSUE TITLE
VesuvioCorrectionsTest systemtest fails with boost 1.64

### ISSUE THREAD

**Issue by rosswhitfield** [mantidproject/mantid#19782]
In particular:
`VesuvioCorrectionsTest.TestGammaAndMsCorrectWorkspaceIndexOne` and `VesuvioCorrectionsTest.TestMsCorrectWithContainer`

I first observed this on Arch Linux [here](http://builds.mantidproject.org/job/master_clean-archlinux/887/console) but the failures were also reproduced on OSX with boost 1.64

[There is already boost version dependency in the unit test](https://github.com/mantidproject/mantid/blob/master/Testing/SystemTests/tests/analysis/VesuvioCommandsTest.py#L16-L27) so this is possible the same thing.

# Detailed output
VesuvioCorrectionsTest.TestGammaAndMsCorrectWorkspaceIndexOne:
```
Thu, 01 Jun 2017 12:35:13: Executing VesuvioCorrectionsTest.TestGammaAndMsCorrectWorkspaceIndexOne
Executing test script '/home/builder/jenkins-linode/workspace/master_clean-archlinux/build/bin/mantidpython --classic /tmp/tmpHCLGwE'
FrameworkManager-[Notice] Welcome to Mantid 3.9.20170601.828
FrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid
LoadVesuvio-[Notice] LoadVesuvio started
LogParser-[Warning] Cannot process ICPevent log. Period 1 assumed for all data.
LogParser-[Warning] Cannot process ICPevent log. Period 1 assumed for all data.
LogParser-[Warning] Cannot process ICPevent log. Period 1 assumed for all data.
LogParser-[Warning] Cannot process ICPevent log. Period 1 assumed for all data.
LogParser-[Warning] Cannot process ICPevent log. Period 1 assumed for all data.
LogParser-[Warning] Cannot process ICPevent log. Period 1 assumed for all data.
LogParser-[Warning] Cannot process ICPevent log. Period 1 assumed for all data.
LoadVesuvio-[Notice] LoadVesuvio successful, Duration 0.19 seconds
LoadVesuvio-[Notice] LoadVesuvio started
LogParser-[Warning] Cannot process ICPevent log. Period 1 assumed for all data.
LoadVesuvio-[Notice] LoadVesuvio successful, Duration 0.06 seconds
CreateEmptyTableWorkspace-[Notice] CreateEmptyTableWorkspace started
CreateEmptyTableWorkspace-[Notice] CreateEmptyTableWorkspace successful, Duration 0.00 seconds
ExtractSingleSpectrum-[Notice] ExtractSingleSpectrum started (child)
ExtractSingleSpectrum-[Notice] ExtractSingleSpectrum successful, Duration 0.00 seconds
VesuvioCalculateGammaBackground-[Notice] VesuvioCalculateGammaBackground started (child)
VesuvioCalculateGammaBackground-[Notice] VesuvioCalculateGammaBackground successful, Duration 8.05 seconds
DeleteWorkspace-[Notice] DeleteWorkspace started (child)
DeleteWorkspace-[Notice] DeleteWorkspace successful, Duration 0.00 seconds
CreateSampleShape-[Notice] CreateSampleShape started (child)
CreateSampleShape-[Notice] CreateSampleShape successful, Duration 0.00 seconds
VesuvioCalculateMS-[Notice] VesuvioCalculateMS started (child)
VesuvioCalculateMS-[Notice] VesuvioCalculateMS successful, Duration 7.15 seconds
SmoothData-[Notice] SmoothData started (child)
SmoothData-[Notice] SmoothData successful, Duration 0.00 seconds
SmoothData-[Notice] SmoothData started (child)
SmoothData-[Notice] SmoothData successful, Duration 0.00 seconds
GroupWorkspaces-[Notice] GroupWorkspaces started (child)
GroupWorkspaces-[Notice] GroupWorkspaces successful, Duration 0.00 seconds
Python-[Notice] Corrections scale fit index 0 is __Correction_GammaBackground
Python-[Notice] Corrections scale fit index 1 is __Correction_TotalScattering
Scale-[Notice] Scale started (child)
Scale-[Notice] Scale successful, Duration 0.00 seconds
Scale-[Notice] Scale started (child)
Scale-[Notice] Scale successful, Duration 0.00 seconds
Scale-[Notice] Scale started (child)
Scale-[Notice] Scale successful, Duration 0.00 seconds
Minus-[Notice] Minus started (child)
Minus-[Notice] Minus successful, Duration 0.00 seconds
Minus-[Notice] Minus started (child)
Minus-[Notice] Minus successful, Duration 0.00 seconds
Minus-[Notice] Minus started (child)
Minus-[Notice] Minus successful, Duration 0.00 seconds
GroupWorkspaces-[Notice] GroupWorkspaces started (child)
GroupWorkspaces-[Notice] GroupWorkspaces successful, Duration 0.00 seconds
Minus-[Notice] Minus started (child)
Minus-[Notice] Minus successful, Duration 0.00 seconds
Minus-[Notice] Minus started (child)
Minus-[Notice] Minus successful, Duration 0.00 seconds
RESULT|iteration time_taken|1 15.48
Traceback (most recent call last):
  File "/tmp/tmpHCLGwE", line 7, in <module>
    exitcode = systest.returnValidationCode(99)
  File "/home/builder/jenkins-linode/workspace/master_clean-archlinux/Testing/SystemTests/lib/systemtests/stresstesting.py", line 362, in returnValidationCode
    if self.doValidation():
  File "/home/builder/jenkins-linode/workspace/master_clean-archlinux/Testing/SystemTests/lib/systemtests/stresstesting.py", line 332, in doValidation
    validation = self.validate()
  File "/home/builder/jenkins-linode/workspace/master_clean-archlinux/Testing/SystemTests/tests/analysis/VesuvioCorrectionsTest.py", line 163, in validate
    _validate_matrix_peak_height(self, corrections_wsg.getItem(2), corrections_ms_peak, corrections_ms_bin)
  File "/home/builder/jenkins-linode/workspace/master_clean-archlinux/Testing/SystemTests/tests/analysis/VesuvioCorrectionsTest.py", line 550, in _validate_matrix_peak_height
    self.assertTrue(abs(peak_bin - expected_bin) <= 1)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
```

VesuvioCorrectionsTest.TestMsCorrectWithContainer
```
Thu, 01 Jun 2017 12:35:58: Executing VesuvioCorrectionsTest.TestMsCorrectWithContainer
Executing test script '/home/builder/jenkins-linode/workspace/master_clean-archlinux/build/bin/mantidpython --classic /tmp/tmpupPpqA'
FrameworkManager-[Notice] Welcome to Mantid 3.9.20170601.828
FrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid
LoadVesuvio-[Notice] LoadVesuvio started
LogParser-[Warning] Cannot process ICPevent log. Period 1 assumed for all data.
LogParser-[Warning] Cannot process ICPevent log. Period 1 assumed for all data.
LogParser-[Warning] Cannot process ICPevent log. Period 1 assumed for all data.
LogParser-[Warning] Cannot process ICPevent log. Period 1 assumed for all data.
LogParser-[Warning] Cannot process ICPevent log. Period 1 assumed for all data.
LogParser-[Warning] Cannot process ICPevent log. Period 1 assumed for all data.
LogParser-[Warning] Cannot process ICPevent log. Period 1 assumed for all data.
LoadVesuvio-[Notice] LoadVesuvio successful, Duration 0.19 seconds
LoadVesuvio-[Notice] LoadVesuvio started
LogParser-[Warning] Cannot process ICPevent log. Period 1 assumed for all data.
LoadVesuvio-[Notice] LoadVesuvio successful, Duration 0.06 seconds
CreateEmptyTableWorkspace-[Notice] CreateEmptyTableWorkspace started
CreateEmptyTableWorkspace-[Notice] CreateEmptyTableWorkspace successful, Duration 0.00 seconds
ExtractSingleSpectrum-[Notice] ExtractSingleSpectrum started (child)
ExtractSingleSpectrum-[Notice] ExtractSingleSpectrum successful, Duration 0.00 seconds
ExtractSingleSpectrum-[Notice] ExtractSingleSpectrum started (child)
ExtractSingleSpectrum-[Notice] ExtractSingleSpectrum successful, Duration 0.00 seconds
CreateSampleShape-[Notice] CreateSampleShape started (child)
CreateSampleShape-[Notice] CreateSampleShape successful, Duration 0.00 seconds
VesuvioCalculateMS-[Notice] VesuvioCalculateMS started (child)
VesuvioCalculateMS-[Notice] VesuvioCalculateMS successful, Duration 7.21 seconds
SmoothData-[Notice] SmoothData started (child)
SmoothData-[Notice] SmoothData successful, Duration 0.00 seconds
SmoothData-[Notice] SmoothData started (child)
SmoothData-[Notice] SmoothData successful, Duration 0.00 seconds
GroupWorkspaces-[Notice] GroupWorkspaces started (child)
GroupWorkspaces-[Notice] GroupWorkspaces successful, Duration 0.00 seconds
Python-[Notice] Corrections scale fit index 0 is __Correction_Container
Python-[Notice] Corrections scale fit index 1 is __Correction_TotalScattering
Scale-[Notice] Scale started (child)
Scale-[Notice] Scale successful, Duration 0.00 seconds
Scale-[Notice] Scale started (child)
Scale-[Notice] Scale successful, Duration 0.00 seconds
Scale-[Notice] Scale started (child)
Scale-[Notice] Scale successful, Duration 0.00 seconds
Minus-[Notice] Minus started (child)
Minus-[Notice] Minus successful, Duration 0.00 seconds
Minus-[Notice] Minus started (child)
Minus-[Notice] Minus successful, Duration 0.00 seconds
Minus-[Notice] Minus started (child)
Minus-[Notice] Minus successful, Duration 0.00 seconds
GroupWorkspaces-[Notice] GroupWorkspaces started (child)
GroupWorkspaces-[Notice] GroupWorkspaces successful, Duration 0.00 seconds
Minus-[Notice] Minus started (child)
Minus-[Notice] Minus successful, Duration 0.00 seconds
Minus-[Notice] Minus started (child)
Minus-[Notice] Minus successful, Duration 0.00 seconds
RESULT|iteration time_taken|1 7.50
Traceback (most recent call last):
  File "/tmp/tmpupPpqA", line 7, in <module>
    exitcode = systest.returnValidationCode(99)
  File "/home/builder/jenkins-linode/workspace/master_clean-archlinux/Testing/SystemTests/lib/systemtests/stresstesting.py", line 362, in returnValidationCode
    if self.doValidation():
  File "/home/builder/jenkins-linode/workspace/master_clean-archlinux/Testing/SystemTests/lib/systemtests/stresstesting.py", line 332, in doValidation
    validation = self.validate()
  File "/home/builder/jenkins-linode/workspace/master_clean-archlinux/Testing/SystemTests/tests/analysis/VesuvioCorrectionsTest.py", line 285, in validate
    _validate_matrix_peak_height(self, corrections_wsg.getItem(2), corrections_ms_peak, corrections_ms_bin)
  File "/home/builder/jenkins-linode/workspace/master_clean-archlinux/Testing/SystemTests/tests/analysis/VesuvioCorrectionsTest.py", line 550, in _validate_matrix_peak_height
    self.assertTrue(abs(peak_bin - expected_bin) <= 1)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
```

**Comment by rosswhitfield** [comment]
Fixed in #22252
