### ISSUE TITLE
MantidPlot does not start on macOS ~since approved nightly

### ISSUE THREAD

**Issue by gvardany** [mantidproject/mantid#24816]
MantidPlot fails to import some python module on a clean macOS:
```
Welcome to Mantid 3.13.20190122.1441
Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid
Traceback (most recent call last):
  File "<string>", line 45, in <module>
  File "mantid/simpleapi.py", line 48, in <module>
    from . import plots  # noqa
  File "mantid/plots/__init__.py", line 21, in <module>
    from mantid.plots import helperfunctions, plotfunctions
  File "mantid/plots/plotfunctions.py", line 19, in <module>
    import matplotlib.dates as mdates
  File "matplotlib/dates.py", line 126, in <module>
    from dateutil.rrule import (rrule, MO, TU, WE, TH, FR, SA, SU, YEARLY,
  File "dateutil/rrule.py", line 20, in <module>
    from six.moves import _thread, range
ImportError: cannot import name _thread
Error running init file "/Applications/MantidPlot.app/Contents/MacOS/mantidplotrc.py"
Error in execution of algorithm DownloadInstrument:
InternetError: Failed to access https://api.github.com/rate_limit because there is no connection to the host p
Previous initialization of Python failed, cannot retry.
```
**Original reporter:** [ILL]/[Bjorn]. 

### Expected behavior

MantidPlot should start normally

### Actual behavior

Fails to initialise python

### Steps to reproduce the behavior

Start MantidPlot on a clean macOS system.

### Platforms affected

macOS

**Comment by gvardany** [comment]
It seems we need to pack the `six.py` also, which is a very old version on a clean system.
