### ISSUE TITLE
ISIS SANS v2 - Beam Centre Finder options accepts radius limits with a negative delta

### ISSUE THREAD

**Issue by aybamidele** [mantidproject/mantid#25011]
The SANS GUI should detect when the lower limit is greater than the higher limit
### Steps to reproduce the behavior
Open the ISIS SANS interface in Interfaces -> SANS -> ISIS SANS v2 experimental
Load a user file and batch file and click 'Process All'
On the left, click on Beam Centre and in the options menu set the "from" radius limit to be lower than the "to" limit
Click Run
An empty plot window shows up and an index error
`
Traceback (most recent call last):
  File "C:\MantidNightlyInstall\scripts\Interface\ui\sans_isis\work_handler.py", line 71, in on_finished
    self._listener.pop(process_id)['listener'].on_processing_finished(result)
  File "C:\MantidNightlyInstall\scripts\SANS\sans\gui_logic\presenter\beam_centre_presenter.py", line 30, in on_processing_finished
    self._presenter.on_processing_finished_centre_finder(result)
  File "C:\MantidNightlyInstall\scripts\SANS\sans\gui_logic\presenter\beam_centre_presenter.py", line 69, in on_processing_finished_centre_finder
    self._beam_centre_model.lab_pos_1 = result['pos1']
TypeError: 'NoneType' object has no attribute '__getitem__'
`
Trying to run using appropriate limits (with positive delta) keep does not do anything. The "Processing..." butting is greyed out.
### Platforms affected
Windows 10

**Comment by gemmaguest** [comment]
Fixed by PR #25066
