### ISSUE TITLE
MSlice - runtime error when no energy axis set

### ISSUE THREAD

**Issue by alicerussell1** [mantidproject/mantid#26187]
### Expected behavior
On slice tab in workspace manager if you set the axis to |Q| and 2Theta it will give an error. It should return an error i.e. `Cannot calculate slices without an energy axis` but without any of the extra information. Or, if possible, it would be better if it were not possible to select these together - like in the cut tab.

### Actual behavior
The following error is given:
```
Error in execution of algorithm Slice:
Cannot calculate slices without an energy axis
  at line 40 in 'C:\MantidNightlyInstall\scripts\ExternalInterfaces\mslice\models\slice\slice_algorithm.py'
  caused by line 79 in 'C:\MantidNightlyInstall\scripts\ExternalInterfaces\mslice\models\slice\slice_algorithm.py'
Traceback (most recent call last):
  File "C:\MantidNightlyInstall\scripts\ExternalInterfaces\mslice\presenters\slice_widget_presenter.py", line 67, in _plot_slice
    self._slice_plotter_presenter.plot_slice(*args)
  File "C:\MantidNightlyInstall\scripts\ExternalInterfaces\mslice\presenters\slice_plotter_presenter.py", line 23, in plot_slice
    self.create_slice(workspace, x_axis, y_axis, intensity_start, intensity_end, norm_to_one, colourmap)
  File "C:\MantidNightlyInstall\scripts\ExternalInterfaces\mslice\presenters\slice_plotter_presenter.py", line 29, in create_slice
    slice = compute_slice(selected_ws, x_axis, y_axis, norm_to_one)
  File "C:\MantidNightlyInstall\scripts\ExternalInterfaces\mslice\models\slice\slice_functions.py", line 34, in compute_slice
    EMode=workspace.e_mode, NormToOne=norm_to_one)
  File "C:\MantidNightlyInstall\scripts\ExternalInterfaces\mslice\util\mantid\algorithm_wrapper.py", line 27, in alg_wrapper
    result = algorithm(*args, StoreInADS=False, **kwargs)
  File "C:\MantidNightlyInstall\bin\mantid\simpleapi.py", line 1129, in algorithm_wrapper
    algm.execute()
RuntimeError: Cannot calculate slices without an energy axis
  at line 40 in 'C:\MantidNightlyInstall\scripts\ExternalInterfaces\mslice\models\slice\slice_algorithm.py'
  caused by line 79 in 'C:\MantidNightlyInstall\scripts\ExternalInterfaces\mslice\models\slice\slice_algorithm.py'

```

**Comment by alicerussell1** [comment]
Copied over to the Mslice repo [#482](https://github.com/mantidproject/mslice/issues/482)
