### ISSUE TITLE
Closing file browser crashes Frequency Analysis interface

### ISSUE THREAD

**Issue by LolloB** [mantidproject/mantid#26324]
In the grouping tab, if one wants to close the file browser the Interface will close and an error will be returned.

### Expected behavior
Che file browser should close successfully.

### Actual behavior
The following error occurs:

> Traceback (most recent call last):
 File "/home/lorenzo/mantid/scripts/Muon/GUI/Common/grouping_tab_widget/grouping_tab_widget_presenter.py", line 131, in handle_load_grouping_from_file
    groups, pairs, description, default = xml_utils.load_grouping_from_XML(filename)
  File "/home/lorenzo/mantid/scripts/Muon/GUI/Common/utilities/xml_utils.py", line 86, in load_grouping_from_XML
    tree = ET.parse(filename)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 647, in parse
    source = open(source, "rb")
IOError: [Errno 2] No such file or directory: ''

### Steps to reproduce the behavior
1. `Interfaces->Muon->Frequency Domain Analysis->Grouping`
2. Press `Load`, a file browser will open
3. Without selecting a file press `Cancel`

### Platforms affected
Tested on workbench for Ubuntu 18.04

**Comment by Harrietbrown** [comment]
This is the same bug as in #25823
