### ISSUE TITLE
Undo-fit crashes workbench

### ISSUE THREAD

**Issue by LolloB** [mantidproject/mantid#26340]
In the Workbench when undoing a fit sometimes the following error is returned:
>Python-[Error] Traceback (most recent call last):
 > File "/home/lorenzo/mantid/scripts/Muon/GUI/Common/results_tab_widget/results_tab_presenter.py", line 77, in _on_new_fit_performed_impl
    self._update_fit_results_view_on_new_fit()
  File "/home/lorenzo/mantid/scripts/Muon/GUI/Common/results_tab_widget/results_tab_presenter.py", line 93, in _update_fit_results_view_on_new_fit
    workspace_list, function_name = self._get_workspace_list()
  File "/home/lorenzo/mantid/scripts/Muon/GUI/Common/results_tab_widget/results_tab_presenter.py", line 89, in _get_workspace_list
    return workspace_list, fit_list[len(fit_list) - 1].fit_function_name
IndexError: list index out of range

It seems that this happens when `fit_list` is `[]` in https://github.com/mantidproject/mantid/blob/b84db52b3d7d8db2a19be5f9e77f23b628cfd9a6/scripts/Muon/GUI/Common/results_tab_widget/results_tab_presenter.py#L87

### Expected behavior
The fit should be undone and the parameters returned to their original values.

### Actual behavior
An `IndexError` is raised and the undo is not successful

### Steps to reproduce the behavior
1. `Interfaces->Muon->Data Analysis v2`
2. Load a run (eg. `EMU0062265`)
3. Go to `Fitting` tab and select a function (eg. `ExpDecay`)
4. Press `Undo Latest Fit`

### Platforms affected
Ubuntu 18.04

**Comment by LolloB** [comment]
Issue fixed in https://github.com/mantidproject/mantid/pull/26299
