### ISSUE TITLE
HFIR 4-circle index peak error

### ISSUE THREAD

**Issue by wdzhou** [mantidproject/mantid#26618]
### Actual behavior

Peak indexing shows error as 
```
Traceback (most recent call last):
  File "/opt/Mantid/scripts/HFIR_4Circle_Reduction/reduce4circleGUI.py", line 2735, in do_index_merged_scans_peaks
    index_status, ret_tup = self._myControl.index_peak(ub_matrix, scan_i, allow_magnetic=True)
  File "/opt/Mantid/scripts/HFIR_4Circle_Reduction/reduce4circleControl.py", line 1731, in index_peak
    RoundHKLs=False)
  File "/opt/Mantid/bin/mantid/simpleapi.py", line 1137, in algorithm_wrapper
    return _gather_returns(name, lhs, algm)
  File "/opt/Mantid/bin/mantid/simpleapi.py", line 995, in _gather_returns
    number_of_returned_values, number_of_values_on_lhs))
RuntimeError: IndexPeaks is trying to return 7 output(s) but you have provided 2 variable(s). These numbers must match.
```

### Platforms affected

All

**Comment by wdzhou** [comment]
It is caused by the change of outputs of IndexPeaks
