### ISSUE TITLE
Mantid fails without warning if Facilities.xml is corrupt

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#26830]
### Expected behavior
Mantid should show a warning if it cannot start because Facilities.xml is not parsable.

### Actual behavior
Mantid silently closes without any indication of what the problem was. You don't even see the splash screen.

### Steps to reproduce the behavior
On Windows:
- Edit `$APPDATA$/Roaming/mantidproject/mantid/instrument/Facilities.xml` and add some random text at the top
- Open an installed MantidPlot or Workbench using the shortcut on the desktop.
- Mantid silently closes with no indication of what went wrong.
- If you run `C:\MantidInstall\bin\launch_mantidplot.bat` from a terminal instead you see the error: 
` RuntimeError: Unable to parse file: in "$APPDATA$\Roaming\mantidproject\mantid\instrument\Facilities.xml"`

### Platforms affected
I noticed this on Windows 10 where my Facilities.xml had somehow become corrupt

**Comment by gemmaguest** [comment]
Anthony has hit the same problem, but even worse, because the error reporter swallowed the useful error message and just gave this output instead, making it very difficult to track down the problem:
```
C:\Users\BTR75544\nightly\MantidNightlyInstall\bin> launch_mantidplot.bat
Traceback (most recent call last):
  File "C:\Users\BTR75544\nightly\MantidNightlyInstall\scripts\ErrorReporter\error_dialog_app.py", line 36, in <module>
    from ErrorReporter.errorreport import CrashReportPage  # noqa
  File "C:\Users\BTR75544\nightly\MantidNightlyInstall\scripts\ErrorReporter\errorreport.py", line 37, in <module>
    class CrashReportPage(ErrorReportUIBase, ErrorReportUI):
  File "C:\Users\BTR75544\nightly\MantidNightlyInstall\scripts\ErrorReporter\errorreport.py", line 41, in CrashReportPage
    interface_manager = InterfaceManager()
Exception: unknown
C:\Users\BTR75544\nightly\MantidNightlyInstall\bin>
```

It would be good to get this fixed for the release because if users hit this it could cause a lot of wasted time in them (and us) trying to track down the problem.
