### ISSUE TITLE
Unhandled exception opening Settings dialog

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#27241]
### Expected behavior
No exception

### Actual behavior
When I try to open the Settings dialog I get this error:
```
Traceback (most recent call last):
  File "C:\MantidNightlyInstall\bin\workbench\app\mainwindow.py", line 623, in open_settings_window
    settings = SettingsPresenter(self)
  File "C:\MantidNightlyInstall\bin\workbench\widgets\settings\presenter.py", line 24, in __init__
    self.general_settings = general_settings if general_settings else GeneralSettings(parent)
  File "C:\MantidNightlyInstall\bin\workbench\widgets\settings\general\presenter.py", line 38, in __init__
    self.load_current_setting_values()
  File "C:\MantidNightlyInstall\bin\workbench\widgets\settings\general\presenter.py", line 100, in load_current_setting_values
    self.view.prompt_save_on_close.setChecked(CONF.get(self.PROMPT_SAVE_ON_CLOSE))
TypeError: setChecked(self, bool): argument 1 has unexpected type 'unicode'
```

### Steps to reproduce the behavior
I'm not sure how I got into this state, but once I did, any time I tried to open the Settings dialog it fails. I had originally had the facility set to TEST_LIVE with one of its instruments, and opened the reflectometry interface, which sets the default instrument to something else. My first thought is that it cannot handle this because the instrument is now not in the facility, but I can't reproduce it.

### Platforms affected
Seen on Windows 10

**Comment by gemmaguest** [comment]
I suspect this is to do with the fact that the reflectometry interface changes the instrument to one that is not in the default facility. This results in the default instrument subsequently being blank in the Settings dialog even though under the hood it seems to be set. I'll add a fix to get the reflectometry interface to change the default facility as well (perhaps with a warning or log message, in case someone opens it by accident).

**Comment by gemmaguest** [comment]
Closing because I can't reproduce this and the workaround is simply to restart workbench
