### ISSUE TITLE
Workbench: Plotting bugs for bin plots

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#27762]
There are some issues with bin plots.

1. Data is plotted as a distribution counts/us when it does not make sense for bin plots.  Also if the context menu worked it needs to handle the normalization correctly.
1. Right-click on the context menu throws an exception when deciding how to add the error bar menus (some lower-level code assumes that the index number of the line in a spectrum number).

 report to: @gvardany 
```
Traceback (most recent call last):
  File "C:\Mantid\Code\external\src\ThirdParty\lib\python3.8\lib\site-packages\matplotlib\cbook\__init__.py", line 216, in process
    func(*args, **kwargs)
  File "c:\mantid\code\qt\applications\workbench\workbench\plotting\figureinteraction.py", line 145, in on_mouse_button_press
    self._show_context_menu(event)
  File "c:\mantid\code\qt\applications\workbench\workbench\plotting\figureinteraction.py", line 307, in _show_context_menu
    self.add_error_bars_menu(menu, event.inaxes)
  File "c:\mantid\code\qt\applications\workbench\workbench\plotting\figureinteraction.py", line 402, in add_error_bars_menu
    if curve_has_errors(line):
  File "c:\mantid\code\qt\python\mantidqt\widgets\plotconfigdialog\curvestabwidget\__init__.py", line 89, in curve_has_errors
    return ax.artists_workspace_has_errors(curve)
  File "c:\mantid\code\framework\pythoninterface\mantid\plots\__init__.py", line 367, in artists_workspace_has_errors
    workspace_index = workspace.getIndexFromSpectrumNumber(spec_num)
RuntimeError: Could not find spectrum number in any spectrum.

```

**Comment by NickDraper** [comment]
Useful code for creating a single bin workspace
``` python 
ws = CreateSampleWorkspace()
wsBin = Integration(ws)
```
