### ISSUE TITLE
Colorfill right-click change colorbar to log

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#27824]
**Original reporter:** @PhilColebrooke 

### Expected Behaviour
- Colorfill right-click options and settings work correctly

### Actual Behaviour
On a colorfill plot in workbench, changing the colorbar to log via the right-click menu soft-crashes Mantid. 
**After doing that step**, if you change the colormap via the settings menu it gives an extra colorbar!!

### Steps to reproduce the behavior
- Plot any colorfill and right-click on the plot to change the colorbar to log: errorreporter for changing colorbar to log!
- Then close the Error Reporter and on the plot window enter Settings>Images tab and change the colormap: an extra colorbar is shown!

### Platforms affected
27/01/2020 Py3 Nightly Mantid Workbench
4.2 seems broken in a different way...
Mantid Nightly 13/12/2019 works perfectly (this is not an issue at all)

Trace out from the first problem is:
```
Traceback (most recent call last):
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\cbook\__init__.py", line 216, in process
    func(*args, **kwargs)
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\colorbar.py", line 1194, in on_mappable_changed
    self.update_normal(mappable)
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\colorbar.py", line 1241, in update_normal
    self.draw_all()
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\colorbar.py", line 483, in draw_all
    self._process_values()
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\colorbar.py", line 932, in _process_values
    b = self.norm.inverse(self._uniform_y(self.cmap.N + 1))
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\colors.py", line 1127, in inverse
    return vmin * np.ma.power((vmax / vmin), val)
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\MantidNightlyInstall\bin\workbench\plotting\figureinteraction.py", line 706, in _change_colorbar_axes
    self.canvas.figure.colorbar(image)
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\figure.py", line 2215, in colorbar
    cb = cbar.colorbar_factory(cax, mappable, **cb_kw)
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\colorbar.py", line 1640, in colorbar_factory
    cb = Colorbar(cax, mappable, **kwargs)
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\colorbar.py", line 1183, in __init__
    ColorbarBase.__init__(self, ax, **kw)
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\colorbar.py", line 460, in __init__
    self.draw_all()
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\colorbar.py", line 483, in draw_all
    self._process_values()
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\colorbar.py", line 932, in _process_values
    b = self.norm.inverse(self._uniform_y(self.cmap.N + 1))
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\colors.py", line 1127, in inverse
    return vmin * np.ma.power((vmax / vmin), val)
ZeroDivisionError: division by zero
```

**Comment by NickDraper** [comment]
This looks like it might be associated with the normalization work
