### ISSUE TITLE
MUSR data fails to load on Muon Gui

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#27950]
### Expected behavior
- Data should load correctly

### Actual behavior
- Open the Muon GUI
- Attempt to open `MUSR00062260.nxs`
- This will crash with:

```
Python-[Error] Traceback (most recent call last):
  File "/home//mantidpr/scripts/Muon/GUI/Common/grouping_tab_widget/grouping_tab_widget_presenter.py", line 196, in handle_update_finished
    self.calculation_finished_notifier.notify_subscribers()
  File "/home//mantidpr/qt/python/mantidqt/utils/observer_pattern.py", line 100, in notify_subscribers
    Observable.notify_subscribers(self, *args)
  File "/home//mantidpr/qt/python/mantidqt/utils/observer_pattern.py", line 56, in notify_subscribers
    self.thread_safe_update_call(arg, **kwargs)
  File "/home//mantidpr/qt/python/mantidqt/utils/qt/qappthreadcall.py", line 48, in __call__
    return self.callee(*args, **kwargs)
  File "/home//mantidpr/qt/python/mantidqt/utils/observer_pattern.py", line 60, in _notify_subscribers_impl
    observer.update(self, arg, **kwargs)
  File "/home//mantidpr/qt/python/mantidqt/utils/observer_pattern.py", line 83, in update
    self.callback()
  File "/home//mantidpr/scripts/Muon/GUI/Common/seq_fitting_tab_widget/seq_fitting_tab_presenter.py", line 72, in handle_selected_workspaces_changed
    self.handle_fit_function_updated()
  File "/home//mantidpr/scripts/Muon/GUI/Common/seq_fitting_tab_widget/seq_fitting_tab_presenter.py", line 39, in handle_fit_function_updated
    self.model.clear_fit_information()
  File "/home//mantidpr/scripts/Muon/GUI/Common/fitting_tab_widget/fitting_tab_model.py", line 497, in clear_fit_information
    fits = self.context.fitting_context.fit_list.copy()
AttributeError: 'list' object has no attribute 'copy'
```

### Platforms affected
Ubuntu (Looks like All)

**Comment by Mantid-Matthew** [comment]
This is an python2 only bug as copy was added to lists in python3. We no longer need this interface to work with python 2 so closing this issue.
