### ISSUE TITLE
Project Recovery dialog does not appear after segfault

### ISSUE THREAD

**Issue by giovannidisiena** [mantidproject/mantid#28075]
### Expected behavior
You should be presented with the Project Recovery dialog when re-opening Mantid after a segfault.

### Actual behavior
The Project Recovery dialog does not appear in Workbench on Windows.

### Steps to reproduce the behavior
Follow simple test 1:  http://developer.mantidproject.org/Testing/ErrorReporter-ProjectRecovery/ProjectRecoveryTesting.html

### Platforms affected
Windows

**Comment by martyngigg** [comment]
It looks like the issue is that psutil is now giving `AccessDenied` errors when access trying to access certain processes:
```python
Traceback (most recent call last):
  File "C:\MantidNightlyInstall\bin\lib\site-packages\psutil\_pswindows.py", line 808, in cmdline
    ret = cext.proc_cmdline(self.pid, use_peb=True)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\MantidNightlyInstall\bin\lib\site-packages\psutil\_pswindows.py", line 707, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\MantidNightlyInstall\bin\lib\site-packages\psutil\_pswindows.py", line 723, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\MantidNightlyInstall\bin\lib\site-packages\psutil\_pswindows.py", line 811, in cmdline
    ret = cext.proc_cmdline(self.pid, use_peb=False)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\MantidNightlyInstall\bin\workbench\projectrecovery\projectrecovery.py", line 218, in check_for_recover_checkpoint
    num_of_other_mantid_processes = self._number_of_other_workbench_processes()
  File "C:\MantidNightlyInstall\bin\workbench\projectrecovery\projectrecovery.py", line 236, in _number_of_other_workbench_processes
    if self._is_mantid_workbench_process(proc.cmdline()):
  File "C:\MantidNightlyInstall\bin\lib\site-packages\psutil\__init__.py", line 791, in cmdline
    return self._proc.cmdline()
  File "C:\MantidNightlyInstall\bin\lib\site-packages\psutil\_pswindows.py", line 709, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=96)
```
PID 96 is owned by the system so I guess it can't query properties about it.
