### ISSUE TITLE
unable to open context menu in plots of MDHistoWorkspace

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#28082]
### Expected behavior
If a MDHistoWorkspace, or any other that lacks the `isDistribution()` method, is plotted it should still be able to generate a context menu.
### Actual behavior
In that situation the context menu cannot be generated because it requires `isDistribution()` to create the normalization options.
### Steps to reproduce the behavior
1. open workbench
2. run this script to get the plot:
```
import matplotlib.pyplot as plt
from mantid import plots
from mantid.simpleapi import Load, ConvertToMD, BinMD, ConvertUnits, Rebin
from matplotlib.colors import LogNorm

# generate a nice 2D multi-dimensional workspace
data = Load('CNCS_7860')
data = ConvertUnits(InputWorkspace=data,Target='DeltaE', EMode='Direct', EFixed=3)
data = Rebin(InputWorkspace=data, Params='-3,0.025,3', PreserveEvents=False)
md = ConvertToMD(InputWorkspace=data,
                 QDimensions='|Q|',
                 dEAnalysisMode='Direct')
sqw = BinMD(InputWorkspace=md,
            AlignedDim0='|Q|,0,3,100',
            AlignedDim1='DeltaE,-3,3,100')

#2D plot
fig, ax = plt.subplots(subplot_kw={'projection':'mantid'})
c = ax.pcolormesh(sqw, norm=LogNorm())
cbar=fig.colorbar(c)
cbar.set_label('Intensity (arb. units)') #add text to colorbar
fig.show()
```
3. right click on the plot.
4. you recive the following error:
```
Traceback (most recent call last):
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\cbook\__init__.py", line 216, in process
    func(*args, **kwargs)
  File "C:\MantidNightlyInstall\bin\workbench\plotting\figureinteraction.py", line 138, in on_mouse_button_press
    self._show_context_menu(event)
  File "C:\MantidNightlyInstall\bin\workbench\plotting\figureinteraction.py", line 291, in _show_context_menu
    self._add_normalization_option_menu(menu, event.inaxes)
  File "C:\MantidNightlyInstall\bin\workbench\plotting\figureinteraction.py", line 326, in _add_normalization_option_menu
    can_toggle_normalization = self._can_toggle_normalization(ax)
  File "C:\MantidNightlyInstall\bin\workbench\plotting\figureinteraction.py", line 711, in _can_toggle_normalization
    if axis != MantidAxType.BIN and not ads.retrieve(workspace_name).isDistribution() and ax.data_replaced:
AttributeError: 'MDHistoWorkspace' object has no attribute 'isDistribution'
```

**Comment by ConorMFinn** [comment]
Fixed by #28125
