### ISSUE TITLE
Unhandled exception in mSlice

### ISSUE THREAD

**Issue by Mantid-Matthew** [mantidproject/mantid#28173]
In mSlice if I create some cuts and then go to the MD Histo tab and click Save to Workbench I get the following stack trace and the unhandled exception box pops up.

```
Exception ignored in: <function Workspace.__del__ at 0x0000024B7865C4C0>
Traceback (most recent call last):
  File "C:\MantidNightlyInstall\scripts\ExternalInterfaces\mslice\workspace\workspace.py", line 50, in __del__
    if hasattr(self, '_raw_ws') and self._raw_ws.name().endswith('_HIDDEN'):
RuntimeError: Variable invalidated, data has been deleted.
Traceback (most recent call last):
  File "C:\MantidNightlyInstall\scripts\ExternalInterfaces\mslice\app\mainwindow.py", line 188, in button_savetoads
    self.workspace_presenter.notify(ws_command.SaveToADS)
  File "C:\MantidNightlyInstall\scripts\ExternalInterfaces\mslice\presenters\workspace_manager_presenter.py", line 50, in notify
    self._command_map[command]()
  File "C:\MantidNightlyInstall\scripts\ExternalInterfaces\mslice\presenters\workspace_manager_presenter.py", line 110, in _save_to_ads
    export_workspace_to_ads(workspace)
  File "C:\MantidNightlyInstall\scripts\ExternalInterfaces\mslice\models\workspacemanager\workspace_algorithms.py", line 274, in export_workspace_to_ads
    workspace = workspace.convert_to_matrix()
  File "C:\MantidNightlyInstall\scripts\ExternalInterfaces\mslice\workspace\histogram_workspace.py", line 40, in convert_to_matrix
    bin_size = coord[coord.keys()[0]][1] - coord[coord.keys()[0]][0]
TypeError: 'dict_keys' object is not subscriptable
```

**Comment by martyngigg** [comment]
Fixed in #f935f1fd67fc16888e98b3aade76b9a3c2b091cd
