### ISSUE TITLE
Exception when you right-click a non-workspace plot

### ISSUE THREAD

**Issue by PhilColebrooke** [mantidproject/mantid#28187]
```
fig, ax = plt.subplots(subplot_kw={'projection':'mantid'})
ax.plot([0,1],[0,1])
fig.show()
```

Right-click the figure.

```
Traceback (most recent call last):
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\cbook\__init__.py", line 216, in process
    func(*args, **kwargs)
  File "C:\MantidNightlyInstall\bin\workbench\plotting\figureinteraction.py", line 138, in on_mouse_button_press
    self._show_context_menu(event)
  File "C:\MantidNightlyInstall\bin\workbench\plotting\figureinteraction.py", line 299, in _show_context_menu
    self._add_normalization_option_menu(menu, event.inaxes)
  File "C:\MantidNightlyInstall\bin\workbench\plotting\figureinteraction.py", line 326, in _add_normalization_option_menu
    can_toggle_normalization = self._can_toggle_normalization(ax)
  File "C:\MantidNightlyInstall\bin\workbench\plotting\figureinteraction.py", line 709, in _can_toggle_normalization
    axis = ax.creation_args[0].get('axis', None)
IndexError: list index out of range
```

**Comment by ConorMFinn** [comment]
Fixed by #28199
