### ISSUE TITLE
Project Recovery psutil fail on launch

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#28184]
***Please Report to Mona Sarter / ISIS***

Found by @PhilColebrooke and @martyngigg 

### Summary
Get an access denied error, and fail on startup of workbench (usually if many project recovery files have been saved and not deleted). 

### What's happening

Workbench tries to load a project recovery instance from a previous crash into the recovery table on launch. It checks for any currently running versions of Mantid assigned to those recovery files, but the PID had been reassigned to another programme. This was the access denied error. 

### What to do
This means we need more protection for exception catching around our psutil implementation. This error is likely to be due to the upgrade in psutil version. 
There error occured around line 167 of qt/applications/workbench/workbench/projectrecovery/projectrecovery.py

**Comment by DanielMurphy22** [comment]
Found separately, but believed to be caused by the same issue:

Mona from ISIS has found crashes while using the ConvFit tab in the IndirectDataAnalysis GUI. The stacktrace (with personal info removed) below seems to suggest that the error is in saving project recovery files:

```       
    Traceback (most recent call last):
 File "C:\MantidInstall\bin\workbench\app\mainwindow.py", line 896, in main
   exit_value = start_workbench(app, options)
 File "C:\MantidInstall\bin\workbench\app\mainwindow.py", line 840, in start_workbench
   main_window.project_recovery.repair_checkpoints()
 File "C:\MantidInstall\bin\workbench\projectrecovery\projectrecovery.py", line 333, in repair_checkpoints
   self._remove_directory_and_directory_trees(directory)
 File "C:\MantidInstall\bin\workbench\projectrecovery\projectrecovery.py", line 139, in _remove_directory_and_directory_trees
   shutil.rmtree(directory)
 File "C:\MantidInstall\bin\lib\shutil.py", line 730, in rmtree
   return _rmtree_unsafe(path, onerror)
 File "C:\MantidInstall\bin\lib\shutil.py", line 608, in _rmtree_unsafe
   onerror(os.unlink, fullname, sys.exc_info())
 File "C:\MantidInstall\bin\lib\shutil.py", line 606, in _rmtree_unsafe
   os.unlink(fullname)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\...\\AppData\\Roaming\\mantidproject\\mantid\\workbench-recovery\\...\\100.py'
```
