### ISSUE TITLE
Cannot open any of the python interfaces

### ISSUE THREAD

**Issue by alicerussell1** [mantidproject/mantid#28296]
### Expected behavior
Interface should open

### Actual behavior
Interface does not open and gives the error 
```
Traceback (most recent call last):
  File "C:\Users\fvv28776\mantid\qt\applications\workbench\workbench\app\mainwindow.py", line 424, in <lambda>
    lambda checked_py, script=script: self.launch_custom_python_gui(script))
  File "C:\Users\fvv28776\mantid\qt\applications\workbench\workbench\app\mainwindow.py", line 382, in launch_custom_python_gui
    self.interface_executor.execute(open(filename).read(), filename)
  File "C:\Users\fvv28776\mantid\qt\python\mantidqt\widgets\codeeditor\execution.py", line 145, in execute
    executor.execute(code_str, filename, flags, self.globals_ns, line_offset)
TypeError: CodeExecution.execute(): argument 5 has unexpected type 'str'
```

### Steps to reproduce the behavior
Open any python interface in workbench

### Platforms affected
Probably all, tested on windows and ubuntu

**Comment by alicerussell1** [comment]
This has just been fixed by #28287
