### ISSUE TITLE
Unable to import mantid from python

### ISSUE THREAD

**Issue by gvardany** [mantidproject/mantid#28439]
Trying to import mantid.simpleapi in python fails on macOS:
```
>>> import sys
>>> sys.path.append('/Applications/MantidPlot.app/Contents/MacOS')
>>> from mantid.simpleapi import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Applications/MantidPlot.app/Contents/MacOS/mantid/__init__.py", line 106, in <module>
    from mantid import kernel as _kernel
  File "/Applications/MantidPlot.app/Contents/MacOS/mantid/kernel/__init__.py", line 38, in <module>
    import_mantid_cext('._kernel', 'mantid.kernel', globals())
  File "/Applications/MantidPlot.app/Contents/MacOS/mantid/utils.py", line 35, in import_mantid_cext
    lib = import_module(modulename, package)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
SystemError: initialization of _kernel raised unreported exception
```
Found on macOS, likely macOS-only.

**Comment by DanielMurphy22** [comment]
Same as #28538
