### ISSUE TITLE
Cannot plot in workbench

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#28460]
### Expected behavior
- Plotting should work 

### Actual behavior
- The following exception is thrown on today's build of master

### Steps to reproduce the behavior
- Create a sample workspace
- Plot spectrum 1
- Traceback:
```
Traceback (most recent call last):
  File "/home/david/mantid/qt/applications/workbench/workbench/plugins/workspacewidget.py", line 94, in _do_plot_spectrum
    plot_from_names(names, errors, overplot)
  File "/home/david/mantid/qt/python/mantidqt/plotting/functions.py", line 105, in plot_from_names
    waterfall=selection.plot_type==selection.Waterfall)
  File "/home/david/mantid/Framework/PythonInterface/mantid/plots/plotfunctions.py", line 56, in inner_func
    return func(workspaces, *args, **kwargs)
  File "/home/david/mantid/Framework/PythonInterface/mantid/plots/plotfunctions.py", line 124, in plot
    fig, axes = get_plot_fig(overplot, ax_properties, window_title, num_axes, fig)
  File "/home/david/mantid/Framework/PythonInterface/mantid/plots/plotfunctions.py", line 283, in get_plot_fig
    fig, _, _, _ = create_subplots(axes_num)
  File "/home/david/mantid/Framework/PythonInterface/mantid/plots/plotfunctions.py", line 209, in create_subplots
    fig = plt.figure()
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 552, in figure
    _pylab_helpers.Gcf.set_active(figManager)
  File "/home/david/mantid/qt/applications/workbench/workbench/plotting/globalfiguremanager.py", line 189, in set_active
    cls.figs[manager.num] = manager
  File "/home/david/mantid/qt/applications/workbench/workbench/plotting/observabledictionary.py", line 50, in __setitem__
    self._notify_observers(action, key)
  File "/home/david/mantid/qt/applications/workbench/workbench/plotting/observabledictionary.py", line 41, in _notify_observers
    observer.notify(action, key)
  File "/home/david/mantid/qt/applications/workbench/workbench/plotting/globalfiguremanager.py", line 47, in notify
    self.figure_manager.notify_observers(FigureAction.New, key)
  File "/home/david/mantid/qt/applications/workbench/workbench/plotting/globalfiguremanager.py", line 257, in notify_observers
    observer.notify(action, figure_number)
  File "/home/david/mantid/qt/applications/workbench/workbench/widgets/plotselector/model.py", line 72, in notify
    self.presenter.append_to_plot_list(plot_number)
  File "/home/david/mantid/qt/applications/workbench/workbench/widgets/plotselector/presenter.py", line 65, in append_to_plot_list
    self.view.append_to_plot_list(plot_number)
  File "/home/david/mantid/qt/python/mantidqt/utils/qt/qappthreadcall.py", line 46, in __call__
    return self.callee(*args, **kwargs)
  File "/home/david/mantid/qt/applications/workbench/workbench/widgets/plotselector/view.py", line 226, in append_to_plot_list
    plot_name_widget = PlotNameWidget(self.presenter, plot_number, self)
  File "/home/david/mantid/qt/applications/workbench/workbench/widgets/plotselector/view.py", line 616, in __init__
    self.line_edit = QLineEdit(self.presenter.get_plot_name_from_number(plot_number))
TypeError: arguments did not match any overloaded call:
  QLineEdit(parent: QWidget = None): argument 1 has unexpected type 'bool'
  QLineEdit(str, parent: QWidget = None): argument 1 has unexpected type 'bool'
```

**Comment by PhilColebrooke** [comment]
https://github.com/mantidproject/mantid/blob/56c9d2c7a0e6d8cac1457eb7630d11f8eb564104/qt/applications/workbench/workbench/plotting/figuremanager.py#L371

This is now returning a bool instead of a string.
