### ISSUE TITLE
Unhandled Exception in Figure Options when Setting Label with Invalid Symbol

### ISSUE THREAD

**Issue by ConorMFinn** [mantidproject/mantid#28854]
### Expected behavior
A warning message should be printed when an invalid symbol is given as a label. 
### Actual behavior
An unhandled exception occurs with a `ValueError`:
```
Traceback (most recent call last):
  File "/home/conor/repos/mantid/qt/python/mantidqt/widgets/plotconfigdialog/presenter.py", line 75, in apply_properties_and_exit
    self.apply_properties()
  File "/home/conor/repos/mantid/qt/python/mantidqt/widgets/plotconfigdialog/presenter.py", line 72, in apply_properties
    self.fig.canvas.draw()
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_qt5agg.py", line 127, in draw
    super(FigureCanvasQTAggBase, self).draw()
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_agg.py", line 430, in draw
    self.figure.draw(self.renderer)
  File "/usr/lib/python3/dist-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/figure.py", line 1299, in draw
    renderer, self, artists, self.suppressComposite)
  File "/usr/lib/python3/dist-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/lib/python3/dist-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/axes/_base.py", line 2437, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/usr/lib/python3/dist-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/lib/python3/dist-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/axis.py", line 1147, in draw
    self.label.draw(renderer)
  File "/usr/lib/python3/dist-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/text.py", line 715, in draw
    bbox, info, descent = textobj._get_layout(renderer)
  File "/usr/lib/python3/dist-packages/matplotlib/text.py", line 317, in _get_layout
    ismath=ismath)
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_agg.py", line 231, in get_text_width_height_descent
    self.mathtext_parser.parse(s, self.dpi, prop)
  File "/usr/lib/python3/dist-packages/matplotlib/mathtext.py", line 3303, in parse
    box = self._parser.parse(s, font_output, fontsize, dpi)
  File "/usr/lib/python3/dist-packages/matplotlib/mathtext.py", line 2522, in parse
    six.text_type(err)]))
ValueError: 
\A
^
Unknown symbol: \A (at char 0), (line:1, col:1)

```
### Steps to reproduce the behavior
1. Plot something
2. Change a symbol to something invalid (such as `d-Spacing ($\AA$)` -> `d-Spacing ($\A$)`)
3. Click Ok or Apply
### Platforms affected
All

**Comment by thomashampson** [comment]
This relates to the text boxes in the Figure Options dialog
