### ISSUE TITLE
`LRAutoReduction` error when `NormalizationType` set to `WithReference`

### ISSUE THREAD

**Issue by marshallmcdonnell** [mantidproject/mantid#28920]
### Expected behavior
Be able to run [LRAutoReduction](https://docs.mantidproject.org/nightly/algorithms/LRAutoReduction-v1.html) with `NormalizationType` set to `WithReference` without error

### Actual behavior
Currently getting the following traceback about a pickling error for EventWorkspace.
Most likely comes from the way the `LRWithReference` algorithm is being called with `**kwargs` inside `LRAutoReduction` and then using `deepcopy`inside the `LRWithReference` algorithm.

```python
Traceback (most recent call last):
  File "/SNS/REF_L/shared/autoreduce/reduce_REF_L.py", line 78, in <module>
    Refl1DModelParameters=REFL1D_PARS)
  File "/opt/mantidnightly/lib/mantid/simpleapi.py", line 1136, in algorithm_wrapper
    algm.execute()
RuntimeError: Pickling of "mantid.dataobjects._dataobjects.EventWorkspace" instances is not enabled (http://www.boost.org/libs/python/doc/v2/pickle.html)
  at line 89 in '/opt/mantidnightly/plugins/python/algorithms/LRReductionWithReference.py'
  caused by line 150 in '/usr/lib64/python3.6/copy.py'
  caused by line 240 in '/usr/lib64/python3.6/copy.py'
  caused by line 169 in '/usr/lib64/python3.6/copy.py'
  at line 695 in '/opt/mantidnightly/plugins/python/algorithms/LRAutoReduction.py'
  caused by line 1136 in '/opt/mantidnightly/lib/mantid/simpleapi.py'
```

**Comment by marshallmcdonnell** [comment]
PR #28921 didn't fix this issue so going to re-open and further investigate the issue in a new feature branch.
