### ISSUE TITLE
Generate Recovery Script causes Unexpected Exception with fresh workbench

### ISSUE THREAD

**Issue by Pasarus** [mantidproject/mantid#29194]
### Expected behavior
Effectively do nothing or create an empty recovery script

### Actual behavior
Throws an unexpected exception.

```
Traceback (most recent call last):
  File "C:\MantidNightlyInstall\bin\workbench\app\mainwindow.py", line 582, in generate_script_from_workspaces
    task.start()
  File "C:\MantidNightlyInstall\bin\mantidqt\utils\asynchronous.py", line 144, in start
    raise self.recv.exc_value
  File "C:\MantidNightlyInstall\bin\mantidqt\utils\asynchronous.py", line 65, in run
    out = self.target(*self.args, **self.kwargs)
  File "C:\MantidNightlyInstall\bin\workbench\app\mainwindow.py", line 585, in _generate_script_from_workspaces
    script = "from mantid.simpleapi import *\n\n" + get_all_workspace_history_from_ads()
  File "C:\MantidNightlyInstall\bin\workbench\utils\workspacehistorygeneration.py", line 67, in get_all_workspace_history_from_ads
    return guarantee_unique_lines(script)
  File "C:\MantidNightlyInstall\bin\workbench\utils\workspacehistorygeneration.py", line 57, in guarantee_unique_lines
    alg.execute()
RuntimeError: [Errno 2] No such file or directory: 'C:\\Users\\Sam\\AppData\\Roaming\\mantidproject\\mantid\\recovery\\summedHistory.py'
  at line 113 in 'C:/MantidNightlyInstall/plugins/python\algorithms/OrderWorkspaceHistory.py'
```

### Steps to reproduce the behavior
- Open Workbench
- Click `File->Generate Recovery Script`

### Platforms affected
Windows

**Comment by Pasarus** [comment]
I did some discovery it seems to be an issue in OrderWorkspaceHistory.py. The algorithm assumes that if the `InputString` property is set then it needs to write out to a file that the algorithm expects to exist, in this case, both the `InputString` and output file does not exist so it fails when attempting to write to the output file.
