### ISSUE TITLE
Export batch in ISIS SANS raises exception.

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#29353]
### Expected behavior
The isis sans gui should be able to export the table as a batch file
### Actual behavior
When attempting to export a batch file the following exception is raised:
```
Traceback (most recent call last):
  File "C:\MantidNightlyInstall\scripts\Interface\ui\sans_isis\sans_data_processor_gui.py", line 455, in _export_table_clicked
    self._call_settings_listeners(lambda listener: listener.on_export_table_clicked())
  File "C:\MantidNightlyInstall\scripts\Interface\ui\sans_isis\sans_data_processor_gui.py", line 230, in _call_settings_listeners
    target(listener)
  File "C:\MantidNightlyInstall\scripts\Interface\ui\sans_isis\sans_data_processor_gui.py", line 455, in <lambda>
    self._call_settings_listeners(lambda listener: listener.on_export_table_clicked())
  File "C:\MantidNightlyInstall\scripts\SANS\sans\gui_logic\presenter\run_tab_presenter.py", line 120, in on_export_table_clicked
    self._presenter.on_export_table_clicked()
  File "C:\MantidNightlyInstall\scripts\SANS\sans\gui_logic\presenter\run_tab_presenter.py", line 706, in on_export_table_clicked
    default_filename = self._table_model.batch_file
AttributeError: 'TableModel' object has no attribute 'batch_file'
```
### Steps to reproduce the behavior

1. Open Interfaces->ISIS SANS
2. Choose Load User File, Maskfile.txt
3. Choose Load Batch File, choose batch_mode_reduction.csv
4. Click the Export Table button.

### Platforms affected
Windows, presumably all.

**Comment by gemmaguest** [comment]
Looks like this is Windows only, which is why it wasn't spotted.
