### ISSUE TITLE
Elwin crash

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#29547]
Open Indirect data reduction
Type runs `144076-80` (osiris)
Change the Grouping to `Groups` and select 1
Click `Run`

Go to the S(Q,w) tab
Change `File` to `workspace`
Select the first run
Click Run
Repeat until you have done all of the workspaces

Save all of the `_sqw` workspaces as local nxs files
Close data reduction

** once you have done the above once you can skip to the following steps **

Open indirect data analysis
Click Browse
Select the files you just saved
Click Run
It all works ok
In the ADS, you will see a workspace that ends in `_elf`, try to plot it
Mantid crashes

**Comment by AnthonyLim23** [comment]
stack trace:

```
Traceback (most recent call last):
 File "/usr/lib64/python3.6/site-packages/matplotlib/mathtext.py", line 2515, in parse
   result = self._expression.parseString(s)
 File "/usr/local/lib/python3.6/site-packages/pyparsing.py", line 1955, in parseString
   raise exc
 File "/usr/local/lib/python3.6/site-packages/pyparsing.py", line 3814, in parseImpl
   raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected end of text, found '$'  (at char 8), (line:1, col:9)
```
During handling of the above exception, another exception occurred:
```
Traceback (most recent call last):
 File "/opt/mantidnightly/lib/workbench/plugins/workspacewidget.py", line 105, in _do_plot_spectrum
   plot_from_names(names, errors, overplot, advanced=advanced)
 File "/opt/mantidnightly/lib/mantidqt/plotting/functions.py", line 139, in plot_from_names
   log_name=selection.log_name, log_values=log_values)
 File "/opt/mantidnightly/lib/mantid/plots/plotfunctions.py", line 57, in inner_func
   return func(workspaces, *args, **kwargs)
 File "/opt/mantidnightly/lib/mantid/plots/plotfunctions.py", line 188, in plot
   fig.canvas.draw()
 File "/usr/lib64/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 437, in draw
   self.figure.draw(self.renderer)
 File "/usr/lib64/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
   return draw(artist, renderer, *args, **kwargs)
 File "/usr/lib64/python3.6/site-packages/matplotlib/figure.py", line 1493, in draw
   renderer, self, artists, self.suppressComposite)
 File "/usr/lib64/python3.6/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
   a.draw(renderer)
 File "/usr/lib64/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
   return draw(artist, renderer, *args, **kwargs)
 File "/usr/lib64/python3.6/site-packages/matplotlib/axes/_base.py", line 2635, in draw
   mimage._draw_list_compositing_images(renderer, self, artists)
 File "/usr/lib64/python3.6/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
   a.draw(renderer)
 File "/usr/lib64/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
   return draw(artist, renderer, *args, **kwargs)
 File "/usr/lib64/python3.6/site-packages/matplotlib/axis.py", line 1204, in draw
   self.label.draw(renderer)
 File "/usr/lib64/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
   return draw(artist, renderer, *args, **kwargs)
 File "/usr/lib64/python3.6/site-packages/matplotlib/text.py", line 706, in draw
   bbox, info, descent = textobj._get_layout(renderer)
 File "/usr/lib64/python3.6/site-packages/matplotlib/text.py", line 309, in _get_layout
   ismath=ismath)
 File "/usr/lib64/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 241, in get_text_width_height_descent
   self.mathtext_parser.parse(s, self.dpi, prop)
 File "/usr/lib64/python3.6/site-packages/matplotlib/mathtext.py", line 3293, in parse
   box = self._parser.parse(s, font_output, fontsize, dpi)
 File "/usr/lib64/python3.6/site-packages/matplotlib/mathtext.py", line 2521, in parse
   six.text_type(err)]))
ValueError: 
sample ($ $)
       ^
Expected end of text, found '$'  (at char 8), (line:1, col:9)
```
