### ISSUE TITLE
Failing doc tests on Ubuntu 20.04

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#29733]
### Expected behavior
After merging #29684, documentation should build without warnings, and doc tests should pass

### Actual behavior
On Ubuntu 20.04 I found the following warnings
```
WARNING: relatedalgorithms - Could not find algorithm "MonteCarloAbsorption, SetSample, SaveReflections" listed in the seeAlso for AddAbsorptionWeightedPathLengths.v1
WARNING: relatedalgorithms - Could not find algorithm "PowderReduceP2D" listed in the seeAlso for SaveP2D.v1
/home/3y9/Mantid/mantid/docs/source/release/v3.11.0/framework.rst:53: WARNING: undefined label: algm-savemdworkspacetovtk-v1 (if the link has no caption the label must precede a section header)
/home/3y9/Mantid/mantid/docs/source/release/v3.11.0/framework.rst:53: WARNING: undefined label: algm-loadvtk-v1 (if the link has no caption the label must precede a section header)
/home/3y9/Mantid/mantid/docs/source/release/v3.7.1/framework.rst:141: WARNING: undefined label: algm-savemdworkspacetovtk (if the link has no caption the label must precede a section header)
/home/3y9/Mantid/mantid/docs/source/release/v3.9.0/framework.rst:35: WARNING: undefined label: algm-savemdworkspacetovtk (if the link has no caption the label must precede a section header)
/home/3y9/Mantid/mantid/docs/source/release/v3.9.0/ui.rst:60: WARNING: undefined label: algm-savemdworkspacetovtk (if the link has no caption the label must precede a section header)
```
In addition, the following errors mean that no images are generated for the corresponding interfaces:
```
reading sources... [ 81%] interfaces/Data Comparison
UserSubWindowFactoryImpl-[Error] UserSubWindowFactory: "Data Comparison" is not registered as an interface name.
InterfaceManager-[Error] Error creating interface Data Comparison
UserSubWindowFactoryImpl-[Error] UserSubWindowFactory: "Data Comparison" is not registered as an interface name.
InterfaceManager-[Error] Error creating interface Data Comparison
UserSubWindowFactoryImpl-[Error] UserSubWindowFactory: "Data Comparison" is not registered as an interface name.
InterfaceManager-[Error] Error creating interface Data Comparison
UserSubWindowFactoryImpl-[Error] UserSubWindowFactory: "Data Comparison" is not registered as an interface name.
InterfaceManager-[Error] Error creating interface Data Comparison
UserSubWindowFactoryImpl-[Error] UserSubWindowFactory: "Data Comparison" is not registered as an interface name.
InterfaceManager-[Error] Error creating interface Data Comparison
```
and 
```
reading sources... [ 83%] interfaces/Sample Transmission Calculator
UserSubWindowFactoryImpl-[Error] UserSubWindowFactory: "Sample Transmission Calculator" is not registered as an interface name.
InterfaceManager-[Error] Error creating interface Sample Transmission Calculator
UserSubWindowFactoryImpl-[Error] UserSubWindowFactory: "Sample Transmission Calculator" is not registered as an interface name.
InterfaceManager-[Error] Error creating interface Sample Transmission Calculator
UserSubWindowFactoryImpl-[Error] UserSubWindowFactory: "Sample Transmission Calculator" is not registered as an interface name.
InterfaceManager-[Error] Error creating interface Sample Transmission Calculator
UserSubWindowFactoryImpl-[Error] UserSubWindowFactory: "Sample Transmission Calculator" is not registered as an interface name.
InterfaceManager-[Error] Error creating interface Sample Transmission Calculator
```
Running the doc tests yield the following errors:
```
Document: algorithms/VesuvioAnalysis-v1
---------------------------------------
**********************************************************************
File "algorithms/VesuvioAnalysis-v1.rst", line 73, in default
Failed example:
    # create table of elements
    table = CreateEmptyTableWorkspace()
    table.addColumn(type="str", name="Symbol")
    table.addColumn(type="double", name="Mass (a.u.)")
    table.addColumn(type="double", name="Intensity lower limit")
    table.addColumn(type="double", name="Intensity value")
    table.addColumn(type="double", name="Intensity upper limit")
    table.addColumn(type="double", name="Width lower limit")
    table.addColumn(type="double", name="Width value")
    table.addColumn(type="double", name="Width upper limit")
    table.addColumn(type="double", name="Centre lower limit")
    table.addColumn(type="double", name="Centre value")
    table.addColumn(type="double", name="Centre upper limit")
    table.addRow(['H', 1.0079,  0.,1.,9.9e9,  3.,  4.5,  6.,  -1.5, 0., 0.5])
    table.addRow(['C', 12.0,    0.,1.,9.9e9,  10., 15.5, 30., -1.5, 0., 0.5])

    VesuvioAnalysis(IPFile = "ip2018.par", ComptonProfile = table, AnalysisMode = "LoadReduceAnalyse",
                    NumberOfIterations = 2, OutputName = "polyethylene", Runs = "38898-38906", TOFRangeVector = [110.,1.5,460.],
                    Spectra = [135,182], MonteCarloEvents = 1e3, ConstraintsProfileNumbers = [0,1],
                    ConstraintsProfileScatteringCrossSection = "2.*82.03/5.51", SpectraToBeMasked = [173,174,181],
                    SubtractResonancesFunction = 'name=Voigt,LorentzAmp=1.,LorentzPos=284.131,LorentzFWHM=2,GaussianFWHM=3;',
                    YSpaceFitFunctionTies = "(c6=0., c4=0.)")

    fit_results = mtd["polyethylene_H_JoY_sym_Parameters"]

    print("variable", "value")
    for row in range(fit_results.rowCount()):
        print(fit_results.column(0)[row],"{:.3f}".format(fit_results.column(1)[row]))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.8/doctest.py", line 1329, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest default[0]>", line 17, in <module>
        VesuvioAnalysis(IPFile = "ip2018.par", ComptonProfile = table, AnalysisMode = "LoadReduceAnalyse",
      File "/home/3y9/Mantid/mantid/Framework/PythonInterface/mantid/simpleapi.py", line 1120, in __call__
        algm.execute()
    RuntimeError: Invalid value for property Filename (string) from string "VESUVIO38898": When setting value of property "Filename": File "VESUVIO38898" not found
      at line 152 in '/home/3y9/Mantid/mantid/Framework/PythonInterface/plugins/algorithms/LoadVesuvio.py'
      caused by line 232 in '/home/3y9/Mantid/mantid/Framework/PythonInterface/plugins/algorithms/LoadVesuvio.py'
      caused by line 542 in '/home/3y9/Mantid/mantid/Framework/PythonInterface/plugins/algorithms/LoadVesuvio.py'
      caused by line 576 in '/home/3y9/Mantid/mantid/Framework/PythonInterface/plugins/algorithms/LoadVesuvio.py'
      caused by line 281 in '/home/3y9/Mantid/mantid/Framework/PythonInterface/plugins/algorithms/LoadVesuvio.py'
      at line 224 in '/home/3y9/Mantid/mantid/Framework/PythonInterface/plugins/algorithms/VesuvioAnalysis.py'
      caused by line 1120 in '/home/3y9/Mantid/mantid/Framework/PythonInterface/mantid/simpleapi.py'
**********************************************************************
```
```
Document: algorithms/VesuvioDiffractionReduction-v1
---------------------------------------------------
**********************************************************************
File "algorithms/VesuvioDiffractionReduction-v1.rst", line 65, in ExVesuvioDiffractionReductionSimple
Failed example:
    VesuvioDiffractionReduction(InputFiles='15289',
                            OutputWorkspace='DiffractionReductions',
                            InstrumentParFile='IP0005.dat')

    ws = mtd['DiffractionReductions'].getItem(0)

    print('Workspace name: %s' % ws.name())
    print('Number of spectra: %d' % ws.getNumberHistograms())
    print('Number of bins: %s' % ws.blocksize())
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.8/doctest.py", line 1329, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest ExVesuvioDiffractionReductionSimple[0]>", line 1, in <module>
        VesuvioDiffractionReduction(InputFiles='15289',
      File "/home/3y9/Mantid/mantid/Framework/PythonInterface/mantid/simpleapi.py", line 1120, in __call__
        algm.execute()
    RuntimeError: Invalid value for property Filename (string) from string "EVS15289": When setting value of property "Filename": File "EVS15289" not found
      at line 154 in '/home/3y9/Mantid/mantid/Framework/PythonInterface/plugins/algorithms/LoadVesuvio.py'
      caused by line 316 in '/home/3y9/Mantid/mantid/Framework/PythonInterface/plugins/algorithms/LoadVesuvio.py'
      caused by line 409 in '/home/3y9/Mantid/mantid/Framework/PythonInterface/plugins/algorithms/LoadVesuvio.py'
      caused by line 281 in '/home/3y9/Mantid/mantid/Framework/PythonInterface/plugins/algorithms/LoadVesuvio.py'
      at line 113 in '/home/3y9/Mantid/mantid/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/VesuvioDiffractionReduction.py'
      caused by line 108 in '/home/3y9/Mantid/mantid/scripts/Inelastic/IndirectReductionCommon.py'
      caused by line 153 in '/home/3y9/Mantid/mantid/scripts/Inelastic/IndirectReductionCommon.py'
      caused by line 196 in '/home/3y9/Mantid/mantid/scripts/Inelastic/IndirectReductionCommon.py'
      caused by line 1120 in '/home/3y9/Mantid/mantid/Framework/PythonInterface/mantid/simpleapi.py'
**********************************************************************
```

```
--------------------------------------------
**********************************************************************
File "algorithms/SaveMDWorkspaceToVTK-v1.rst", line 49, in SaveMDWorkspaceToVTK
Failed example:
    import os
    signalInput = [i for i in range(1,28)]
    errorInput = [1 for i in range(1,28)]

    ws = CreateMDHistoWorkspace(SignalInput=signalInput, ErrorInput=errorInput, Dimensionality='3',
                                Extents='-1,1,-1,1,-1,1', NumberOfBins='3,3,3', Names='A,B,C', Units='U,T,W')

    ws2 = CreateMDHistoWorkspace(SignalInput='1,2,3,4,5,6,7,8,9', ErrorInput='1,1,1,1,1,1,1,1,1', Dimensionality='2',
                                Extents='-1,1,-1,1', NumberOfBins='3,3', Names='A,B', Units='U,T')

    savefile = os.path.join(config["defaultsave.directory"], "mdhws.vts")
    SaveMDWorkspaceToVTK(InputWorkspace = ws, Filename = savefile)

    print("File created: {}".format(os.path.exists(savefile)))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.8/doctest.py", line 1329, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest SaveMDWorkspaceToVTK[0]>", line 12, in <module>
        SaveMDWorkspaceToVTK(InputWorkspace = ws, Filename = savefile)
    NameError: name 'SaveMDWorkspaceToVTK' is not defined
**********************************************************************
File "algorithms/SaveMDWorkspaceToVTK-v1.rst", line 47, in SaveMDWorkspaceToVTK (cleanup code)
Failed example:
    os.remove(savefile)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.8/doctest.py", line 1329, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest SaveMDWorkspaceToVTK (cleanup code)[0]>", line 1, in <module>
        os.remove(savefile)
    FileNotFoundError: [Errno 2] No such file or directory: 'mdhws.vts'
**********************************************************************
```

```Document: algorithms/GeneratePeaks-v1
-------------------------------------
**********************************************************************
File "algorithms/GeneratePeaks-v1.rst", line 195, in GeneratePeakFromTable
Failed example:
    # Create an input Tableworkspace by FindPeaks
    Load(Filename='focussed.nxs', OutputWorkspace='focussed', LoaderName='LoadNexusProcessed',
      LoaderVersion=1, LoadHistory=False)
    FindPeaks(InputWorkspace='focussed', WorkspaceIndex=3, BackgroundType='Quadratic', PeaksList='PeakList3')

    # Geneate peaks
    GeneratePeaks(PeakParametersWorkspace='PeakList3', PeakType='Gaussian', BackgroundType='Quadratic',
          InputWorkspace='focussed', NumberWidths=5, OutputWorkspace='GaussianPeak', IsRawParameter=False)

    # Print
    outws = mtd["GaussianPeak"]
    vecx3 = outws.readX(3)
    vecy3 = outws.readY(3)
    for i in range(4277, 4283):
      print("X = {:.6f}, Y = {:.6f}".format(vecx3[i], vecy3[i]))
Expected:
    X = 2.137026, Y = 24074.469544
    X = 2.139414, Y = 25091.516123
    X = 2.141805, Y = 25481.643702
    X = 2.144199, Y = 25120.243602
    X = 2.146595, Y = 24105.695010
    X = 2.148994, Y = 22713.122811
Got:
    X = 2.137026, Y = 24692.730153
    X = 2.139414, Y = 25425.651107
    X = 2.141805, Y = 25417.044545
    X = 2.144199, Y = 24659.364905
    X = 2.146595, Y = 23373.017425
    X = 2.148994, Y = 21899.242668
1 items passed all tests:
   1 tests in GeneratePeakFromArray
**********************************************************************
```
```
Document: algorithms/SANSILLParameterScan-v1
--------------------------------------------
**********************************************************************
File "algorithms/SANSILLParameterScan-v1.rst", line 53, in ExSANSILLParameterScan
Failed example:
    # reduce part of an omega scan on D16.
    SANSILLParameterScan(SampleRuns="023583:023585",
                         OutputWorkspace="output2d",
                         OutputJoinedWorkspace="reduced",
                         Observable="Omega.value",
                         PixelYmin=3,
                         PixelYMax=317)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.8/doctest.py", line 1329, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest ExSANSILLParameterScan[0]>", line 2, in <module>
        SANSILLParameterScan(SampleRuns="023583:023585",
      File "/home/3y9/Mantid/mantid/Framework/PythonInterface/mantid/simpleapi.py", line 1118, in __call__
        set_properties(algm, *args, **final_keywords)
      File "/home/3y9/Mantid/mantid/Framework/PythonInterface/mantid/simpleapi.py", line 1036, in set_properties
        do_set_property(key, value)
      File "/home/3y9/Mantid/mantid/Framework/PythonInterface/mantid/simpleapi.py", line 1019, in do_set_property
        alg_object.setProperty(key, new_value)
    ValueError: Invalid value for property SampleRuns (list of str lists) from string "023583:023585": Unable to find file matching the string "CNCS_23583", please check the data search directories.
**********************************************************************
```

### Steps to reproduce the behavior
Note that I am building on Ubuntu 20.04, no MantidPlot, no Paraview (so no `MAKE_VATES`)

For running tests, I have my facility set to SNS, and default instrument CNCS.

### Platforms affected
Ubuntu 20.04

**Comment by AndreiSavici** [comment]
Note that I had to run `export QT_API=pyqt5` before running the documentation build
