### ISSUE TITLE
Workbench crashes when trying to delete peaks from IPeakTable

### ISSUE THREAD

**Issue by KedoKudo** [mantidproject/mantid#29776]
### Expected behavior
When inspecting data of an IPeaksTable, one should be able to delete an a peak by selecting the row, then use the `detele row` option from the context menu to delete the entire entry of the peak.

### Actual behavior
Mantid workbench will crash when trying to use `Delete Row`.

### Steps to reproduce the behavior
* Start MantidWorkbench
* Use `LoadIsawPeaks` to load a testing data set , [TOPAZ_1204.zip](https://github.com/mantidproject/mantid/files/5411511/TOPAZ_1204.zip)
* Right click on the workspace to open the context menu, then select `show data`
* Right click on the left most border to select an entire row (peak), then right-click to open the context menu, select `Delete Row`
* Mantid will crash with the following error messages.

```python
Python-[Error] Traceback (most recent call last):
  File "/home/user/Mantid/mantid/qt/python/mantidqt/widgets/workspacedisplay/table/presenter.py", line 182, in handleItemChanged
    item.is_v3d)
AttributeError: 'QStandardItem' object has no attribute 'is_v3d'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/Mantid/mantid/qt/python/mantidqt/widgets/workspacedisplay/table/presenter.py", line 187, in handleItemChanged
    item.reset()
AttributeError: 'QStandardItem' object has no attribute 'reset'
```

### Platforms affected
All platforms affected.

**Comment by KedoKudo** [comment]
The original report of this issue is located at https://code.ornl.gov/sns-hfir-scse/spectroscopy/spectroscopy/-/issues/26
