### ISSUE TITLE
SANS Save Other unhandled exception

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#30298]
**Original reporter:** Richard Heenan

### Expected behavior
After processing data on the ISIS SANS gui, using the "Save other" option at the bottom of the gui works as expected to save out workspaces to file
### Actual behavior
Broken with this stacktrace:
```
Traceback (most recent call last):
 File "C:\MantidNightlyInstall\scripts\Interface\ui\sans_isis\SANSSaveOtherWindow.py", line 72, in on_save_clicked
   subscriber.on_save_clicked()
 File "C:\MantidNightlyInstall\scripts\SANS\sans\gui_logic\presenter\save_other_presenter.py", line 46, in on_save_clicked
   save_workspace_to_file(name_to_save, file_formats, filename)
TypeError: save_workspace_to_file() missing 1 required positional argument: 'additional_run_numbers'
```
### Steps to reproduce the behavior
- Process some data, such as the loqdemo from TrainingCourseData
- Click save other and try to save some workspaces to file (specifically it was a group of transmission workspaces, but I think the problem is more general.)
- Saving with the tickboxes in the gui while processing and using the saveRKH algorithm works fine.

### Platforms affected
Found on nightly before release 6.0, but has been broken in 5.1 and 5.0.

**Comment by DanielMurphy22** [comment]
It looks like there are more required input params to the save_workspace_to_file() function than provided on the line in the stacktrace. A correct implementation of this function can be found here: https://github.com/mantidproject/mantid/blob/7e2959eacd2bab93dd2ae082492699a19174826f/scripts/SANS/sans/algorithm_detail/batch_execution.py#L1189-L1192
