### ISSUE TITLE
Sliceviewer exception when changing peaks workspace when overlaid

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#30308]
### Expected behavior
Having overlaid a peaks workspace in sliceviewer, if the peaks workspace were to change (e.g. integrated again with different radius) then the table and plot in the sliceviewer would be updated. Or at least the peaks workspace removed from sliceviewer.

### Actual behavior
The table and plot are not updated and when the user clicks on a peak in the table there is an unexpected exception
```
Traceback (most recent call last):
  File "C:\MantidNightlyInstall\bin\mantidqt\widgets\sliceviewer\peaksviewer\view.py", line 166, in _on_row_clicked
    self._row_selected()
  File "C:\MantidNightlyInstall\bin\mantidqt\widgets\sliceviewer\peaksviewer\view.py", line 172, in _row_selected
    self._presenter.notify(self._presenter.Event.PeakSelected)
  File "C:\MantidNightlyInstall\bin\mantidqt\widgets\sliceviewer\peaksviewer\presenter.py", line 89, in notify
    self._peak_selected()
  File "C:\MantidNightlyInstall\bin\mantidqt\widgets\sliceviewer\peaksviewer\presenter.py", line 123, in _peak_selected
    self._view.set_slicepoint(self.model.slicepoint(selected_index, self._view.sliceinfo))
  File "C:\MantidNightlyInstall\bin\mantidqt\widgets\sliceviewer\peaksviewer\model.py", line 90, in slicepoint
    peak = self.ws.getPeak(selected_index)
RuntimeError: Variable invalidated, data has been deleted.
```
### Steps to reproduce the behavior
For example
(1) Load in MD data and peak workspace
(2) Overlay peaks workspace
(3) Integrate the workspace using IntegratePeaksMD

### Platforms affected
found on unscripted testing of  workbench nightly install from 07/01/21

**Comment by martyngigg** [comment]
Fixed by #30375
