### ISSUE TITLE
ISIS SANS: Browse button in sum runs causes exception

### ISSUE THREAD

**Issue by StephenSmith25** [mantidproject/mantid#30303]
### Expected behavior
Exiting the browse option without selecting any files should not produce an error.
### Actual behavior
It produces an unhandled exception
### Steps to reproduce the behavior

1. Open the ISIS SANS GUI
2. Go to sum runs
3. Click browse
4. Click cancel
5. You should get an unexpected exception error message

```
Traceback (most recent call last):
  File "C:\Users`Documents\mantid\mantid\scripts\SANS\sans\gui_logic\presenter\RunSelectorPresenter.py", line 75, in _handle_browse
    file_paths = self.view.show_file_picker(RunSelectorPresenter.file_extensions,
  File "C:\Users\Documents\mantid\mantid\scripts\Interface\ui\sans_isis\run_selector_widget.py", line 40, in show_file_picker
    self._store_previous_directory(previous_directories, chosen_files[0])
  File "C:\Users\Documents\mantid\mantid\scripts\Interface\ui\sans_isis\run_selector_widget.py", line 52, in _store_previous_directory
    previous_file = QFileInfo(path)
TypeError: arguments did not match any overloaded call:
  QFileInfo(): too many arguments
  QFileInfo(str): argument 1 has unexpected type 'list'
  QFileInfo(QFile): argument 1 has unexpected type 'list'
  QFileInfo(QDir, str): argument 1 has unexpected type 'list'
  QFileInfo(QFileInfo): argument 1 has unexpected type 'list'

```
### Platforms affected
All

**Comment by StephenSmith25** [comment]
Tested on windows: Found two issues 

#30306
#30303

**Comment by gemmaguest** [comment]
This has been reported before but for some reason I thought that was fixed. I can reproduce it again now, though. It's been a problem in workbench for some time. I also get the exception when selecting a file.
