### ISSUE TITLE
Edit Legend in-situ on Linux

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#30304]
This seems to have not worked on IDAaaS in the initial implementation: https://github.com/mantidproject/mantid/pull/29217
### Expected behavior
Edit legend in situ works.
### Actual behavior
On IDAaaS this doesn't, presumably because Workbench on Linux uses an older version of matplotlib.
### Steps to reproduce the behavior
- Open IDAaaS instance
- Plot any data
- Double click on a legend entry to edit it
```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/matplotlib/cbook/__init__.py", line 387, in process
    proxy(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/matplotlib/cbook/__init__.py", line 227, in __call__
    return mtd(*args, **kwargs)
  File "/opt/mantidnightly/lib/workbench/plotting/figureinteraction.py", line 158, in on_mouse_button_press
    self._show_axis_editor(event)
  File "/opt/mantidnightly/lib/workbench/plotting/figureinteraction.py", line 261, in _show_axis_editor
    ax.get_legend().set_draggable(False)
AttributeError: 'Legend' object has no attribute 'set_draggable'
```
### Platforms affected
Linux, IDAaaS 5.1.1 and nightly before 6.0

**Comment by StephenSmith25** [comment]
Fixed by #30346
