### ISSUE TITLE
Error/Crash when using Slice Viewer on a workspace from FFT

### ISSUE THREAD

**Issue by joseph-torsney** [mantidproject/mantid#30344]
### Expected behavior
When using the Slice Viewer on a workspace that is the output of an FFT, Slice Viewer should not cause an error when interacting with the plot.

### Actual behavior
The following stacktrace is reported in the messages pane:
```
IndexError: invalid vector subscript
Traceback (most recent call last):
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\backends\backend_qt5.py", line 506, in _draw_idle
    self.draw()
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\backends\backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\figure.py", line 1708, in draw
    mimage._draw_list_compositing_images(
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\axes\_base.py", line 2647, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\MantidNightlyInstall\bin\mantid\plots\resampling_image\samplingimage.py", line 72, in draw
    self._resample_image()
  File "C:\MantidNightlyInstall\bin\mantid\plots\resampling_image\samplingimage.py", line 109, in _resample_image
    x, y, data = get_matrix_2d_ragged(self.ws,
  File "C:\MantidNightlyInstall\bin\mantid\plots\datafunctions.py", line 519, in get_matrix_2d_ragged
    counts = interpolate_y_data(workspace, x_centers, y, normalize_by_bin_width, spectrum_info=spec_info,
  File "C:\MantidNightlyInstall\bin\mantid\plots\datafunctions.py", line 593, in interpolate_y_data
    if not (spectrum_info and spectrum_info.hasDetectors(workspace_index) and spectrum_info.isMonitor(
IndexError: invalid vector subscript
```

Only once have I found this to cause a sad mantid.

### Steps to reproduce the behavior
1. Run the following script:
```
ws = CreateSampleWorkspace(OutputWorkspace='ws')
ws = FFT(ws, AutoShift=True)
```
2. Open sliceviewer and manipulate the plot (zoom in and out, pan around) until the exception occurs.

### Platforms affected
Tested on Windows

**Comment by Harrietbrown** [comment]
Fixed by #30380
