### ISSUE TITLE
Sliceviewer unzoom to box on 2D data 

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#30677]
<!-- If the issue was raised by a user they should be named here.
**Original reporter:** @MathieuTillet https://github.com/mantidproject/mantid/issues/30653#issuecomment-776537062

### Expected behavior
Zoom out on sliceviewer, by right-clicking and dragging to some box size, should work with no errors.
### Actual behavior
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/cbook/__init__.py", line 388, in process
    proxy(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/cbook/__init__.py", line 228, in __call__
    return mtd(*args, **kwargs)
  File "/opt/Mantid/lib/mantidqt/widgets/sliceviewer/cursor.py", line 65, in on_mouse_move
    self.on_cursor_at(xdata, ydata)
  File "/opt/Mantid/lib/mantidqt/widgets/sliceviewer/imageinfowidget.py", line 66, in _on_cursor_at_axesimage
    self._widget.cursorAt(xdata, ydata, arr[i, j])
RuntimeError: indexOfValue - value out of range
```
I suspect the error message is only seen on Ubbuntu as it's Matplotlib version is behind Windows+MacOS.

### Steps to reproduce the behavior
- Load some 2D data (not MD data!), such as `Training_Exercise3a_SNS.nxs` from the TrainingCourseData.
- Open Sliceviewer.
- Zoom out of the plotted image by right-clicking and dragging out to a box. (like how you would zoom in on a region, but instead right-clicking)
### Platforms affected
Ubuntu, probably all Linux, found on release candidate for 6.0

**Comment by thomashampson** [comment]
This may be resolved by fixing #31266
