### ISSUE TITLE
Project Save Encoder tests for EngDiff UI throws error after success

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#31012]
The encoder tests  in
C:\mantid\scripts\Engineering\gui\engineering_diffraction\test\engineering_diffraction_io_test.py

Seem to pass alright but throw an error after the test - perhaps indicating a tearDown method is required?
```
----------------------------------------------------------------------
Ran 5 tests in 4.301s

OK
Error occurred in handler:
Traceback (most recent call last):
  File "C:\mantid\scripts\Engineering\gui\engineering_diffraction\tabs\fitting\fitting_ads_observer.py", line 20, in wrapper
    func(*args, **kwargs)
  File "C:\mantid\scripts\Engineering\gui\engineering_diffraction\tabs\fitting\fitting_ads_observer.py", line 65, in clearHandle
    self.clear_callback()
  File "C:\mantid\scripts\Engineering\gui\engineering_diffraction\tabs\fitting\data_handling\data_widget.py", line 37, in clear_workspaces
    self.presenter.clear_workspaces()
  File "C:\mantid\scripts\Engineering\gui\engineering_diffraction\tabs\fitting\data_handling\data_presenter.py", line 91, in clear_workspaces
    self._repopulate_table()
  File "C:\mantid\scripts\Engineering\gui\engineering_diffraction\tabs\fitting\data_handling\data_presenter.py", line 131, in _repopulate_table
    self._remove_all_table_rows()
  File "C:\mantid\scripts\Engineering\gui\engineering_diffraction\tabs\fitting\data_handling\data_presenter.py", line 284, in _remove_all_table_rows
    self.view.remove_all()
  File "C:\mantid\scripts\Engineering\gui\engineering_diffraction\tabs\fitting\data_handling\data_view.py", line 137, in remove_all
    self.table_selection.setRowCount(0)
RuntimeError: wrapped C/C++ object of type QTableWidget has been deleted
Error occurred in handler:
Traceback (most recent call last):
  File "C:\mantid\scripts\Engineering\gui\engineering_diffraction\tabs\fitting\fitting_ads_observer.py", line 20, in wrapper
    func(*args, **kwargs)
  File "C:\mantid\scripts\Engineering\gui\engineering_diffraction\tabs\fitting\fitting_ads_observer.py", line 65, in clearHandle
    self.clear_callback()
  File "C:\mantid\scripts\Engineering\gui\engineering_diffraction\tabs\fitting\data_handling\data_widget.py", line 37, in clear_workspaces
    self.presenter.clear_workspaces()
  File "C:\mantid\scripts\Engineering\gui\engineering_diffraction\tabs\fitting\data_handling\data_presenter.py", line 91, in clear_workspaces
    self._repopulate_table()
  File "C:\mantid\scripts\Engineering\gui\engineering_diffraction\tabs\fitting\data_handling\data_presenter.py", line 131, in _repopulate_table
    self._remove_all_table_rows()
  File "C:\mantid\scripts\Engineering\gui\engineering_diffraction\tabs\fitting\data_handling\data_presenter.py", line 284, in _remove_all_table_rows
    self.view.remove_all()
  File "C:\mantid\scripts\Engineering\gui\engineering_diffraction\tabs\fitting\data_handling\data_view.py", line 137, in remove_all
    self.table_selection.setRowCount(0)
RuntimeError: wrapped C/C++ object of type QTableWidget has been deleted
```

**Comment by DannyHindson** [comment]
Error seems to come from test_decode_produces_gui_returning_same_dict. If I debug it I get a slightly different error for some reason:
```
Traceback (most recent call last):
  File "C:\mantid\scripts\Engineering\gui\engineering_diffraction\tabs\fitting\plotting\EngDiff_fitpropertybrowser.py", line 146, in function_changed_slot
    super(EngDiffFitPropertyBrowser, self).function_changed_slot()
  File "c:\mantid\qt\python\mantidqt\widgets\fitpropertybrowser\fitpropertybrowser.py", line 483, in function_changed_slot
    peak_ids, peak_updates = self.tool.update_peak_markers(self.peak_ids.keys(),
AttributeError: 'NoneType' object has no attribute 'update_peak_markers'
```
