### ISSUE TITLE
SANS Interface: Load throws an exception if you have input focus in a cell in a new row

### ISSUE THREAD

**Issue by smk78** [mantidproject/mantid#31202]
Discovered testing Mantid Nightly 6.0.20210421.2323 on W10/x64. But probably exists in earlier versions. And probably affects all platforms.

![image](https://user-images.githubusercontent.com/10938679/115858661-25cffe80-a427-11eb-9911-5c42411293ec.png)

If you hit Return/Enter after completing data entry in a row in the Reduction Table in the SANS Interface a new row is automatically created and input focus is given to the cell in this new row in the same column as the one in which Return/Enter was made.

If you click Load at this point - whilst the cell is still editable - an exception is immediately thrown:
```
Traceback (most recent call last):
  File "C:\MantidNightlyInstall\scripts\Interface\ui\sans_isis\sans_data_processor_gui.py", line 465, in _load_clicked
    self._call_settings_listeners(lambda listener: listener.on_load_clicked())
  File "C:\MantidNightlyInstall\scripts\Interface\ui\sans_isis\sans_data_processor_gui.py", line 244, in _call_settings_listeners
    target(listener)
  File "C:\MantidNightlyInstall\scripts\Interface\ui\sans_isis\sans_data_processor_gui.py", line 465, in <lambda>
    self._call_settings_listeners(lambda listener: listener.on_load_clicked())
  File "C:\MantidNightlyInstall\scripts\SANS\sans\gui_logic\presenter\run_tab_presenter.py", line 145, in on_load_clicked
    self._presenter.on_load_clicked()
  File "C:\MantidNightlyInstall\scripts\SANS\sans\gui_logic\presenter\run_tab_presenter.py", line 684, in on_load_clicked
    selected_rows = self._get_selected_non_empty_rows()
  File "C:\MantidNightlyInstall\scripts\SANS\sans\gui_logic\presenter\run_tab_presenter.py", line 655, in _get_selected_non_empty_rows
    to_process = [self._table_model.get_row(i) for i in selected_rows]
  File "C:\MantidNightlyInstall\scripts\SANS\sans\gui_logic\presenter\run_tab_presenter.py", line 655, in <listcomp>
    to_process = [self._table_model.get_row(i) for i in selected_rows]
  File "C:\MantidNightlyInstall\scripts\SANS\sans\gui_logic\models\table_model.py", line 57, in get_row
    return self._table_entries[index]
IndexError: list index out of range
```

This is surprisingly easy to trigger if, for example, you just want to load a new run. You type in a new run number, hit return and then immediately click Load, not realising you don't actually have the row you just typed in selected!

This should be gracefully trapped.

Because the SANS Reduction Table shares code with the Reflectometry Reduction Table, this issue is probably common to both.

**Comment by martyngigg** [comment]
Fixed by #31224
