### ISSUE TITLE
Sliceviewer spectrum axis does not zoom or pan correctly.

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#31266]
### Expected behavior
The 2D plot data should pan and zoom consistently with the axis limits, i.e. the data on the plot should be in the correct position relative to the axes.

### Actual behavior
When panning, the plot data is stretched and compressed in the spectrum axis direction. When zooming, the plot data does not zoom consistently with the spectrum axis range. The time-of-flight axis appears to be fine.

### Steps to reproduce the behavior
- Load a file, e.g. MAR11060.raw from the training course data.
- Open the slice viewer.
- Select the "pan axes" tool.
- Drag the plot upwards.
You will see that the data is stretched and that data is left in negative spectrum space. Hovering the cursor over these negative spectrum values will throw runtime errors, as mentioned in #30677 (related issue).

### Platforms affected
Seen on both windows and linux in Mantid Workbench v6.0 and above.

**Comment by RichardWaiteSTFC** [comment]
I can reproduce this, if you keep on going with the pan you eventually get an empty plot and this error
```
Traceback (most recent call last):
  File "C:\mantid\external\src\ThirdParty\lib\python3.8\lib\site-packages\matplotlib\cbook\__init__.py", line 216, in process
    func(*args, **kwargs)
  File "C:\mantid\qt\python\mantidqt\widgets\sliceviewer\cursor.py", line 65, in on_mouse_move
    self.on_cursor_at(xdata, ydata)
  File "C:\mantid\qt\python\mantidqt\widgets\sliceviewer\imageinfowidget.py", line 66, in _on_cursor_at_axesimage
    self._widget.cursorAt(xdata, ydata, arr[i, j])
RuntimeError: indexOfValue - value out of range
```

**Comment by thomashampson** [comment]
I've edited the issue, since it applies to colorfill plots in general and not just the slice viewer.

**Comment by RichardWaiteSTFC** [comment]
If it affects both colorfills and sliceviewer it might be a bug in here
`C:\mantid\Framework\PythonInterface\mantid\plots\resampling_image\samplingimage.py`
