### ISSUE TITLE
Muon Analysis - Limited validation of the start and end X line edits

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#31505]
### Description
In Muon Analysis and FDA there is an issue with not enough validation of the start and end x.

From Steve:
```
Another issue I’ve come across is connected with the boxes used to define the fit range in the Analysis interface.
 
1.       It seems to be possible to specify a ‘time end’ beyond the end of the data. What happens when this is done?
2.       It seems to be possible to leave ‘time start’ blank, which causes Mantid to bring up the crash window
3.       It seem to be possible to leave ‘time end’ blank … the box stays blank, what happens?
4.       Whether a value as been entered and accepted seems a little indetermined.
```

Also the error reporter shows:
```
 Traceback (most recent call last):
 File "C:\MantidNightlyInstall\scripts\Muon\GUI\Common\fitting_widgets\basic_fitting\basic_fitting_presenter.py", line 219, in handle_end_x_updated
   if self.view.end_x < self.view.start_x:
 File "C:\MantidNightlyInstall\scripts\Muon\GUI\Common\fitting_widgets\basic_fitting\basic_fitting_view.py", line 126, in start_x
   return self.fit_function_options.start_x
 File "C:\MantidNightlyInstall\scripts\Muon\GUI\Common\fitting_widgets\basic_fitting\fit_function_options_view.py", line 147, in start_x
   return float(self.start_x_line_edit.text())
ValueError: could not convert string to float: ''
```

### Platforms affected
All

**Comment by martyngigg** [comment]
Fixed by #31507
