### ISSUE TITLE
Value error setting plot to Log scale

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#31674]
### Expected behavior
- Plotting should handle Log values with NaN

### Actual behavior
- A value error is raised:
```
Traceback (most recent call last):
  File "/Applications/MantidWorkbench.app/Contents/MacOS/mantidqt/widgets/plotconfigdialog/presenter.py", line 72, in apply_properties
    self.fig.canvas.draw()
  File "/Users//Library/Python/3.8/lib/python/site-packages/matplotlib/backends/backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "/Users//Library/Python/3.8/lib/python/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users//Library/Python/3.8/lib/python/site-packages/matplotlib/figure.py", line 1708, in draw
    mimage._draw_list_compositing_images(
  File "/Users//Library/Python/3.8/lib/python/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users//Library/Python/3.8/lib/python/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users//Library/Python/3.8/lib/python/site-packages/matplotlib/axes/_base.py", line 2647, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/Users//Library/Python/3.8/lib/python/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Applications/MantidWorkbench.app/Contents/MacOS/mantid/plots/resampling_image/samplingimage.py", line 72, in draw
    self._resample_image()
  File "/Applications/MantidWorkbench.app/Contents/MacOS/mantid/plots/resampling_image/samplingimage.py", line 107, in _resample_image
    xbins, ybins = self._calculate_bins_from_extent()
  File "/Applications/MantidWorkbench.app/Contents/MacOS/mantid/plots/resampling_image/samplingimage.py", line 98, in _calculate_bins_from_extent
    xbins = int(np.ceil(bbox.width * dpi))
ValueError: cannot convert float NaN to integer
```

### Steps to reproduce the behavior
- Load MAR11015
- Color fill plot
- Right click bar on the right, and set axis to Log

### Platforms affected
All

**Comment by thomashampson** [comment]
I can't access the option via a right click menu, but double clicking the plot and setting LogIt on the axis tab will cause the same error.
![image](https://user-images.githubusercontent.com/8058899/152998205-5b96d1d7-39bc-41a7-b359-3b84ce821a49.png)
