### ISSUE TITLE
test_interpreter fails frequntly on linux

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#31983]
projectroot.qt.python.mantidqt_qt5.test_interpreter.test_interpreter has been failing frequently on linux systems, see for example:
https://builds.mantidproject.org/job/pull_requests-ubuntu/46183/
https://builds.mantidproject.org/job/pull_requests-rhel7/44591/

Stack trace:

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-abc'
/jenkins_workdir/workspace/pull_requests-ubuntu/build/bin/site.py:26: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp  # Avoid import loop in Python >= 3.3
........Traceback (most recent call last):
  File "/jenkins_workdir/workspace/pull_requests-ubuntu/qt/python/mantidqt/widgets/codeeditor/completion.py", line 268, in update_completion_api
    self.editor.updateCompletionAPI(self.completions)
RuntimeError: wrapped C/C++ object of type ScriptEditor has been deleted
this is a string
this is a string

**Comment by thomashampson** [comment]
Related error report:
```
Name: Not provided  Email: Not provided
       Additional text:
       Not provided
       Stack Trace:
       Traceback (most recent call last):
 File "/opt/mantid51/lib/mantidqt/widgets/codeeditor/interpreter.py", line 363, in _on_exec_error
   self.view.editor.updateProgressMarker(lineno, True)
RuntimeError: wrapped C/C++ object of type ScriptEditor has been deleted
       Using: workbench 5.1.0 on Red Hat Enterprise Linux
```
