### ISSUE TITLE
Crash when run LoadInstrument as live data postprocessing algorithm

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#32313]
**Describe the bug**
Mantid crashes if you run live data with LoadInstrument as a postprocessing algorithm.

**To Reproduce**

For example
1. Set the facility to TEST_LIVE
2. Run the algorithm FakeISISHistoDAE with default settings
3. Click Load->Live data
4. Set the instrument to ISIS_Histogram and set an output name e.g. `live`
5. Select the postprocessing `Algorithm` radio button and on the postprocessing tab select `LoadInstrument`. Set the workspace name to `live` and the instrument to e.g. `INTER` and RewriteSpectraMap to False.
6. Click Run.

**Expected behavior**
Mantid should load the live data and then run LoadInstrument on the `live` workspace without crashing. This works ok if you run load live data without a postprocessing step and then run LoadInstrument on the resulting workspace separately.

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: Ubuntu
 - OS Version: 18.04
 - Mantid Version: 6.1.20210824.1853

**Additional context**
According to the stacktrace it seems to be related to sliceviewer:
```
Traceback (most recent call last):
  File "/home/gemma/work/checkout/mantid/qt/applications/workbench/workbench/app/start.py", line 198, in start
    exit_value = start_workbench(app, options)
  File "/home/gemma/work/checkout/mantid/qt/applications/workbench/workbench/app/start.py", line 133, in start_workbench
    main_window.setup()
  File "/home/gemma/work/checkout/mantid/qt/applications/workbench/workbench/app/mainwindow.py", line 178, in setup
    from workbench.plugins.workspacewidget import WorkspaceWidget
  File "/home/gemma/work/checkout/mantid/qt/applications/workbench/workbench/plugins/workspacewidget.py", line 22, in <module>
    from mantidqt.widgets.sliceviewer.presenter import SliceViewer
  File "/home/gemma/work/checkout/mantid/qt/python/mantidqt/widgets/sliceviewer/presenter.py", line 18, in <module>
    from .model import SliceViewerModel, WS_TYPE
  File "/home/gemma/work/checkout/mantid/qt/python/mantidqt/widgets/sliceviewer/model.py", line 15, in <module>
    from mantid.simpleapi import BinMD, IntegrateMDHistoWorkspace, TransposeMD
ImportError: cannot import name 'BinMD'
```

**Comment by martyngigg** [comment]
Fixed by #32337
