### ISSUE TITLE
Clearing workspaces while saving project causes error

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#32361]
**Describe the bug**
If workspaces are cleared during a project save operation, the save will fail and the error reporter will pop up with something like:
```
Traceback (most recent call last):
  File "C:\MantidNightlyInstall\bin\mantidqt\widgets\saveprojectdialog\presenter.py", line 66, in save_as
    self.project.save_as(path=self.view.get_location())
  File "C:\MantidNightlyInstall\bin\mantidqt\project\project.py", line 108, in save_as
    task.start()
  File "C:\MantidNightlyInstall\bin\mantidqt\utils\asynchronous.py", line 151, in start
    raise self.recv.exc_value
  File "C:\MantidNightlyInstall\bin\mantidqt\utils\asynchronous.py", line 65, in run
    out = self.target(*self.args, **self.kwargs)
  File "C:\MantidNightlyInstall\bin\mantidqt\project\project.py", line 149, in _save
    project_saver.save_project(file_name=self.last_project_location, workspace_to_save=workspaces_to_save,
  File "C:\MantidNightlyInstall\bin\mantidqt\project\projectsaver.py", line 47, in save_project
    workspace_saver.save_workspaces(workspaces_to_save=workspace_to_save)
  File "C:\MantidNightlyInstall\bin\mantidqt\project\workspacesaver.py", line 39, in save_workspaces
    workspace = ADS.retrieve(workspace_name)
KeyError: "'SXD23767' does not exist."
```

**To Reproduce**
For example
1. Run this script (or anything that will make project save take a bit of time to run) to generate some workspaces (assuming the training course data is one of your data search directories):
```
from mantid.simpleapi import *

md_4D = CreateMDWorkspace(Dimensions=4, Extents=[-1,1,-1,1,-1,1,-10,10], Names="H,K,L,E", Frames='HKL,HKL,HKL,General Frame',Units='r.l.u.,r.l.u.,r.l.u.,meV')
FakeMDEventData(InputWorkspace=md_4D, PeakParams='500000,0,0,0,0,3') # 4D data
# Create a histogrammed (binned) workspace with 100 bins in each of the H, K and L dimensions
mdHisto_3D = BinMD(InputWorkspace=md_4D, AlignedDim0='H,-1,1,100', AlignedDim1='K,-1,1,100', AlignedDim2='L,-1,1,100') # 3D cut
mdHisto_2D = BinMD(InputWorkspace=md_4D, AlignedDim0='H,-1,1,100', AlignedDim1='K,-1,1,100') # 2D cut

# SXD23767.raw is available in the TrainingCourseData from the downloads page
SXD23767 = Load(Filename='SXD23767.raw', LoadMonitors='Exclude')
# Set some UB with angles we can play with
SetUB(SXD23767, 1,1,2,90,90,120)
SXD_MD_nonortho = ConvertToDiffractionMDWorkspace(InputWorkspace='SXD23767', OutputDimensions='HKL')
```
2. Click File>Save Project as...
3. Choose a file name and click OK.
4. **QUICKLY** click "Clear" in the workspace widget and press Yes too accept the dialog.
5. Wait a bit.
6. The error reporter will pop up and the save operation will fail.

**Expected behavior**
The user should not be allowed to delete workspaces that are being saved. Or a dialog sohuld warn the user that the save operation will be cancelled, and it should be cancelled if the user chooses to continue to clear workspaces.

**Platform/Version (please complete the following information):**
 - OS: All
 - Mantid Version 6.1

**Comment by thomashampson** [comment]
We've seen this in the error reports channel, so I'm re-opening.
