### ISSUE TITLE
Uncaught exception trying to plot bins with different X,Y dims

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#32649]
Noticed whilst testing #32551 
**Describe the bug**
The following uncaught exception is thrown:

```
Traceback (most recent call last):
  File "/home/david/mantid/qt/applications/workbench/workbench/plugins/workspacewidget.py", line 196, in _do_plot_bin
    plot(self._ads.retrieveWorkspaces(names, unrollGroups=True),
  File "/home/david/mantid/Framework/PythonInterface/mantid/plots/plotfunctions.py", line 61, in inner_func
    return func(workspaces, *args, **kwargs)
  File "/home/david/mantid/Framework/PythonInterface/mantid/plots/plotfunctions.py", line 186, in plot
    _do_single_plot(ax, workspaces, errors, show_title, nums, kw, plot_kwargs, log_name, log_values)
  File "/home/david/mantid/Framework/PythonInterface/mantid/plots/plotfunctions.py", line 528, in _do_single_plot
    plot_fn(ws, **plot_kwargs)
  File "/home/david/mantid/Framework/PythonInterface/mantid/plots/mantidaxes.py", line 43, in wrapper
    func_value = func(self, *args, **kwargs)
  File "/home/david/mantid/Framework/PythonInterface/mantid/plots/mantidaxes.py", line 674, in plot
    axesfunctions.plot(self, normalize_by_bin_width=is_normalized,
  File "/home/david/mantid/Framework/PythonInterface/mantid/plots/axesfunctions.py", line 225, in plot
    return axes.plot(x, y, *args, **kwargs)
  File "/home/david/mantid/Framework/PythonInterface/mantid/plots/mantidaxes.py", line 43, in wrapper
    func_value = func(self, *args, **kwargs)
  File "/home/david/mantid/Framework/PythonInterface/mantid/plots/mantidaxes.py", line 683, in plot
    return Axes.plot(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/axes/_axes.py", line 1665, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/usr/lib/python3/dist-packages/matplotlib/axes/_base.py", line 225, in __call__
    yield from self._plot_args(this, kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/axes/_base.py", line 391, in _plot_args
    x, y = self._xy_from_xy(x, y)
  File "/usr/lib/python3/dist-packages/matplotlib/axes/_base.py", line 269, in _xy_from_xy
    raise ValueError("x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (102402,) and (102400,)
```

**To Reproduce**
- Open [repro.nxs.zip](https://github.com/mantidproject/mantid/files/7243983/repro.nxs.zip)
- Plot bins

**Comment by DavidFair** [comment]
Duplicate of #32552
