### ISSUE TITLE
Sliceviewer should not Rebin on Zoom where mdhisto_was_modified=True

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#33104]
**Original reporter:** Jonathan Morris

**Describe the bug**
After subtracting 2 MDhisto workspaces, it isn't valid to rebin the data. Sliceviewer still attempts to run BinMD when such data is zoomed into.

**To Reproduce**
Run this script which creates some MDhisto data and runs MinusMD to subtract 2MDhisto workspaces.
``` python
from mantid.simpleapi import *

Load(Filename='SXD23767.raw', OutputWorkspace='SXD23767', LoaderName='LoadRaw', LoaderVersion='3', LoadMonitors='Exclude')
SetUB(Workspace='SXD23767', c='2', gamma='120')
ConvertToDiffractionMDWorkspace(InputWorkspace='SXD23767', OutputWorkspace='SXD_MD_nonortho', OutputDimensions='HKL')
BinMD(InputWorkspace='SXD_MD_nonortho', AxisAligned=False,
    BasisVector0='[H,0,0],in 7.255 A^-1,1.0,0.0,0.0', 
    BasisVector1='[0,K,0],in 7.255 A^-1,0.0,1.0,0.0', 
    BasisVector2='[0,0,L],in 3.142 A^-1,0.0,0.0,1.0', 
    OutputExtents='-0.3609,5.0277,-2.6936,2.6936,-2.103,-2.003', 
    OutputBins='100,100,100', NormalizeBasisVectors=False, OutputWorkspace='MD_svrebinned')
    
ws = mtd['MD_svrebinned']
ws2 = ws * 1.5
ws3 = ws2 - ws
```

Right-click on `ws3` and open in sliceviewer. Then try to zoom in on the data. An error reporter appears, sliceviewer closes and the following errormessage is printed:

```
Traceback (most recent call last):
  File "/home/danielmurphy/mantid/qt/python/mantidqt/mantidqt/widgets/sliceviewer/view.py", line 435, in on_data_limits_changed
    self.presenter.data_limits_changed()
  File "/home/danielmurphy/mantid/qt/python/mantidqt/mantidqt/widgets/sliceviewer/presenter.py", line 226, in data_limits_changed
    self.new_plot()  # automatically uses current display limits
  File "/home/danielmurphy/mantid/qt/python/mantidqt/mantidqt/widgets/sliceviewer/presenter.py", line 101, in new_plot_MDH
    self.new_plot_MDE(dimensions_transposing, dimensions_changing)
  File "/home/danielmurphy/mantid/qt/python/mantidqt/mantidqt/widgets/sliceviewer/presenter.py", line 126, in new_plot_MDE
    dimension_indices=dimension_indices))
  File "/home/danielmurphy/mantid/qt/python/mantidqt/mantidqt/widgets/sliceviewer/model.py", line 163, in get_ws_MDE
    binned = BinMD(InputWorkspace=workspace, OutputWorkspace=self._rebinned_name, **params)
  File "/home/danielmurphy/mantid/Framework/PythonInterface/mantid/simpleapi.py", line 1065, in __call__
    raise RuntimeError(msg) from e
RuntimeError: BinMD-v1: This MDHistoWorkspace was modified by a binary operation (e.g. Plus, Minus). It is not currently possible to rebin a modified MDHistoWorkspace because that requires returning to the original (unmodified) MDEventWorkspace, and so would give incorrect results. Instead, you can use SliceMD and perform operations on the resulting MDEventWorkspaces, which preserve all events. You can override this check by removing the 'mdhisto_was_modified' sample log.
```

**Expected behavior**
The sliceviewer does not attempt to rebin the data on zooming if the `mdhisto_was_modified` sample log is True. 

**Screenshots**
You can tell that Sliceviewer will attempt to rebin on zoom when you open sliceviewer as the bin comboboxes for H and K are visible.

![Screenshot 2021-12-06 at 11 57 00](https://user-images.githubusercontent.com/55980573/144842154-527e81c5-4a53-43f3-8a6d-cb77d3a07c14.png)

**Platform/Version (please complete the following information):**
 - OS: Ubuntu but present on all
 - OS Version: 18.04
 - Mantid Version 6.2 and current main

**Comment by martyngigg** [comment]
Fixed by #33362
