### ISSUE TITLE
TF asymm crash

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#33227]
When using Muon analysis there is crash when trying to do a TF Asymmetry fit. This seems to be related to the shade region.

To reproduce:
1. Load MUSR62260
2. Go to the fitting tab
3. Change to TF asymmetry mode
4. Press fit

```
ConvertToHistogram successful, Duration 0.00 seconds
Traceback (most recent call last):
  File "c:\users\btr75544\work\dev\mantid\qt\python\mantidqtinterfaces\mantidqtinterfaces\Muon\GUI\Common\thread_model.py", line 135, in threadWrapperTearDown
    self.end_slot()
  File "c:\users\btr75544\work\dev\mantid\qt\python\mantidqtinterfaces\mantidqtinterfaces\Muon\GUI\Common\fitting_widgets\basic_fitting\basic_fitting_presenter.py", line 185, in handle_finished
    self.handle_fitting_finished(fit_function, fit_status, fit_chi_squared)
  File "c:\users\btr75544\work\dev\mantid\qt\python\mantidqtinterfaces\mantidqtinterfaces\Muon\GUI\Common\fitting_widgets\basic_fitting\basic_fitting_presenter.py", line 198, in handle_fitting_finished
    self.update_plot_fit()
  File "c:\users\btr75544\work\dev\mantid\qt\python\mantidqtinterfaces\mantidqtinterfaces\Muon\GUI\Common\fitting_widgets\basic_fitting\basic_fitting_presenter.py", line 470, in update_plot_fit
    self.selected_fit_results_changed.notify_subscribers(self.model.get_active_fit_results())
  File "c:\users\btr75544\work\dev\mantid\qt\python\mantidqt\mantidqt\utils\observer_pattern.py", line 99, in notify_subscribers
    Observable.notify_subscribers(self, *args)
  File "c:\users\btr75544\work\dev\mantid\qt\python\mantidqt\mantidqt\utils\observer_pattern.py", line 55, in notify_subscribers
    self.thread_safe_update_call(arg, **kwargs)
  File "c:\users\btr75544\work\dev\mantid\qt\python\mantidqt\mantidqt\utils\qt\qappthreadcall.py", line 47, in __call__
    return self.callee(*args, **kwargs)
  File "c:\users\btr75544\work\dev\mantid\qt\python\mantidqt\mantidqt\utils\observer_pattern.py", line 59, in _notify_subscribers_impl
    observer.update(self, arg, **kwargs)
  File "c:\users\btr75544\work\dev\mantid\qt\python\mantidqt\mantidqt\utils\observer_pattern.py", line 91, in update
    self.callback(arg)
  File "c:\users\btr75544\work\dev\mantid\qt\python\mantidqtinterfaces\mantidqtinterfaces\Muon\GUI\Common\plot_widget\fit_pane\plot_fit_pane_presenter.py", line 51, in handle_plot_selected_fits
    self._figure_presenter.add_shaded_region(fit_workspaces, fit_indices)
  File "c:\users\btr75544\work\dev\mantid\qt\python\mantidqtinterfaces\mantidqtinterfaces\Muon\GUI\Common\plot_widget\plotting_canvas\plotting_canvas_presenter.py", line 142, in add_shaded_region
    self._view.add_shaded_region(workspace_name = name,
  File "c:\users\btr75544\work\dev\mantid\qt\python\mantidqtinterfaces\mantidqtinterfaces\Muon\GUI\Common\plot_widget\plotting_canvas\plotting_canvas_view.py", line 218, in add_shaded_region
    axis = self.fig.axes[axis_number-1]
IndexError: list index out of range
```

**Comment by martyngigg** [comment]
Fixed by #33231
