### ISSUE TITLE
zoom on sliceviewer results in AttributeError: 'SliceViewerCanvas' object has no attribute '_dpi_ratio'`

### ISSUE THREAD

**Issue by thomueller** [mantidproject/mantid#33687]
**Describe the bug**
Trying to zoom in in sliceviewer by drag raises an Attribute Errror for missing attribute _dpi_ratio
**To Reproduce**
open sliceviewer with data in Windows and try to zoom in

`Traceback (most recent call last):
  File "C:\Users\username\mambaforge\envs\mantid-developer\lib\site-packages\matplotlib\cbook\__init__.py", line 287, in process
    func(*args, **kwargs)
  File "C:\Users\username\mambaforge\envs\mantid-developer\lib\site-packages\matplotlib\backend_bases.py", line 3191, in drag_zoom
    self.draw_rubberband(event, x1, y1, x2, y2)
  File "c:\mantidbuild\mantid\qt\python\mantidqt\mantidqt\plotting\mantid_navigation_toolbar.py", line 140, in draw_rubberband
    self.canvas.drawRectangle(rect)
  File "C:\mantidbuild\mantid\qt\applications\workbench\workbench\plotting\mantidfigurecanvas.py", line 47, in drawRectangle
    self._drawRect = [pt / self._dpi_ratio for pt in rect]
  File "C:\mantidbuild\mantid\qt\applications\workbench\workbench\plotting\mantidfigurecanvas.py", line 47, in <listcomp>
    self._drawRect = [pt / self._dpi_ratio for pt in rect]
AttributeError: 'SliceViewerCanvas' object has no attribute '_dpi_ratio'`

**Expected behavior**
zoom in

**Platform/Version (please complete the following information):**
 - OS: Windows 10
 - Mantid Version: 6.3.20220322.955
- matplotlib version: 3.5.1

**Comment by sf1919** [comment]
closed by #33748
