### ISSUE TITLE
Surface plot not opening

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#33731]
**Describe the bug**
Surface plots do not open when using a conda-based build, probably because matplotlib has been upgraded to version 3.5.

```
Traceback (most recent call last):
  File "C:\workdir\mantid_conda_dev\mantid\qt\applications\workbench\workbench\plugins\workspacewidget.py", line 228, in _do_plot_3D
    plot_function(workspaces)
  File "C:\workdir\mantid_conda_dev\mantid\Framework\PythonInterface\mantid\plots\plotfunctions.py", line 61, in inner_func
    return func(workspaces, *args, **kwargs)
  File "c:\workdir\mantid_conda_dev\mantid\qt\python\mantidqt\mantidqt\plotting\functions.py", line 345, in plot_surface
    fig, ax = plt.subplots(subplot_kw={'projection': 'mantid3d'})
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mantid-developer\lib\site-packages\matplotlib\pyplot.py", line 1435, in subplots
    axs = fig.subplots(nrows=nrows, ncols=ncols, sharex=sharex, sharey=sharey,
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mantid-developer\lib\site-packages\matplotlib\figure.py", line 897, in subplots
    axs = gs.subplots(sharex=sharex, sharey=sharey, squeeze=squeeze,
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mantid-developer\lib\site-packages\matplotlib\gridspec.py", line 307, in subplots
    axarr[row, col] = figure.add_subplot(
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mantid-developer\lib\site-packages\matplotlib\figure.py", line 772, in add_subplot
    ax = subplot_class_factory(projection_class)(self, *args, **pkw)
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mantid-developer\lib\site-packages\matplotlib\axes\_subplots.py", line 34, in __init__
    self._axes_class.__init__(self, fig, [0, 0, 1, 1], **kwargs)
  File "C:\workdir\mantid_conda_dev\mantid\Framework\PythonInterface\mantid\plots\mantidaxes.py", line 1297, in __init__
    self.figure.canvas.mpl_disconnect(self._cids[1])
AttributeError: 'MantidAxes3DSubplot' object has no attribute '_cids'
```

**To Reproduce**
1. Open a workspace, e.g. MAR11060 from the training course data
2. Right click the workspace and select Plot->3D->Surface
3. Unhandkled exception

**Expected behavior**
A surface plot is shown as in v6.3.0.

**Platform/Version (please complete the following information):**
 - OS: Conda environment
 - Mantid Version: main branch

**Comment by thomashampson** [comment]
This was already resolved in #33540
