### ISSUE TITLE
MacOS Plotting Smoke Tests  :chart_with_upwards_trend: :bar_chart:

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#34061]
**Before testing**:
- Check this testing issue relates to the OS you will test on.
- If unassigned, please assign yourself as for a normal Github issue.
- Please run these tests on the release package of Mantid; **not a locally built version**.

**Afterwards**:
- Comment below with any issues you came across.
- If no major issues were found, please **close this testing issue**.
- Check the main issue for this OS for other unassigned smoke tests.

If you have any questions please contact the creator of this issue.

 :chart_with_upwards_trend: :bar_chart:

* 1D plotting:[instructions](http://docs.mantidproject.org/nightly/tutorials/mantid_basic_course/loading_and_displaying_data/03_displaying_1D_data.html#displaying-1d-data)
 - [ ] Simple plot 
 - [ ] Another way to plot 
 - [ ] Adding curves to existing plots 
 - [ ] Also, test out [waterfall](https://docs.mantidproject.org/nightly/plotting/WaterfallPlotsHelp.html#waterfall-plots) and [tiled]( https://docs.mantidproject.org/nightly/plotting/1DPlotsHelp.html#tiled-plots)
 - [ ] Check Toolbar buttons

* 2D plotting: [instructions](http://docs.mantidproject.org/nightly/tutorials/mantid_basic_course/loading_and_displaying_data/04_displaying_2D_data.html#displaying-2d-data)
 - [ ] Plot all spectra 
 - [ ] Change colour map 
 - [ ] [Contour plot](https://docs.mantidproject.org/nightly/plotting/ColorfillPlotsHelp.html#contour-plots) (under 3D menu) 
 - [ ] Check Toolbar buttons

* [3D plotting](https://docs.mantidproject.org/nightly/plotting/3DPlotsHelp.html):
 - Load some data eg `LOQ7041` from the ISIS sample data
 - [ ] 3D surface
 - [ ] 3D wire frame  
 - [ ] Check Toolbar buttons

 ## Sliceviewer
 - [ ] Overly long instructions (don't spend  long!) and data [here](https://developer.mantidproject.org/Testing/SliceViewer/SliceViewer.html). In particular try editing the data in a workspace while it is open in Sliceviewer!

**Comment by DanielMurphy22** [comment]
All worked apart from the same error Silke found for generating a script with contour plots:

```
Traceback (most recent call last):
  File "/Applications/MantidWorkbench.app/Contents/Resources/lib/python3.8/site-packages/workbench/plotting/figuremanager.py", line 459, in generate_plot_script_clipboard
    script = generate_script(self.canvas.figure, exclude_headers=True)
  File "/Applications/MantidWorkbench.app/Contents/Resources/lib/python3.8/site-packages/workbench/plotting/plotscriptgenerator/__init__.py", line 79, in generate_script
    colormap_lines, colormap_headers = get_plot_2d_cmd(ax, ax_object_var)  # ax.imshow or pcolormesh
  File "/Applications/MantidWorkbench.app/Contents/Resources/lib/python3.8/site-packages/workbench/plotting/plotscriptgenerator/__init__.py", line 140, in get_plot_2d_cmd
    cmds.extend(generate_plot_2d_command(artist, ax_object_var))
  File "/Applications/MantidWorkbench.app/Contents/Resources/lib/python3.8/site-packages/workbench/plotting/plotscriptgenerator/colorfills.py", line 33, in generate_plot_2d_command
    kwargs = get_plot_command_kwargs(artist)
  File "/Applications/MantidWorkbench.app/Contents/Resources/lib/python3.8/site-packages/workbench/plotting/plotscriptgenerator/colorfills.py", line 77, in get_plot_command_kwargs
    kwargs = _get_plot_command_kwargs_from_colorfill(artist)
  File "/Applications/MantidWorkbench.app/Contents/Resources/lib/python3.8/site-packages/workbench/plotting/plotscriptgenerator/colorfills.py", line 94, in _get_plot_command_kwargs_from_colorfill
    props = {key: artist.properties()[key] for key in PLOT_KWARGS}
  File "/Applications/MantidWorkbench.app/Contents/Resources/lib/python3.8/site-packages/workbench/plotting/plotscriptgenerator/colorfills.py", line 94, in <dictcomp>
    props = {key: artist.properties()[key] for key in PLOT_KWARGS}
AttributeError: 'QuadContourSet' object has no attribute 'properties'
```
