### ISSUE TITLE
MacOS Interface Smoke Tests  :facepalm:

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#34524]
**Before testing**:
- Check this testing issue relates to the OS you will test on.
- If unassigned, please assign yourself as for a normal Github issue.
- Please run these tests on the release package of Mantid; **not a locally built version**.

**Afterwards**:
- Comment below with any issues you came across.
- If no major issues were found, please **close this testing issue**.
- Check the main issue for this OS for other unassigned smoke tests.

If you have any questions please contact the creator of this issue.

 :facepalm:

## ISIS only, if possible, so catalogue access can be tested

- [ ] MantidWorkbench opens without errors or warnings 
- [x] Every option in `Interface` opens a GUI 
- [x] Load some test data 
- [x] Access Catalogue through algorithms (use Facilities account, same as for IDAaaS): [CatalogLogin](https://docs.mantidproject.org/algorithms/CatalogLogin-v1.html) and [CatalogGetDataFiles](https://docs.mantidproject.org/algorithms/CatalogGetDataFiles-v1.html)
- [x] Saving/loading projects works 
 - [ ] Alter preferences in [File > Settings](https://docs.mantidproject.org/nightly/tutorials/mantid_basic_course/useful/01_save_settings.html#settings) and check they are obeyed

**Comment by DanielMurphy22** [comment]
I also see this on MacOS: https://github.com/mantidproject/mantid/issues/34531#issuecomment-1280586058

**Comment by DanielMurphy22** [comment]
If I set in Settings (Preferences) > Plotting > Error Capsize to 3, then plot any data and add errorbars then the capsize is set to 0 (check in figure options)

**Comment by DanielMurphy22** [comment]
I have messed with some plotting settings then tried to plot > Spectrum with errors and get this error:

```
Traceback (most recent call last):
  File "/Users/danielmurphy/mambaforge/envs/daniel_test/lib/python3.8/site-packages/workbench/plugins/workspacewidget.py", line 167, in _do_plot_spectrum
    plot_from_names(names, errors, overplot, advanced=advanced)
  File "/Users/danielmurphy/mambaforge/envs/daniel_test/lib/python3.8/site-packages/mantidqt/plotting/functions.py", line 191, in plot_from_names
    return plot(selection.workspaces, spectrum_nums=selection.spectra,
  File "/Users/danielmurphy/mambaforge/envs/daniel_test/lib/python3.8/site-packages/mantid/plots/plotfunctions.py", line 61, in inner_func
    return func(workspaces, *args, **kwargs)
  File "/Users/danielmurphy/mambaforge/envs/daniel_test/lib/python3.8/site-packages/mantid/plots/plotfunctions.py", line 186, in plot
    _do_single_plot(ax, workspaces, errors, show_title, nums, kw, plot_kwargs, log_name, log_values)
  File "/Users/danielmurphy/mambaforge/envs/daniel_test/lib/python3.8/site-packages/mantid/plots/plotfunctions.py", line 542, in _do_single_plot
    plot_fn(ws, **plot_kwargs)
  File "/Users/danielmurphy/mambaforge/envs/daniel_test/lib/python3.8/site-packages/mantid/plots/mantidaxes.py", line 47, in wrapper
    func_value = func(self, *args, **kwargs)
  File "/Users/danielmurphy/mambaforge/envs/daniel_test/lib/python3.8/site-packages/mantid/plots/mantidaxes.py", line 800, in errorbar
    axesfunctions.errorbar(self, normalize_by_bin_width=is_normalized,
  File "/Users/danielmurphy/mambaforge/envs/daniel_test/lib/python3.8/site-packages/mantid/plots/axesfunctions.py", line 284, in errorbar
    return axes.errorbar(x, y, dy, dx, *args, **kwargs)
  File "/Users/danielmurphy/mambaforge/envs/daniel_test/lib/python3.8/site-packages/mantid/plots/mantidaxes.py", line 47, in wrapper
    func_value = func(self, *args, **kwargs)
  File "/Users/danielmurphy/mambaforge/envs/daniel_test/lib/python3.8/site-packages/mantid/plots/mantidaxes.py", line 806, in errorbar
    errorbar_container =  Axes.errorbar(self, *args, **kwargs)
  File "/Users/danielmurphy/mambaforge/envs/daniel_test/lib/python3.8/site-packages/matplotlib/__init__.py", line 1414, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/Users/danielmurphy/mambaforge/envs/daniel_test/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 3362, in errorbar
    everymask[errorevery] = True
ValueError: slice step cannot be zero

```

**Comment by DanielMurphy22** [comment]
Both setting plot problems existed in the last release!
