### ISSUE TITLE
Mantid fails if bad user alg is imported

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#34543]
```
PluginLoader-[Debug] Loading python plugin C:/Users/BTR75544/Downloads/script_test/script_test/script_test/IndirectImport2.py
Python-[Warning] Failed to load plugin C:/Users/BTR75544/Downloads/script_test/script_test/script_test/IndirectImport2.py.
Error: Traceback (most recent call last):
  File "C:\Users\BTR75544\nightly\MantidInstall\bin\lib\site-packages\mantid\kernel\plugins.py", line 184, in load_from_file
    name, module = load_plugin(filepath)
  File "C:\Users\BTR75544\nightly\MantidInstall\bin\lib\site-packages\mantid\kernel\plugins.py", line 204, in load_plugin
    module = loader.run()
  File "C:\Users\BTR75544\nightly\MantidInstall\bin\lib\site-packages\mantid\kernel\plugins.py", line 49, in run
    return SourceFileLoader(name, pathname).load_module()
  File "<frozen importlib._bootstrap_external>", line 522, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1022, in load_module
  File "<frozen importlib._bootstrap_external>", line 847, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:/Users/BTR75544/Downloads/script_test/script_test/script_test/IndirectImport2.py", line 14, in <module>
    import numpy.core.setup_common as numpy_cfg
  File "C:\Users\BTR75544\nightly\MantidInstall\bin\lib\site-packages\numpy\core\setup_common.py", line 113, in <module>
    with open(pathlib.Path(__file__).parent / file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\BTR75544\\nightly\\MantidInstall\\bin\\lib\\site-packages\\numpy\\core\\feature_detection_locale.h'

PluginLoader-[Debug] Loading python plugin C:/Users/BTR75544/Downloads/script_test/script_test/script_test/__init__.py
PluginLoader-[Debug] Loading python plugin C:/Users/BTR75544/Downloads/script_test/script_test/script_test/python\bayes.py
PluginLoader-[Debug] Loading python plugin C:/Users/BTR75544/Downloads/script_test/script_test/script_test/python\constants.py
PluginLoader-[Debug] Loading python plugin C:/Users/BTR75544/Downloads/script_test/script_test/script_test/python\data.py
PluginLoader-[Debug] Loading python plugin C:/Users/BTR75544/Downloads/script_test/script_test/script_test/python\qldata_main.py
PluginLoader-[Debug] Loading python plugin C:/Users/BTR75544/Downloads/script_test/script_test/script_test/python\qldata_subs.py
PluginLoader-[Debug] Loading python plugin C:/Users/BTR75544/Downloads/script_test/script_test/script_test/python\setup.py
Unknown Extension options: 'annotate'
Traceback (most recent call last):
  File "C:\Users\BTR75544\nightly\MantidInstall\bin\lib\distutils\core.py", line 134, in setup
    ok = dist.parse_command_line()
  File "C:\Users\BTR75544\nightly\MantidInstall\bin\lib\distutils\dist.py", line 501, in parse_command_line
    raise DistutilsArgError("no commands supplied")
distutils.errors.DistutilsArgError: no commands supplied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\BTR75544\nightly\MantidInstall\bin\lib\site-packages\workbench\app\start.py", line 170, in create_and_launch_workbench
    main_window.setup()
  File "C:\Users\BTR75544\nightly\MantidInstall\bin\lib\site-packages\workbench\app\mainwindow.py", line 172, in setup
    from workbench.plugins.editor import MultiFileEditor
  File "C:\Users\BTR75544\nightly\MantidInstall\bin\lib\site-packages\workbench\plugins\editor.py", line 18, in <module>
    from mantidqt.widgets.codeeditor.multifileinterpreter import MultiPythonFileInterpreter
  File "C:\Users\BTR75544\nightly\MantidInstall\bin\lib\site-packages\mantidqt\widgets\codeeditor\multifileinterpreter.py", line 20, in <module>
    from mantidqt.widgets.codeeditor.scriptcompatibility import add_mantid_api_import, mantid_api_import_needed
  File "C:\Users\BTR75544\nightly\MantidInstall\bin\lib\site-packages\mantidqt\widgets\codeeditor\scriptcompatibility.py", line 19, in <module>
    from mantid import simpleapi
  File "C:\Users\BTR75544\nightly\MantidInstall\bin\lib\site-packages\mantid\simpleapi.py", line 1352, in <module>
    _plugin_modules = _plugin_helper.load(_plugin_files)
  File "C:\Users\BTR75544\nightly\MantidInstall\bin\lib\site-packages\mantid\kernel\plugins.py", line 129, in load
    loaded += load_from_list(path)
  File "C:\Users\BTR75544\nightly\MantidInstall\bin\lib\site-packages\mantid\kernel\plugins.py", line 151, in load_from_list
    loaded += load(p)
  File "C:\Users\BTR75544\nightly\MantidInstall\bin\lib\site-packages\mantid\kernel\plugins.py", line 131, in load
    loaded += load_from_file(path)
  File "C:\Users\BTR75544\nightly\MantidInstall\bin\lib\site-packages\mantid\kernel\plugins.py", line 184, in load_from_file
    name, module = load_plugin(filepath)
  File "C:\Users\BTR75544\nightly\MantidInstall\bin\lib\site-packages\mantid\kernel\plugins.py", line 204, in load_plugin
    module = loader.run()
  File "C:\Users\BTR75544\nightly\MantidInstall\bin\lib\site-packages\mantid\kernel\plugins.py", line 49, in run
    return SourceFileLoader(name, pathname).load_module()
  File "C:/Users/BTR75544/Downloads/script_test/script_test/script_test/python\setup.py", line 25, in <module>
    setup(
  File "C:\Users\BTR75544\nightly\MantidInstall\bin\lib\distutils\core.py", line 136, in setup
    raise SystemExit(gen_usage(dist.script_name) + "\nerror: %s" % msg)
SystemExit: usage: MantidWorkbench-script.pyw [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: MantidWorkbench-script.pyw --help [cmd1 cmd2 ...]
   or: MantidWorkbench-script.pyw --help-commands
   or: MantidWorkbench-script.pyw cmd --help

error: no commands supplied
InternetHelper-[Debug] Sending https POST request to: https://reports.mantidproject.org/api/feature
InternetHelper-[Debug] Answer from web: 201 Created
InstrumentDataService-[Debug] class Mantid::Kernel::DataService<class Mantid::Geometry::Instrument> * __ptr64 cleared.
AnalysisDataService-[Debug] class Mantid::Kernel::DataService<class Mantid::API::Workspace> * __ptr64 cleared.
PropertyManagerDataService-[Debug] class Mantid::Kernel::DataService<class Mantid::Kernel::PropertyManager> * __ptr64 cleared.
PS C:\Users\BTR75544\nightly\MantidInstall\bin> .\python MantidWorkbench-script.pyw
Traceback (most recent call last):
  File "MantidWorkbench-script.pyw", line 3, in <module>
    import workbench.app.main
  File "C:\Users\BTR75544\nightly\MantidInstall\bin\lib\site-packages\workbench\app\main.py", line 11, in <module>
    from mantid import __version__ as mtd_version
  File "C:\Users\BTR75544\nightly\MantidInstall\bin\lib\site-packages\mantid\__init__.py", line 72, in <module>
    raise ImportError(
ImportError: Broken installation! Unable to find Mantid.properties file.
Directories searched: C:\Users\BTR75544\nightly\MantidInstall\bin\lib\site-packages, C:\Users\BTR75544\nightly\MantidInstall\bin, C:\Users\BTR75544\nightly\MantidInstall\bin\Library\bin, C:\Users\BTR75544\nightly\MantidInstall\bin, C:\Users\BTR75544\nightly\MantidInstall\bin\python38.zip, C:\Users\BTR75544\nightly\MantidInstall\bin\DLLs, C:\Users\BTR75544\nightly\MantidInstall\bin\lib, C:\Users\BTR75544\nightly\MantidInstall\bin, C:\Users\BTR75544\nightly\MantidInstall\scripts, C:\Users\BTR75544\nightly\MantidInstall\scripts\Calibration, C:\Users\BTR75544\nightly\MantidInstall\scripts\DiamondAttenuationCorrection, C:\Users\BTR75544\nightly\MantidInstall\scripts\Diffraction, C:\Users\BTR75544\nightly\MantidInstall\scripts\Engineering, C:\Users\BTR75544\nightly\MantidInstall\scripts\GSAS-II, C:\Users\BTR75544\nightly\MantidInstall\scripts\Inelastic, C:\Users\BTR75544\nightly\MantidInstall\scripts\Interface, C:\Users\BTR75544\nightly\MantidInstall\scripts\Reflectometry, C:\Users\BTR75544\nightly\MantidInstall\scripts\SANS, C:\Users\BTR75544\nightly\MantidInstall\scripts\SCD_Reduction, C:\Users\BTR75544\nightly\MantidInstall\scripts\TemporaryREF_MScripts, C:\Users\BTR75544\nightly\MantidInstall\scripts\ExternalInterfaces, C:\Users\BTR75544\nightly\MantidInstall\bin\lib\site-packages, C:\Users\BTR75544\nightly\MantidInstall\bin\lib\site-packages\win32, C:\Users\BTR75544\nightly\MantidInstall\bin\lib\site-packages\win32\lib, C:\Users\BTR75544\nightly\MantidInstall\bin\lib\site-packages\Pythonwin
```

**Comment by AnthonyLim23** [comment]
[script_test.zip](https://github.com/mantidproject/mantid/files/9799192/script_test.zip)
