### ISSUE TITLE
Windows Workbench will not start if non-ascii character in username

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#35091]
**Original reporter:** João

**Describe the bug**
The function `mantid.kernel.config.getAppDataDirectory()`  does not correctly parse the username `Usuário` (Portuguese for Username) and looks for the incorrect APPDATA path inside: `C:\Users\Usußrio`. 

**To Reproduce**
Hard to reproduce but try to launch workbench for the first time on Windows with a non-ascii character such as `á` in the username.

```
C:\Users\Usuário>C:\MantidInstall\bin\python.exe
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import qtpy.QtCore
>>>
>>> import mantid.simpleapi
ConfigService-[Error] Cannot create the local instrument cache directory [C:\Users\Usußrio\AppData\Roaming\mantidproject\mantid\instrument\]. Mantid will not be able to update instrument definitions.
ConfigService-[Error] Access to file denied
ConfigService-[Error] Cannot create the local instrument geometry cache directory [C:\Users\Usußrio\AppData\Roaming\mantidproject\mantid\instrument\]. Mantid will be slower at viewing complex instruments.
ConfigService-[Error] Access to file denied
FrameworkManager-[Notice] Welcome to Mantid 6.5.0
FrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid6.5
Python-[Warning] Failed to load plugin C:/MantidInstall/plugins/python\algorithms/OrderWorkspaceHistory.py.
Error: Traceback (most recent call last):
  File "C:\MantidInstall\bin\lib\site-packages\mantid\kernel\plugins.py", line 184, in load_from_file
    name, module = load_plugin(filepath)
  File "C:\MantidInstall\bin\lib\site-packages\mantid\kernel\plugins.py", line 204, in load_plugin
    module = loader.run()
  File "C:\MantidInstall\bin\lib\site-packages\mantid\kernel\plugins.py", line 49, in run
    return SourceFileLoader(name, pathname).load_module()
  File "<frozen importlib._bootstrap_external>", line 522, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1022, in load_module
  File "<frozen importlib._bootstrap_external>", line 847, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:/MantidInstall/plugins/python\algorithms/OrderWorkspaceHistory.py", line 22, in <module>
    _default_folder = os.path.join(mantid.kernel.config.getAppDataDirectory(), "recovery")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 12: invalid continuation byte
```

**Expected behavior**
- Our appdata parser works for non-ascii usernames
- the simpleapi should log warnings but not prevent opening! This problem is logged as a Python warning and then proceeds with an error and stacktrace! An improvement to the simpleapi would be a good long term fix here!

**Platform/Version (please complete the following information):**
 - OS: Windows 10
 - OS Version:
 - Mantid Version Found in 6.5 but probably been a problem before

**Comment by DanielMurphy22** [comment]
When a solution is found, then we should decide how risky it is to include in this upcoming release.
