### ISSUE TITLE
Workbench crashes upon open when a user plugins directory is set

### ISSUE THREAD

**Issue by MialLewis** [mantidproject/mantid#35479]
**Describe the bug**
If a user plugins directory is set, mantid crashes the next time it is opened. In order to fix this you need to clear the mantid user properties cache.

**To Reproduce**
1) `File` > `Manage user directories`
2) Select the `Python Script Directories` tab
3) Under the `Python Extensions` header, Browse to a directory. Press Ok.
4) Restart workbench and observe crash.

**Expected behaviour**
No crash

**Platform/Version (please complete the following information):**
Confirmed to occur on windows and linux (ubuntu-18.04).

**Additional context**
Stack trace:

```
FrameworkManager-[Notice] Welcome to Mantid 6.6.20230322.1523.dev59
FrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid
Traceback (most recent call last):
  File "/home/miallewis/mambaforge/envs/mantid-developer/lib/python3.8/distutils/core.py", line 134, in setup
    ok = dist.parse_command_line()
  File "/home/miallewis/mambaforge/envs/mantid-developer/lib/python3.8/distutils/dist.py", line 501, in parse_command_line
    raise DistutilsArgError("no commands supplied")
distutils.errors.DistutilsArgError: no commands supplied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/miallewis/mantid/qt/applications/workbench/workbench/app/start.py", line 183, in create_and_launch_workbench
    main_window.setup()
  File "/home/miallewis/mantid/qt/applications/workbench/workbench/app/mainwindow.py", line 173, in setup
    from workbench.plugins.editor import MultiFileEditor
  File "/home/miallewis/mantid/qt/applications/workbench/workbench/plugins/editor.py", line 18, in <module>
    from mantidqt.widgets.codeeditor.multifileinterpreter import MultiPythonFileInterpreter
  File "/home/miallewis/mantid/qt/python/mantidqt/mantidqt/widgets/codeeditor/multifileinterpreter.py", line 20, in <module>
    from mantidqt.widgets.codeeditor.scriptcompatibility import add_mantid_api_import, mantid_api_import_needed
  File "/home/miallewis/mantid/qt/python/mantidqt/mantidqt/widgets/codeeditor/scriptcompatibility.py", line 19, in <module>
    from mantid import simpleapi
  File "/home/miallewis/mantid/Framework/PythonInterface/mantid/simpleapi.py", line 1373, in <module>
    _plugin_modules = _plugin_helper.load(_plugin_files)
  File "/home/miallewis/mantid/Framework/PythonInterface/mantid/kernel/plugins.py", line 131, in load
    loaded += load_from_list(path)
  File "/home/miallewis/mantid/Framework/PythonInterface/mantid/kernel/plugins.py", line 154, in load_from_list
    loaded += load(p)
  File "/home/miallewis/mantid/Framework/PythonInterface/mantid/kernel/plugins.py", line 133, in load
    loaded += load_from_file(path)
  File "/home/miallewis/mantid/Framework/PythonInterface/mantid/kernel/plugins.py", line 189, in load_from_file
    name, module = load_plugin(filepath)
  File "/home/miallewis/mantid/Framework/PythonInterface/mantid/kernel/plugins.py", line 210, in load_plugin
    module = loader.run()
  File "/home/miallewis/mantid/Framework/PythonInterface/mantid/kernel/plugins.py", line 49, in run
    return SourceFileLoader(name, pathname).load_module()
  File "/home/miallewis/vesuvio/setup.py", line 96, in <module>
    setup(**setup_args)
  File "/home/miallewis/mambaforge/envs/mantid-developer/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/home/miallewis/mambaforge/envs/mantid-developer/lib/python3.8/distutils/core.py", line 136, in setup
    raise SystemExit(gen_usage(dist.script_name) + "\nerror: %s" % msg)
SystemExit: usage: workbench [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: workbench --help [cmd1 cmd2 ...]
   or: workbench --help-commands
   or: workbench cmd --help
```

**Comment by MialLewis** [comment]
Needs to be fixed if still exists

**Comment by thomashampson** [comment]
I think we can close this thanks to https://github.com/mantidproject/mantid/pull/41288. If a similar problem appears in the future we can open a new issue.
