### ISSUE TITLE
Editing axis label in 3D plot causes unhandled exception

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#36108]
**Describe the bug**
Editing the axis labels in a 3D surface plot will sometimes cause this problem:

```
Traceback (most recent call last):
  File "C:\MantidInstall\bin\lib\site-packages\workbench\plotting\propertiesdialog.py", line 50, in on_ok
    self.canvas.draw()
  File "C:\MantidInstall\bin\lib\site-packages\matplotlib\backends\backend_agg.py", line 405, in draw
    self.figure.draw(self.renderer)
  File "C:\MantidInstall\bin\lib\site-packages\matplotlib\artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "C:\MantidInstall\bin\lib\site-packages\matplotlib\artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "C:\MantidInstall\bin\lib\site-packages\matplotlib\figure.py", line 3081, in draw
    self.patch.draw(renderer)
  File "C:\MantidInstall\bin\lib\site-packages\matplotlib\artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "C:\MantidInstall\bin\lib\site-packages\matplotlib\patches.py", line 589, in draw
    self._draw_paths_with_artist_properties(
  File "C:\MantidInstall\bin\lib\site-packages\matplotlib\patches.py", line 574, in _draw_paths_with_artist_properties
    renderer.draw_path(gc, *draw_path_args)
  File "C:\MantidInstall\bin\lib\site-packages\matplotlib\backends\backend_agg.py", line 187, in draw_path
    raise OverflowError(msg) from None
OverflowError: Exceeded cell block limit in Agg, however for the following reasons:

- can not split filled path
- path.should_simplify is False

we can not automatically split up this path to draw.

Please manually simplify your path.

```

**To Reproduce**
Attempt to edit the axis labels in a 3D surface plot.

**Expected behavior**
Working fine.

**Platform/Version (please complete the following information):**
 - OS: all
 - Mantid Version: 6.7 and maybe earlier

**Additional context**

**Comment by jclarkeSTFC** [comment]
I think this is the same problem as in #36264 and #35750, I can reproduce consistently using the instructions in #36264.
