### ISSUE TITLE
Crash when changing color/axes limits in surface plot

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#36264]
**Describe the bug**
Changing color limit of 3D surface plot using figure options (or double click on z-azis) 
```
Traceback (most recent call last):
  File "/home/l1115324/.conda/envs/mantid6.8_env/lib/python3.10/site-packages/workbench/plotting/propertiesdialog.py", line 50, in on_ok
    self.canvas.draw()
  File "/home/l1115324/.conda/envs/mantid6.8_env/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 405, in draw
    self.figure.draw(self.renderer)
  File "/home/l1115324/.conda/envs/mantid6.8_env/lib/python3.10/site-packages/matplotlib/artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/home/l1115324/.conda/envs/mantid6.8_env/lib/python3.10/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/home/l1115324/.conda/envs/mantid6.8_env/lib/python3.10/site-packages/matplotlib/figure.py", line 3081, in draw
    self.patch.draw(renderer)
  File "/home/l1115324/.conda/envs/mantid6.8_env/lib/python3.10/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/home/l1115324/.conda/envs/mantid6.8_env/lib/python3.10/site-packages/matplotlib/patches.py", line 589, in draw
    self._draw_paths_with_artist_properties(
  File "/home/l1115324/.conda/envs/mantid6.8_env/lib/python3.10/site-packages/matplotlib/patches.py", line 574, in _draw_paths_with_artist_properties
    renderer.draw_path(gc, *draw_path_args)
  File "/home/l1115324/.conda/envs/mantid6.8_env/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 187, in draw_path
    raise OverflowError(msg) from None
OverflowError: Exceeded cell block limit in Agg, however for the following reasons:

- can not split filled path
- path.should_simplify is False

we can not automatically split up this path to draw.

Please manually simplify your path.

```

**To Reproduce**

(1) Load `LOQ74041`
(2) Right-click > Plot > 3D > surface
(3) Double-click on colorbar axis
(4) Change max to 1
(5) Click OK

This will hang and then eventually crash mantid 

**Expected behavior**
No crash, limit would be changed

**Screenshots**
![image](https://github.com/mantidproject/mantid/assets/55979119/88e23d88-c730-4c6b-86bb-4237334c7c40)

**Platform/Version (please complete the following information):**
- Seen on IDAaaS Rocky 8

**Additional context**

**Comment by RichardWaiteSTFC** [comment]
Seen on v6.7 so changed milestone to v6.9
