### ISSUE TITLE
Exception when open fitbrowser or superplot when plotting 1D MDHisto workspace

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#36637]
**Describe the bug**
Found by Pascal (WISH)
Opening fit browser or superplot on a 1D MDHisto workspace (e.g. as created on the non-axis aligned cutting tool in sliceviewer) causes an exception.

**To Reproduce**
(1) Make 1D MDHisto object 

```
Load(Filename='/archive/ndxsxd/Instrument/data/cycle_10_3/SXD23767.raw', OutputWorkspace='SXD23767')
ConvertToDiffractionMDWorkspace(InputWorkspace='SXD23767', OutputWorkspace='SXD23767_MD', OneEventPerBin=False)
BinMD(InputWorkspace='SXD23767_MD', AxisAligned=False, BasisVector0='(0.0+1.0x 0.15 0.19), in 1.0 Ang^-1, 1.0,0.0,0.0', BasisVector1='u2, in 1.0 Ang^-1, 0.0,-1.0,0.0', BasisVector2='u3, in 1.0 Ang^-1, 0.0,0.0,1.0', OutputExtents='-8.12182,8.80245,-0.626105,0.317822,0.138,0.238', OutputBins='50,1,1', NormalizeBasisVectors=False, OutputWorkspace='SXD23767_MD_1Dcut')
```
(2) Plot `SXD23767_MD_1Dcut` (right-click > PLot > PLot 1D MD Histogram)

(3) Click Fit in toolbar to open fit browser
```
Traceback (most recent call last):
  File "/opt/mantidworkbenchnightly/lib/python3.10/site-packages/workbench/plotting/figuremanager.py", line 407, in fit_toggle
    self.fit_browser.show()
  File "/opt/mantidworkbenchnightly/lib/python3.10/site-packages/mantidqt/widgets/fitpropertybrowser/fitpropertybrowser.py", line 194, in show
    self._add_spectra(allowed_spectra)
  File "/opt/mantidworkbenchnightly/lib/python3.10/site-packages/mantidqt/widgets/fitpropertybrowser/fitpropertybrowser.py", line 105, in _add_spectra
    self.addAllowedSpectra(name, spec_list)
TypeError: index 0 has type 'NoneType' but 'int' is expected
```

(4) Click superplot
```
Traceback (most recent call last):
  File "/opt/mantidworkbenchnightly/lib/python3.10/site-packages/workbench/plotting/figuremanager.py", line 435, in superplot_toggle
    self._superplot_show()
  File "/opt/mantidworkbenchnightly/lib/python3.10/site-packages/workbench/plotting/figuremanager.py", line 411, in _superplot_show
    self.superplot = Superplot(self.canvas, self.window)
  File "/opt/mantidworkbenchnightly/lib/python3.10/site-packages/mantidqt/widgets/superplot/presenter.py", line 51, in __init__
    self._sync_with_current_plot()
  File "/opt/mantidworkbenchnightly/lib/python3.10/site-packages/mantidqt/widgets/superplot/presenter.py", line 187, in _sync_with_current_plot
    spec_index = args[i]["wkspIndex"]
KeyError: 'wkspIndex'
```

**Expected behavior**
Would not crash, maybe print warning to user to say not possible (though would be good to be able to fit 1D MDHisto workspaces)

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: [e.g. Windows, RHEL 7, Ubuntu, macOS]
 - OS Version:
 - Mantid Version [e.g. 6.0.0]

**Additional context**

**Comment by RichardWaiteSTFC** [comment]
Instead of step 1 can also make a fake 1D MDHisto workspace like so 
```
CreateMDWorkspace(Dimensions=3, Extents='-5,5,-4,4,-3,3', Names='H,K,L', Units='r.l.u.,r.l.u.,r.l.u.', Frames='HKL,HKL,HKL', SplitInto='2', SplitThreshold=50, OutputWorkspace='ws')
FakeMDEventData(InputWorkspace='ws', UniformParams='100000', PeakParams='100000,0,0,1,0.3', RandomSeed=3873875)
ws_cut = BinMD(InputWorkspace='ws', AxisAligned=False, BasisVector0='(0.0+1.0x 0.0 0.0), in 7.26 Ang^-1, 1.0,0.0,0.0', BasisVector1='u2, in 7.26 Ang^-1, 0.0,1.0,0.0', BasisVector2='u3, in 3.14 Ang^-1, 0.0,0.0,1.0', 
               OutputExtents='-2.5,2.5,-0.16,0.16,-0.05,0.05', OutputBins='50,1,1', NormalizeBasisVectors=False, OutputWorkspace='ws_1Dcut')

```
