### ISSUE TITLE
MSlice throws error when trying to remove bragg peak lines

### ISSUE THREAD

**Issue by GuiMacielPereira** [mantidproject/mantid#36749]
**Describe the bug**
Open a slice plot > Information > Bragg peaks > select some bragg peaks
Then try to deselect any bragg peak

The following error is produced: 

```
Traceback (most recent call last):
  File "/home/ljg28444/Downloads/mantidworkbenchnightly-6.8.20240123.1153-latest/mantidworkbenchnightly/scripts/ExternalInterfaces/mslice/plotting/plot_window/overplot_interface.py", line 38, in toggle_overplot_line
    plotter_presenter.hide_overplot_line(plot_handler.ws_name, key)
  File "/home/ljg28444/Downloads/mantidworkbenchnightly-6.8.20240123.1153-latest/mantidworkbenchnightly/scripts/ExternalInterfaces/mslice/presenters/slice_plotter_presenter.py", line 91, in hide_overplot_line
    remove_line(line)
  File "/home/ljg28444/Downloads/mantidworkbenchnightly-6.8.20240123.1153-latest/mantidworkbenchnightly/scripts/ExternalInterfaces/mslice/plotting/plot_window/overplot_interface.py", line 71, in remove_line
    plt.gca().lines.remove(line)
AttributeError: 'ArtistList' object has no attribute 'remove'
``` 

This is likely due to matpplotlib having been updated.

**Platform/Version (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS
 - OS Version:
 - Mantid Version: 

**Additional context**

**Comment by GuiMacielPereira** [comment]
- Transfered this issue over to the mslice repository: https://github.com/mantidproject/mslice/issues/967
