### ISSUE TITLE
LET nexus files loading error

### ISSUE THREAD

**Issue by sf1919** [mantidproject/mantid#36988]
**Original reporter:**
@mducle 

**Describe the bug**
When attempting to show detectors for run `LET00100769` the following error occurs.

```
   Stack Trace:
        Traceback (most recent call last):
  File "/opt/mantidworkbenchnightly/lib/python3.10/site-packages/workbench/plugins/workspacewidget.py", line 324, in _do_show_detectors
    task.start()
  File "/opt/mantidworkbenchnightly/lib/python3.10/site-packages/mantidqt/utils/asynchronous.py", line 148, in start
    raise self.recv.exc_value
  File "/opt/mantidworkbenchnightly/lib/python3.10/site-packages/mantidqt/utils/asynchronous.py", line 63, in run
    out = self.target(*self.args, **self.kwargs)
  File "/opt/mantidworkbenchnightly/lib/python3.10/site-packages/workbench/plugins/workspacewidget.py", line 333, in _run_create_detector_table
    CreateDetectorTable(InputWorkspace=ws)
  File "/opt/mantidworkbenchnightly/lib/python3.10/site-packages/mantid/simpleapi.py", line 1083, in __call__
    algm.execute()
ValueError: Run::getPropertyValueAsType - 'Ei' is not of the requested type
```  

**To Reproduce**
1. Load `LET00100769.nxs` (or another recent LET file)
2. Right click on workspace and click `Show Detectors` 

**Expected behavior**
A table of detectors is added to the ADS and opens in data table view automatically.

**Platform/Version (please complete the following information):**
 - OS: Rocky Linux 8.9 (IDAaaS)
 - Mantid Version: 6.9.20240228.1632
 
 - OS: Windows 10
 - Mantid Version: v6.9 & v6.8

**Additional context**

After further investigation this issue appears in Mantid v6.8 and v6.9. It seems to be occuring on `.nxs` files from LET from 2022 onwards. Earlier nexus files have no problem with `Show Detectors`.

There is a work around for this issue at present - Running `ConvertUnits` before Show Detectors prevents the error from occurring. However a more robust solution would be preferable.

**Comment by SilkeSchomann** [comment]
This issue can be closed. The fix was merged through this PR: https://github.com/mantidproject/mantid/pull/37101
