### ISSUE TITLE
Crash when plotting Quasi result data with errors

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#37973]
**Reported by:** Mona Sarter

**Description**
There is a crash when attempting to plot data from a workspace which contains some negative values in the error data. This crash should be avoided. Perhaps a warning should be shown instead that some of the errors are negative and that this should be investigated why.

Need a second opinion on this: Do we then attempt to plot the data but taking the absolute positive value of the errors?

**Solutions considered**
- [ ] Preventing the crash and showing a warning @jhaigh0 (https://github.com/mantidproject/mantid/pull/37984)
- [x] Investigate why we have negative errors in the first place @robertapplin (https://github.com/mantidproject/mantid/pull/37975)

**To reproduce**
1. Open Inelastic Bayes Fitting
2. Go to Quasi tab
3. Load following sample and resolution
[BCA299_Subtract.zip](https://github.com/user-attachments/files/16991209/BCA299_Subtract.zip)
[vanadium.zip](https://github.com/user-attachments/files/16991210/vanadium.zip)

5. Set EMin EMax to -0.075 and 0.075
6. Click `Run`
7. Right click the output workspace ending in `_Result`
8. Choose Plot-> SPectrum with errors
9. Choose 6-8 and click Ok
10. Crashes with this error:

```
Traceback (most recent call last):
  File "C:\Users\mlc47243\Documents\mantid-dev\mantid-1\mantid\qt\applications\workbench\workbench\plugins\workspacewidget.py", line 172, in _do_plot_spectrum
    plot_from_names(names, errors, overplot, advanced=advanced)
  File "C:\Users\mlc47243\Documents\mantid-dev\mantid-1\mantid\qt\python\mantidqt\mantidqt\plotting\functions.py", line 185, in plot_from_names
    return plot(
  File "C:\Users\mlc47243\Documents\mantid-dev\mantid-1\mantid\Framework\PythonInterface\mantid\plots\plotfunctions.py", line 89, in inner_func
    return func(workspaces, *args, **kwargs)
  File "C:\Users\mlc47243\Documents\mantid-dev\mantid-1\mantid\Framework\PythonInterface\mantid\plots\plotfunctions.py", line 224, in plot
    _do_single_plot(ax, workspaces, errors, show_title, nums, kw, plot_kwargs, log_name, log_values)
  File "C:\Users\mlc47243\Documents\mantid-dev\mantid-1\mantid\Framework\PythonInterface\mantid\plots\plotfunctions.py", line 601, in _do_single_plot
    plot_fn(ws, **plot_kwargs)
  File "C:\Users\mlc47243\Documents\mantid-dev\mantid-1\mantid\Framework\PythonInterface\mantid\plots\mantidaxes.py", line 45, in wrapper
    func_value = func(self, *args, **kwargs)
  File "C:\Users\mlc47243\Documents\mantid-dev\mantid-1\mantid\Framework\PythonInterface\mantid\plots\mantidaxes.py", line 815, in errorbar
    axesfunctions.errorbar(self, normalize_by_bin_width=is_normalized, *args, **kwargs),
  File "C:\Users\mlc47243\Documents\mantid-dev\mantid-1\mantid\Framework\PythonInterface\mantid\plots\axesfunctions.py", line 289, in errorbar
    return axes.errorbar(x, y, dy, dx, *args, **kwargs)
  File "C:\Users\mlc47243\Documents\mantid-dev\mantid-1\mantid\Framework\PythonInterface\mantid\plots\mantidaxes.py", line 45, in wrapper
    func_value = func(self, *args, **kwargs)
  File "C:\Users\mlc47243\Documents\mantid-dev\mantid-1\mantid\Framework\PythonInterface\mantid\plots\mantidaxes.py", line 823, in errorbar
    errorbar_container = Axes.errorbar(self, *args, **kwargs)
  File "C:\Users\mlc47243\AppData\Local\mambaforge\envs\mantid-developer\lib\site-packages\matplotlib\__init__.py", line 1446, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "C:\Users\mlc47243\AppData\Local\mambaforge\envs\mantid-developer\lib\site-packages\matplotlib\axes\_axes.py", line 3636, in errorbar
    raise ValueError(
ValueError: 'yerr' must not contain negative values
```

**Other Info**
Found on Windows nightly

**Comment by SpencerHowells** [comment]
@robertapplin the sample data is the subtraction of 2 workspaces so the problem is there. Are there negative data values?

**Comment by robertapplin** [comment]
> @robertapplin the sample data is the subtraction of 2 workspaces so the problem is there. Are there negative data values?

I see, yes there are some negative values in the input sample data.

I have also found the error propagation for the EISF errors might not be completely right, thanks to some help from @RichardWaiteSTFC .

[mantid/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/BayesQuasi.py](https://github.com/mantidproject/mantid/blob/c100135e10239b87a486fa275ce07c1660255a34/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/BayesQuasi.py#L660)

Line 660 in [c100135](https://github.com/mantidproject/mantid/commit/c100135e10239b87a486fa275ce07c1660255a34)

 EISF_error = EISF_data * np.sqrt((height_error**2 / height_data**2) + (total_error / total**2)) 
I am going to investigate this too and see if I get a different formula because of the "height" dependence in the "total"

**Comment by jhaigh0** [comment]
When testing this, I don't get a crash. I get one of these uncaught exception warnings that allows you to coninue

![image](https://github.com/user-attachments/assets/365ae473-7476-4582-8b97-20b340c2f3eb)
