### ISSUE TITLE
Module load error on IDAaaS

### ISSUE THREAD

**Issue by jclarkeSTFC** [mantidproject/mantid#38011]
**Describe the bug**
Certain plugins on IDAaaS generate an error on starting Workbench, and some scripts won't run, the error below is produced

```
Welcome to Mantid 6.10.20240916.1815
Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid
Could not open library /opt/mantidworkbenchnightly/plugins/libMantidCrystal.so: libMantidDataHandling.so: cannot open shared object file: No such file or directory
Failed to load plugin /opt/mantidworkbenchnightly/plugins/python/algorithms/BASISCrystalDiffraction.py.
Error: Traceback (most recent call last):
  File "/opt/mantidworkbenchnightly/lib/python3.10/site-packages/mantid/kernel/plugins.py", line 198, in load_from_file
    name, module = load_plugin(filepath)
  File "/opt/mantidworkbenchnightly/lib/python3.10/site-packages/mantid/kernel/plugins.py", line 219, in load_plugin
    module = loader.run()
  File "/opt/mantidworkbenchnightly/lib/python3.10/site-packages/mantid/kernel/plugins.py", line 52, in run
    loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/mantidworkbenchnightly/plugins/python/algorithms/BASISCrystalDiffraction.py", line 28, in <module>
    from mantid.simpleapi import (
ImportError: cannot import name 'SetGoniometer' from partially initialized module 'mantid.simpleapi' (most likely due to a circular import) (/opt/mantidworkbenchnightly/lib/python3.10/site-packages/mantid/simpleapi.py)
```

**To Reproduce**
Start the nightly on IDAaaS

**Expected behavior**
No errors

**Screenshots**

![image](https://github.com/user-attachments/assets/dcab880a-f93b-4ae4-b092-3e19fce04ee3)

**Platform/Version (please complete the following information):**
 - OS: Rocky Linux
 - OS Version:
 - Mantid Version 6.10.20240916.1815

**Comment by rbauststfc** [comment]
Just to flag, this happened for me on a Windows install.

**Comment by perenon** [comment]
Happened also to me on Linux conda install

**Comment by jclarkeSTFC** [comment]
This is not fixed
