### ISSUE TITLE
Crash due to workspace rename in Mslice 

### ISSUE THREAD

**Issue by yusufjimoh** [mantidproject/mantid#38076]
In MSlice I renamed a workspace to a similar name with different capitalisation and this caused Mantid to crash. I have not attempted to reproduce the error.

Stack Trace:
```
Traceback (most recent call last):
File "/opt/mantidworkbench6.10/scripts/ExternalInterfaces/mslice/app/mainwindow.py", line 180, in button_rename
self.workspace_presenter.notify(ws_command.RenameWorkspace)
File "/opt/mantidworkbench6.10/scripts/ExternalInterfaces/mslice/presenters/workspace_manager_presenter.py", line 52, in notify
self._command_map[command](https://github.com/ISISNeutronMuon/mantid-isis-support/issues/248)
File "/opt/mantidworkbench6.10/scripts/ExternalInterfaces/mslice/presenters/workspace_manager_presenter.py", line 137, in _rename_workspace
rename_workspace(selected_workspace, new_name)
File "/opt/mantidworkbench6.10/scripts/ExternalInterfaces/mslice/models/workspacemanager/workspace_provider.py", line 31, in rename_workspace
workspace.name = new_name
File "/opt/mantidworkbench6.10/scripts/ExternalInterfaces/mslice/workspace/workspace.py", line 34, in name
rename_workspace(raw_name, re.sub(rf"{re.escape(self.name)}\w*", new_name, raw_name))
File "/opt/mantidworkbench6.10/scripts/ExternalInterfaces/mslice/workspace/helperfunctions.py", line 101, in rename_workspace
RenameWorkspace(InputWorkspace=old_name, OutputWorkspace=new_name)
File "/opt/mantidworkbench6.10/lib/python3.10/site-packages/mantid/simpleapi.py", line 571, in RenameWorkspace
return _gather_returns("RenameWorkspace", lhs, algm)
RuntimeError: Unable to find Data Object type with name '__MSLDMF-d6 650meV': data service search object '__MSLDMF-d6 650meV'
```

**Platform/Version:**
 - OS: Rocky Linux 8.10 (Green Obsidian)
 - Mantid Version: 6.10.0

**Comment by GuiMacielPereira** [comment]
Easier to track this on mslice repo https://github.com/mantidproject/mslice/issues/1001
