### ISSUE TITLE
DNS Reduction interface does not open

### ISSUE THREAD

**Issue by SilkeSchomann** [mantidproject/mantid#38249]
**Describe the bug**
The `DNS Reduction` interface in `Direct` throws an error message when opened:

```
Traceback (most recent call last):
  File "/Users/silke.schomann/mambaforge/envs/mantid_smoke/lib/python3.10/site-packages/workbench/app/mainwindow.py", line 393, in <lambda>
    action.triggered.connect(lambda checked_py, script=script: self.launch_custom_python_gui(script))
  File "/Users/silke.schomann/mambaforge/envs/mantid_smoke/lib/python3.10/site-packages/workbench/app/mainwindow.py", line 353, in launch_custom_python_gui
    self.interface_executor.execute(open(filename).read(), filename)
  File "/Users/silke.schomann/mambaforge/envs/mantid_smoke/lib/python3.10/site-packages/mantidqt/widgets/codeeditor/execution.py", line 153, in execute
    executor.execute(code_str, filename, flags, self.globals_ns, line_offset)
  File "/Users/silke.schomann/mambaforge/envs/mantid_smoke/lib/python3.10/site-packages/mantidqtinterfaces/DNS_Reduction.py", line 24, in <module>
    from mantidqtinterfaces.dns_powder_tof.main_widget import DNSReductionGuiWidget
  File "/Users/silke.schomann/mambaforge/envs/mantid_smoke/lib/python3.10/site-packages/mantidqtinterfaces/dns_powder_tof/main_widget.py", line 13, in <module>
    from mantidqtinterfaces.dns_powder_tof.dns_modus import DNSModus
  File "/Users/silke.schomann/mambaforge/envs/mantid_smoke/lib/python3.10/site-packages/mantidqtinterfaces/dns_powder_tof/dns_modus.py", line 29, in <module>
    from mantidqtinterfaces.dns_single_crystal_elastic.options.elastic_single_crystal_options_widget import DNSElasticSCOptionsWidget
ModuleNotFoundError: No module named 'mantidqtinterfaces.dns_single_crystal_elastic'
```

**To Reproduce**
Navigate to the `Direct` menu and click on `DNS Reduction`.

**Comment by robertapplin** [comment]
Fixed as part of #2825
